INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('Q41', 'Joule por metro cúbico normalizado', 'Joule por metro cúbico normalizado (temperatura 0 ° C y presión 101325 milibares).', NULL),
('Q42', 'Joule por metro cúbico estándar', 'Joule por metro cúbico normalizado (temperatura 15 ° C y presión 101325 milibares).', NULL),
('QA', 'Página-fascimil', 'Unidad de conteo que define el número de páginas fascimil', NULL),
('QAN', 'Cuarto (de un año)', 'Unidad de tiempo que define el número de años (3 meses)', NULL),
('QB', 'Página, copia impresa', 'Unidad de conteo que define el número de copias impresas', NULL),
('QD', 'Cuarta docena', NULL, NULL),
('QH', 'Un cuarto de hora', NULL, NULL),
('QK', 'Cuarto de kilogramo', NULL, NULL),
('QR', 'Mano de papel', 'Unidad de conteo para papel, expresada como el número de manos de papel (mano de papel: numero de papel en hojas, típicamente 25)', 'qr'),
('QT', 'Cuarto (EUA)', 'Utilice cuarto de galón líquido (código común QTL)', 'Qt (US)'),
('QTD', 'Cuarto seco (estados unidos)', NULL, 'dry qt (US)'),
('QTI', 'Cuarto (UK)', 'Es una unidad de medida de volumen equivalente a media fanega. En Castilla equivalía a aproximadamente a 6 celemines. La medida real cambia según regiones o incluso localidades.', 'qt (UK)'),
('QTL', 'Cuarto de líquido (estadis unidos)', NULL, 'liq qt (US)'),
('QTR', 'Cuarto', 'Unidad tradicional de peso igual a 1/4 de peso. En el Reino Unido 1/4 equivale a 28 libras.', 'Qr (UK)'),
('R1', 'Pica', 'Unidad de conteo que define el número de picas (pica: longitud tipografia igual a 12 puntos o 4,22 mm aprox)', NULL),
('R9', 'Mil metros cúbicos', 'Unidad de volumen que equivale a mil metro cúbicos', NULL),
('RH', 'Hora de funcionamiento', 'Unidad de tiempo que define el número de horas de operación', NULL),
('RK', 'Medida métrica de rollo', NULL, NULL),
('RM', 'Resma', 'Unidad de conteo para papel, espresada como el número de resmas (resma: una gran cantidad de hojas de papel, tipicamente 500)', NULL),
('RN', 'Medida métrica de Hojas (resma)', NULL, NULL),
('ROM', 'Habitación', 'Unidad de conteo que define el número de habitaciones', NULL),
('RP', 'Libra por resma', 'Unidad de masa para papel, expresada en libras por resma. (Resma: una gran cantidad de papel, tipicamente 500 hojas)', NULL),
('RPM', 'Revoluciones por minuto', 'Consulte la Guía ISO / TC12 SI', 'r/min'),
('RPS', 'Revoluciones por segundo', 'Consulte la Guía ISO / TC12 SI', 'r/s'),
('RS', 'Reiniciar', NULL, NULL),
('RT', 'Milla de toneladas de ingresos', 'Unidad de información tipicamente utilizada para propósitos de facturación, expresada como el número de toneladas en ingresos: una tonelada métrica o un metro cúbico, la que sea mayor) se movio  a una distancia de una milla', NULL),
('RU', 'correr', NULL, NULL),
('S3', 'Pie cuadrado por segundo', 'Sinónimo: pie cuadrado por segundo', 'ft²/s'),
('S4', 'Metro cuadrado por segundo', 'Sinónimo: metro cuadrado por segundo', 'm²/s'),
('S5', 'Sesenta cuartos de pulgada', NULL, NULL),
('S6', 'Sesión', NULL, NULL),
('S7', 'unidad de almacenamiento', NULL, NULL),
('S8', 'Unidad de publicidad estándar', NULL, NULL),
('SAN', 'Medio año', 'Unidad de tiempo que define el número de años', NULL),
('SCO', 'Puntuación', 'Unidad de conteo que define el número de unidades en multiplos de 20', NULL),
('SCR', 'Escrúpulo', 'El escrúpulo (en inglés apothecary scruple) era Unidad de medida utilizada en farmacia para pesar ingredientes de los medicamentos. El escrúpulo podía tener diferentes valores en cada país: en España y Portugal, un escrúpulo equivalía a 24 granos (pesando 1,55517384 gramos), mientras que en el sistema imperial inglés correspondía a 20 granos (1,2959782 gramos). En astronomía, un escrúpulo es el resultado de dividir en sesenta partes un grado de círculo.', NULL),
('SD', 'Libra sólida', NULL, NULL),
('SE', 'Sección', NULL, NULL),
('SEC', 'Segundo [unidad de tiempo]', 'Supone comúnmente una sesentava parte de un minuto (1⁄60) y es esencial para la medición en múltiples sistemas de unidades.', 's'),
('SET', 'Conjunto', 'Unidad de conteo que define el número de conjuntos (Conjunto: un número de objetos agrupados)', NULL),
('SG', 'Segmento', 'Unidad de información equivalente a 64000bytes', NULL),
('SHT', 'Tonelada de envíos', 'Unidad de masa que define el número de toneladas para el envío.', NULL),
('SIE', 'Siemens', 'Se denomina siemens a la unidad derivada del SI para la medida de la conductancia eléctrica.', 'S'),
('SK', 'Camión cisterna con división', NULL, NULL),
('SM3', 'Metro cúbico estándar', 'Metro cúbico estándar (temperatura 15 ° C y presión 101325 milibares)', NULL),
('SMI', 'Milla (milla estatal)', 'Medida de longitud, especialmente utilizada en marina, que equivale a 1,852 m.', 'mile'),
('SN', 'Barra cuadrada', NULL, 'Rd²'),
('SQ', 'Cuadrado', 'Unidad de conteo que define el número de cuadrados (cuadrado: forma rectangular)', NULL),
('SQR', 'Cuadrado y techado', 'Unidad de conteo que conteo que define el número de plazas de materiales para techos, medida en múltiplos de 100 pies cuadrados', NULL),
('SR', 'Tira', 'Unidad de conteo que define el número de tiras (pieza larga y estrecha de un objeto)', NULL),
('SS', 'Medida métrica de hoja', NULL, NULL),
('SST', 'Estandar corto (7200 partidos)', NULL, NULL),
('STC', 'Palo', 'Unidad de conteo que define el número de palos (palo: pieza delgada y a menudo cilíndirca de una sustancia)', NULL),
('STI', 'Estone (UK)', NULL, 'st'),
('STK', 'Palo, cigarrillo', 'Unidad de conteo que define el número de cigarrillos en la unidad más pequeña para el cálculo de la población y/o del trabajo', NULL),
('STL', 'Litro estándar', 'Unidad de volumen que define el número de litros de un producto a una temperatura de 15 grados celsius, especialmente en relación con los aceites de hidrocarburos', NULL),
('STN', 'Tonelada (estados unidos) o tonelada corta (UK y estados unidos)', 'Sinónimo: tonelada neta (2000 lb)', 'ton (US)'),
('STW', 'Paja', 'Unidad de conteo que define el número de pajitas (paja:un tubo delgado utilizado para succionar liquidos)', NULL),
('SW', 'Número de madejas', 'Unidad de conteo que define el número de madejas (skein:un paquete de hilo o hilo suelto)', NULL),
('SX', 'Envío', 'Unidad de conteo que define el número de envíos (embarque: una cantidad de mercancias embarcadas o transportadas)', NULL),
('SYR', 'Jeringuilla', 'Unidad de conteo que define el número de jeringuillas (jeringa: un pequeño dispositivo para bombear, pulverizar y/o inyectar liquidos a través de una pequeña abertura)', NULL),
('T0', 'Linea de telecomunicaciones en servicio', 'Unidad de conteo que define el número de líneas de servicio', NULL),
('T1', 'Mil libras', NULL, NULL),
('T3', 'Mil pedazos', 'Unidad de conteo que define el número de piezas en múltiplos de 1000 (pieza: un solo artículo, artículo o ejemplar)', NULL),
('T4', 'Bolsa de mil', NULL, NULL),
('T5', 'Mil envolturas', NULL, NULL),
('T6', 'Mil galones (US)', NULL, NULL),
('T7', 'Impresión de mil', NULL, NULL),
('T8', 'Mil pulgadas lineales', NULL, NULL),
('TA', 'Décimo de pie cúbico', NULL, NULL),
('TAB', 'Tonelada de registro bruto', 'Una unidad de masa igual al total de las imágenes cúbicas antes de las deducciones, donde 1 registro t es igual a 100 pies cúbicos.Véase el Convenio internacional sobre el arqueo de los buques.', NULL),
('TAH', 'Kiloamperio-hora (milamperio-hora)', NULL, 'kA·h'),
('TAN', 'Número de acido total', 'Unidad de química que define la cantidad de hidróxido de potasio (KOH) en miligramos que se necesita para neutralizar los ácidos en un gramo de aceite. Es una medida importante de la calidad del petróleo crudo', 'TAN'),
('TC', 'Camión', NULL, NULL),
('TD', 'Termico', NULL, NULL),
('TE', 'Totalizador', NULL, NULL),
('TF', 'Diez yardas cuadradas', NULL, NULL),
('TI', 'Mil pulgadas cuadradas', 'Unidad de medida imperial', NULL),
('TIC', 'Tonelada métrica, incluido el contenedor', 'Unidad de masa que define el número de toneladas métricas de un producto, incluyendo su contenedor', NULL),
('TIP', 'Tonelada métrica, incluido el embalaje interior', 'Unidad de masa que define el número de toneladas metricas de un producto, incluyendo sus materiales de embalaje interior', NULL),
('TJ', 'Mil centímetros cuadrados', NULL, NULL),
('TKM', 'Tonelada kilometro', 'Unidad de información típicamente usada para propósitos de facturación, expresada como el número de toneladas (toneladas métricas) movidas sobre una distancia de un kilómetro', 't·km'),
('TL', 'Mil pies (lineal)', NULL, NULL),
('TMS', 'Kilogramo de carne importada, menos despojos', 'Unidad de masa equivalente a mil gramos de carne importada, sin tener en cuenta los subproductos menos valiosos como las montañas', NULL),
('TNE', 'Tonelada (tonelada métrica)', 'Sinónimo: tonelada métrica', 't'),
('TP', 'Paquete de diez', 'Unidad de conteo que define el número de elementos en múltiplos de 10', NULL),
('TPI', 'Dientes por pulgada', 'El número de dientes por pulgada', 'TPI'),
('TPR', 'Decenas de pares', 'Unidad de conteo que define el número de pares en multiplos de 10 (par:elemento descrito por dos)', NULL),
('TQ', 'Mil pies', NULL, NULL),
('TQD', 'Mil metros cúbicos por día', 'Unidad de volumen igual a mil metros cúbicos por día', 'km³/d'),
('TR', 'Diez pies cuadrados', NULL, NULL),
('TRL', 'Trillones (eur)', 'Unidad de escala númerica', NULL),
('Ts', 'Mil pies cuadrados', NULL, NULL),
('TSD', 'Tonelada de sustancia 90% seca', NULL, NULL),
('TSH', 'Tonelada de vapor por hora', NULL, NULL),
('TST', 'Decena de conjuntos', 'Unidad de conteo que define el número de conjuntos en múltiplos de 10 (conjunto: un número de objetos agrupados)', NULL),
('TT', 'Mil metros lineales', NULL, NULL),
('TTS', 'Decenas de millar de pegatinas', 'Unidad de conteo que define el número de palos multiples de 10000 (Pegatina: pieza delgada y a menudo cilíndrica de una sustancia)', NULL),
('Tu', 'Contenedor externo', 'Tipo de caja de contención que sirve como contenedor de transporte externo, no especificado como equipo de transporte.', NULL),
('TV', 'Mil kilogramos', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();