INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('H18', 'Hectómetro cuadrado', 'Sinónimo: hectárea', 'hm²'),
('H19', 'Hectómetro cúbico', NULL, 'hm³'),
('H2', 'Medio litro', NULL, NULL),
('H20', 'Kilómetro cúbico', NULL, 'km³'),
('H21', 'Blanco', 'Unidad de conteo que define el número de blancos', NULL),
('H22', 'Voltio pulgada cuadrada por libra fuerza', NULL, 'V/(lbf/in²)'),
('H23', 'Voltio por pulgada', NULL, 'V/in'),
('H24', 'Voltio por microsegundo', NULL, 'V/µs'),
('H25', 'Por ciento por kelvin', 'Unidad de proporción, igual a 0,01, en relación con la unidad de base SI Kelvin.', '%/K'),
('H26', 'Ohm por metro', NULL, 'Ω/m'),
('H27', 'Grado por metro', NULL, '°/m'),
('H28', 'Microfaradio por kilómetro', NULL, 'µF/km'),
('H29', 'Microgramo por litro', NULL, 'µg/l'),
('H30', 'Micrómetro cuadrado', NULL, 'µm²'),
('H31', 'Amperio por kilogramo', NULL, 'A/kg'),
('H32', 'Amperio cuadrado segundo', 'Es una unidad de medida basada en la energía o el calor que se permite pasar a través del fusible o interruptor durante una condición de cortocircuito.', 'A²·s'),
('H33', 'Faradio por kilómetro', NULL, 'F/km'),
('H34', 'Hertz metro', NULL, 'Hz·m'),
('H35', 'Kelvin metro por watt', NULL, 'K·m/W'),
('H36', 'MegaOhm por kilómetro', NULL, 'MΩ/km'),
('H37', 'MegaOhm por metro', NULL, 'MΩ/m'),
('H38', 'Megaamperio', NULL, 'MA'),
('H39', 'Megahertz kilómetro', NULL, 'MHz·km'),
('H40', 'Newton por amperio', NULL, 'N/A'),
('H41', 'Newton metro watts elevado a la potencia menos 0.5', NULL, 'N·m·W⁻⁰‧⁵'),
('H42', 'Pascal por metro', NULL, 'Pa/m'),
('H43', 'Siemens por centímetro', NULL, 'S/cm'),
('H44', 'TeraOhm', NULL, 'TΩ'),
('H45', 'Voltio segundo por metro', NULL, 'V·s/m'),
('H46', 'Voltio por segundo', NULL, 'V/s'),
('H47', 'Watt por metro cúbico', NULL, 'W/m³'),
('H48', 'Attofarad', NULL, 'aF'),
('H49', 'Centímetro por hora', NULL, 'cm/h'),
('H50', 'Reciprocidad del centimetro cúbico', NULL, 'cm⁻³'),
('H51', 'Decibel per kilometro', NULL, 'dB/km'),
('H52', 'Decibel per metro', NULL, 'dB/m'),
('H53', 'Kilogramo por bar', NULL, 'kg/bar'),
('H54', 'Kilogramo por decímetro cúbico kelvin', NULL, '(kg/dm³)/K'),
('H55', 'Kilogramo por decímetro cúbico bar', NULL, '(kg/dm³)/bar'),
('H56', 'Kilogramo por metro cuadrado segundo', NULL, 'kg/(m²·s)'),
('H57', 'Pulgada por dos pi por radián', NULL, 'in/revolution'),
('H58', 'Metro por voltio segundo', NULL, 'm/(V·s)'),
('H59', 'Metro cuadrado por newton', NULL, 'm²/N'),
('H60', 'Metro cúbico por metro cúbico', NULL, 'm³/m³'),
('H61', 'Milisiemens por centímetro', NULL, 'mS/cm'),
('H62', 'Milivoltio por minuto', NULL, 'mV/min'),
('H63', 'Miligramo por centímetro cuadrado', NULL, 'mg/cm²'),
('H64', 'Miligramo por gramo', NULL, 'mg/g'),
('H65', 'Mililitro por metro cúbico', NULL, 'ml/m³'),
('H66', 'Milímetro por año', NULL, 'mm/y'),
('H67', 'Milímetro por hora', NULL, 'mm/h'),
('H68', 'MiliMol por gram', NULL, 'mmol/g'),
('H69', 'Picopascal por kilometro', NULL, 'pPa/km'),
('H70', 'Picosegundo', NULL, 'ps'),
('H71', 'Por ciento al mes', 'Unidad de proporción, igual a 0,01, en relación a un mes.', '%/mo'),
('H72', 'Por ciento por hectobar', 'Unidad de proporción, igual a 0,01, en relación con 100 veces la barra unitaria', '%/hbar'),
('H73', 'Por ciento por decakelvin', 'Unidad de proporción, igual a 0,01, en relación con 10 veces la unidad de base SI Kelvin', '%/daK'),
('H74', 'Watt por metro', NULL, 'W/m'),
('H75', 'Decapascal', NULL, 'daPa'),
('H76', 'Gramo por milímetro', NULL, 'g/mm'),
('H77', 'Anchura del módulo', 'Unidad de medida utilizada para describir la anchura de los conjuntos electrónicos como una norma de instalación o una dimensión de montaje.', 'MW'),
('H78', 'Centímetro convencional de agua', NULL, 'Cm H $ ₂ $ O'),
('H79', 'Escala francesa', 'Unidad de longitud usada para la medición de los diámetros de pequeños tubos como instrumentos urológicos y catéteres.                                                       
Sinónimos: Francés, Charrière, Charrière gauge.', 'Fg'),
('H80', 'Unidad de bastidor', 'Unidad de medida utilizada para describir la altura en unidades de bastidor del equipo destinado a ser montado en un bastidor de 19 pulgadas o un bastidor de 23 pulgadas. Unidad de bastidor tiene 1,45 pulgadas (44,45 mm) de alto.', 'U or RU'),
('H81', 'Milímetro por minuto', NULL, 'mm/min'),
('H82', 'Punto grande', 'Unidad de longitud que define el número de puntos grandes (punto grande: el software de Adobe (EUA) define el punto grande a ser exactamente 1/72 de pulgada (0,013 888 9 pulgadas o 0,352 777 8 milímetros)', 'bp'),
('H83', 'Litro por kilogramo', NULL, 'l/kg'),
('H84', 'Gramos milímetro', NULL, 'g·mm'),
('H85', 'Semana recíproca', NULL, '1/wk'),
('H87', 'Pieza', 'Unidad de conteo que define el número de piezas (pieza: un solo artículo, artículo o ejemplar).', NULL),
('H88', 'MegaOhm kilómetro', NULL, 'MΩ·km'),
('H89', 'Por ciento por Ohmio', 'Unidad de proporción, igual a 0,01, en relación con un ángulo de un grado.', '%/Ω'),
('H90', 'Porcentaje por grado', 'Unidad de proporción, igual a 0,01, en relación a múltiplos de diez mil.', '%/°'),
('H91', 'Por ciento por cada diez mil', 'Unidad de proporción, igual a 0,01, en relación a múltiplos de cien mil.', '%/10000'),
('H92', 'Ciento por cien mil', 'Unidad de proporción, igual a 0,01, en relación a múltiplos de cien.', '%/100000'),
('H93', 'Porcentaje por cien', 'Unidad de proporción, igual a 0,01, en relación a múltiplos de mil.', '%/100'),
('H94', 'Por ciento por mil', 'Unidad de proporción, igual a 0,01, en relación con la unidad derivada de SI volt.', '%/1000'),
('H95', 'Por ciento por voltio', 'Unidad de proporción, igual a 0,01, en relación con una presión atmosférica de una barra.', '%/V'),
('H96', 'Tanto por ciento por bar', 'Unidad de proporción, igual a 0,01, en relación con una presión atmosférica de una barra.', '%/bar'),
('H98', 'Por ciento por pulgada', 'Unidad de proporción, igual a 0,01, en relación a una pulgada.', '%/in'),
('H99', 'Por ciento por metro', 'Unidad de proporción, igual a 0,01, en relación con un metro.', '%/m'),
('HA', 'Madeja', 'Unidad de longitud, típicamente para el hilado.', NULL),
('HAR', 'hectárea', 'Sinónimo: hectómetro cuadrado', 'decir ah'),
('HBA', 'Hectobar', NULL, 'hbar'),
('HBX', 'Ciento de cajas', 'Unidad de conteo que define el número de cajas en múltiplos de cien unidades de caja.', NULL),
('HC', 'Conteo en cientos', 'Unidad de cuenta que define el número de unidades contadas en múltiplos de 100.', NULL),
('HD', 'Media docena', NULL, NULL),
('HDW', 'Cien kilogramos, peso seco', 'Unidad de masa que define el número de cien kilogramos de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('HE', 'Centésima de un quilate', NULL, NULL),
('HEA', 'Cabeza', 'Unidad de conteo que define el número de cabezas (cabeza: persona o animal considerada como un número.', NULL),
('HF', 'Cien pies', NULL, NULL),
('HGM', 'Héctogramo', NULL, 'hg'),
('HH', 'Cien pies cúbicos', 'Unidad de volumen igual a cien pies cúbicos.', NULL),
('HI', 'Cien hojas', NULL, NULL),
('HIU', 'Unidad internacional de cien', 'Unidad de cuenta que define el número de unidades internacionales en múltiplos de 100.', NULL),
('HJ', 'Potencia métrica', NULL, 'Hp métrico'),
('HK', 'Cien kilogramos', NULL, NULL),
('HKM', 'Cien kilogramos, masa neta', 'Unidad de masa que define el número de cientos de kilogramos de un producto, después de las deducciones.', NULL),
('HL', 'Cien pies (lineal)', NULL, NULL),
('HLT', 'Hectolitro', 'Es una unidad de volumen equivalente a cien litros, representado por el símbolo hl. Es el segundo múltiplo del litro y también equivale a 100 decímetros cúbicos (0,1 metros cúbicos).', 'hl')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();