INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('MPA', 'Megapascal', NULL, 'MPa'),
('MQ', 'Mil metros', NULL, NULL),
('MQH', 'Metro cúbico por hora', NULL, 'm³/h'),
('MQS', 'Metro cúbico por segundo', NULL, 'm³/s'),
('MSK', 'Metro por segundo cuadrado', 'Es la aceleración de un cuerpo, animado de movimiento uniformemente variado, cuya velocidad varía cada segundo, 1 m/s.', 'm/s²'),
('MTK', 'Metro cuadrado', 'Es la unidad básica de superficie en el Sistema Internacional de Unidades. Si a esta unidad se antepone un prefijo del Sistema Internacional se crea un múltiplo o submúltiplo de esta.', 'm²'),
('MTQ', 'Metro cúbico', 'Sinónimo: metro cúbico', 'm³'),
('MTR', 'Metro', 'El metro (símbolo m) es la principal unidad de longitud del Sistema Internacional de Unidades. Un metro es la distancia que recorre la luz en el vacío en un intervalo de 1/299 792 458 de segundo.', 'm'),
('MTS', 'Metro por segundo', 'Es la velocidad de un cuerpo que, con movimiento uniforme, recorre, una longitud de un metro en 1 segundo .', 'm/s'),
('MV', 'Número de mults', NULL, NULL),
('MVA', 'Megavoltio - amperio', NULL, 'MV·A'),
('MWH', 'Megawatt hora', 'Unidad de potencia que define la cantidad total de energía a granel transferida o consumida.', 'MW·h'),
('N1', 'Pluma calórica', 'Unidad de conteo que define el número de calorías que se recetan diariamente para la terapia parenteral / enteral.', NULL),
('N10', 'Libra pie por segundo', 'Producto de la libra avoirdupois de acuerdo con el sistema de unidades avoirdupois y el pie de acuerdo con el sistema de unidades Anglo-Americano y el sistema imperial, dividido por la unidad segundo del sistema interacional.', 'lb·(ft/s)'),
('N11', 'Libra pulgada por segundo', 'Producto de la libra avoirdupois de acuerdo con el sistema de unidades avoirdupois y la pulgada de acuerdo con el sistema de unidades Anglo-Americano y el sistema imperial, dividido por la unidad segundo del sistema interacional.', 'lb·(in/s)'),
('N12', 'Pferdestaerke', 'Unidad obsoleta de la potencia relativa a DIN 1301-3: 1979: 1 PS = 735.498 75 W.', 'PS'),
('N13', 'Centímetro de mercurio (0°)', 'Unidad de presión no conforme al sistema internacional, en la cuál el valor de 1 cmHg cumple con la presión estática, que es generada por un mercurio a una temperatura de 0 ° C con una altura de 1 centímetro.', 'cmHg (0 ºC)'),
('N14', 'Centímetro de agua (4°)', 'Unidad de presión no conforme al sistema internacional, en la cuál el valor de 1 cmH2O cumple con la presión estática, que es generada por una cabeza de agua a una temperatura de 4 ° C con una altura de 1 centímetro.', 'cmH₂O (4 °C)'),
('N15', 'Pie de agua (39.2 °f)', 'Unidad de presión no conforme al sistema internacional, de acuerdo con el sistema Anglo-Americano e Imperial para unidades, mientras que el valor de 1 ft H2O es equivalente a la presión estática, que es generada por una cabeza de agua a una temperatura de 39,2 ° F con una Altura de 1 pie.', 'ftH₂O (39,2 ºF)'),
('N16', 'Pulgada de mercurio (32 °f)', 'Unidad de presión no conforme al sistema internacional, de acuerdo con el sistema Anglo-American e Imperial para unidades, mientras que el valor de 1 inHg cumple con la presión estática, que es generada por un mercurio a una temperatura de 32 ° F con una altura de 1 pulgada.', 'inHG (32 ºF)'),
('N17', 'Pulgada de mercurio (60 °f)', 'Unidad de presión no conforme al sistema internacional sino según al sistema Anglo-Americano e Imperial para unidades, mientras que el valor de 1 in Hg satisface la presión estática, que es generada por un mercurio a una temperatura de 60 ° F con una altura de 1 pulgada.', 'inHg (60 ºF)'),
('N18', 'Pulgada de agua (39.2 °f)', 'Unidad de presión no conforme al sistema internacional sino de acuerdo con el sistema Anglo-Americano e Imperial para unidades, mientras que el valor de 1 inH2O satisface la presión estática, que es generada por una cabeza de agua a una temperatura de 39,2 ° F con una altura De 1 pulgada.', 'inH₂O (39,2 ºF)'),
('N19', 'Pulgada de agua (60 °f)', 'Unidad de presión no conforme al sistema internacional sino según al sistema Anglo-Americano e Imperial para unidades, mientras que el valor de 1 inH2O satisface la presión estática, que es generada por una cabeza de agua a una temperatura de 60 ° F con una altura de 1 pulgada.', 'inH₂O (60 ºF)'),
('N2', 'número de líneas', NULL, NULL),
('N20', 'Kip por pulgada cuadrada', 'Unidad de presión no conforme al sistema internacional de unidades sino de acuerdo con el sistema Anglo-Americano de unidades como el 1000 veces de la unidad de fuerza de libra fuerza dividida por la potencia de la unidad de pulgada por el exponente 2.', 'ksi'),
('N21', 'Poundal por pie cuadrado', 'Unidad de presión no conforme al sistema internacional según el sistema Imperial de unidades según NIST: 1 pdl / ft² = 1,488 164 Pa.', 'pdl/ft²'),
('N22', 'Onza (avoirdupois) por pulgada cuadrada', 'Unidad de la masa específica de la superficie (onza de avoirdupois según el sistema del avoirdupois de unidades según la superficie pulgada cuadrada según el sistema Anglo-Americano e imperial de unidades).', 'oz/in²'),
('N23', 'Metro convencional de agua', 'No es una unidad de presión del sistema internacional, mientras que un valor de 1 mH2O es equivalente a la presión estática, que es producida por una columna de agua de un metro de alto.', 'mH₂O'),
('N24', 'Gramo por milímetro cuadrado', '0.001 veces el kilo de unidad de basedel sistema internacional dividido por el 0,000 001 veces de la potencia del medidor de unidad de base del sistema internacional por el exponente 2.', 'g/mm²'),
('N25', 'Libra por yarda cuadrada', 'Unidad para la masa relacionada con el área como una unidad de la libra según el sistema de la unidad del avoirdupois dividido por la potencia del patio de la unidad según el sistema Anglo-Americano e imperial de unidades con el exponente 2.', 'lb/yd²'),
('N26', 'Poundal por pulgada cuadrada', 'Unidad de presión no conforme al sistema internacional sino según el sistema Imperial de unidades (poundal por pulgada cuadrada).', 'pdl/in²'),
('N27', 'Pie a la cuarta potencia', 'Potencia de la unidad pie, de acuerdo con el sistema Anglo-Americano e Imperial de unidades, elevado al exponente 4 de acuerdo con NIST: 1 ft4 = 8,630 975 m4.', 'ft⁴'),
('N28', 'Decímetro cúbico por kilogramo', '0.001 veces de metro, unidad base  del sistema internacional elevado al exponente 3 dividido por el kilogramo.', 'dm³/kg'),
('N29', 'Pie cúbico por libra', 'Potencia del pie, unidad de acuerdo con el sistema de unidades Anglo-Americanas e Imperial elevado al exponente 3 dividido por la libra de la unidad avoirdupois según el sistema unitario avoirdupois.', 'ft³/lb'),
('N3', 'Impresión de punto', NULL, NULL),
('N30', 'Pulgada cúbica por libra', 'Potencia de la unidad pulgada según el sistema Anglo-Americano e Imperial de unidades elevado al exponente 3 dividido por la libra avoirdupois según el sistema unitario avoirdupois.', 'in³/lb'),
('N31', 'Kilonewton por metro', '1000 veces de la unidad derivada newton dividido por el metro, ambas unidades del sistema internacional.', 'kN/m'),
('N32', 'Poundal por pulgada', 'Unidad de tensión superficial de acuerdo con el sistema de unidad Imperial como cociente de poundal por pulgada.', 'pdl/in'),
('N33', 'Libra-fuerza por yarda', 'Unidad de fuerza por unidad de longitud basado en el sistema Anglo-Americano de unidades.', 'lbf/yd'),
('N34', 'Poundal segundo por pie cuadrado', 'Unidad de viscosidad no conforme al sistema internacional.', '(pdl/ft²)·s'),
('N35', 'Poise por pascal', 'CGS (Centímetro-Gramo-Segundo sistema) unidad poise dividido por la unidad derivada del sistema internacional, pascal.', 'P/Pa'),
('N36', 'Newton segundo por metro cuadrado', 'Unidad de la viscosidad dinámica como un producto de la unidad de la presión (newton por metro cuadrado) multiplicado con la unidad de base SI segundo.', '(N/m²)·s'),
('N37', 'Kilogramo por metro segundo', 'Unidad de la viscosidad dinámica como un cociente de la unidad kilogramo del sistema internacional entre la unidad metro y por segundo del sistema internacional de unidades.', 'kg/(m·s)'),
('N38', 'Kilogramo por metro minuto', 'Unidad de la viscosidad dinámica como un cociente de la unidad kilogramo del sistema internacional entre la unidad metro y por minuto del sistema internacional de unidades.', 'kg/(m·min)'),
('N39', 'Kilogramo por metro día', 'Unidad de la viscosidad dinámica como un cociente de unidad base kilogramo dividido por la unidad base metro y por la unidad de día, ambas del sistema internacional.', 'kg/(m·d)'),
('N40', 'Kilogramo por metro hora', 'Unidad de la viscosidad dinámica como cociente de la unidad base kilogramo dividido por la unidad base metro y por unidad de hora, ambas del sistema internacional.', 'kg/(m·h)'),
('N41', 'Gramo por centímetro segundo', 'Unidad de la viscosidad dinámica como un cociente del 0,001 veces de la unidad base kilogramo dividido por el 0,01 veces de la unidad base metro y la unidad base segundo, del sistema internacional de unidades.', 'g/(cm·s)'),
('N42', 'Poundal segundo por pulgada cuadrada', 'Unidad de viscosidad dinámica no conforme al sistema internacional sino según el sistema Imperial de unidades, como producto de la  unidad de presión (poundal por pulgada cuadrada) multiplicada por la unidad base segundo, del sistema internacional de unidades.', '(pdl/in²)·s'),
('N43', 'Libra por pie minuto', 'Unidad de la viscosidad dinámica según el sistema Anglo-Americano de unidades.', 'lb/(ft·min)'),
('N44', 'Libra por pie día', 'Unidad de la viscosidad dinámica según el sistema Anglo-Americano de unidades.', 'lb/(ft·d)'),
('N45', 'Metro cúbico por segundo pascal', 'Potencia de la unidad metro del sistema internacional por el exponente 3 dividido por el producto de la unidad base segundo y la unidad derivada pascal, ambas del sistema internacional de unidades.', '(m³/s)/Pa'),
('N46', 'Pie poundal', 'Unidad de trabajo (trayectoria de fuerza)', 'ft·pdl'),
('N47', 'Pulgada poundal', 'Unidad de trabajo (fuerza multiplicado por trayectoria) de acuerdo con el sistema imperial de unidades como el producto de la unidad pulgada multiplicada por el poundal.', 'in·pdl'),
('N48', 'Watt por centímetro cuadrado', 'Unidad derivada del sistema internacional, watt, dividido por la potencia de la 0.01 parte de la unidad base del sistema internacional, metro al exponente 2.', 'W/cm²'),
('N49', 'Watt por pulgada cuadrada', 'Unidad derivada del sistema internacional, watt, dividido por la potencia de la unidad pulgada al exponente 2, de acuerdo al sistema de unidades Anglo-Americano y el sistema imperial de unidades.', 'W/in²'),
('N50', 'Unidad térmica británica (tabla internacional) por pie cuadrado hora.', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'BtuIT/(ft²·h)'),
('N51', 'Unidad térmica británica (termoquímica) por pie cuadrado hora.', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'Btuth/(ft²·h)'),
('N52', 'Unidad térmica británica (termoquímico) por pie cuadrado minuto.', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'Btuth/(ft²·min)'),
('N53', 'Unidad térmica británica (tabla internacional) por pie cuadrado segundo.', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'BtuIT/(ft²·s)'),
('N54', 'Unidad térmica británica (termoquímica) por pie cuadrado segundo.', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'Btuth/(ft²·s)'),
('N55', 'Unidad térmica británica (tabla internacional) por pulgada cuadrada segundo.', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'BtuIT/(in²·s)'),
('N56', 'Caloría (termoquímica) por centímetro cuadrado minuto', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'calth/(cm²·min)'),
('N57', 'Caloría (termoquímica) por centímetro cuadrado segundo', 'Unidad del flujo superficial de calor según el sistema Imperial de unidades.', 'calth/(cm²·s)'),
('N58', 'Unidad térmica británica (tabla internacional) por pie cúbico', 'Unidad de la densidad de energía según el sistema Imperial de unidades.', 'BtuIT/ft³'),
('N59', 'Unidad térmica británica (termoquímica) por pie cúbico', 'Unidad de la densidad de energía según el sistema Imperial de unidades.', 'Btuth/ft³'),
('N60', 'Unidad térmica británica (tabla internacional) por grado fahrenheit', 'Unidad de la capacidad calorífica según el sistema Imperial de unidades.', 'BtuIT/ºF'),
('N61', 'Unidad térmica británica (termoquímico) por grado fahrenheit', 'Unidad de la capacidad calorífica según el sistema Imperial de unidades.', 'Btuth/ºF'),
('N62', 'Unidad térmica británica (tabla internacional) por grado rankine', 'Unidad de la capacidad calorífica según el sistema Imperial de unidades.', 'BtuIT/ºR'),
('N63', 'Unidad térmica británica (termoquímico) por grado rankine', 'Unidad de la capacidad calorífica según el sistema Imperial de unidades.', 'Btuth/ºR'),
('N64', 'Unidad térmica británica (termoquímico) por libra grado rankine', 'Unidad de la capacidad calorífica (unidad térmica británica según la tabla internacional según el grado de Rankine) de acuerdo con el sistema Imperial de unidades dividido por la unidad avoirdupois libra según el sistema de avoirdupois de unidades.', '(Btuth/°R)/lb'),
('N65', 'Kilocaloría (tabla internacional) por gramo kelvin', 'Unidad de la capacidad calorífica relacionada con la masa como cociente 1000 veces de la caloría (tabla internacional) dividido por el producto de 0,001 veces de las unidades de base kilogramo y kelvin.', '(kcalIT/K)/g'),
('N66', 'Unidad térmica británica (39 °f)', 'Unidad de energía térmica según el sistema Imperial de unidades en una temperatura de referencia de 39 ° F.', 'Btu (39 ºF)'),
('N67', 'Unidad térmica británica (59 °f)', 'Unidad de energía térmica según el sistema Imperial de unidades en una temperatura de referencia de 59 ° F.', 'Btu (59 ºF)'),
('N68', 'Unidad térmica británica (60 °f)', 'Unidad de energía térmica según el sistema Imperial de unidades en una temperatura de referencia de 60 ° F.', 'Btu (60 ºF)'),
('N69', 'Caloría (20 °c)', 'Unidad para la cantidad de calor, que se requiere para que 1g de agua libre de aire a una presión constante de 101.325 kPa, se caliente a la presión de la atmósfera estándar a nivel del mar, de 19,5 ° C a 20,5 ° C.', 'cal₂₀'),
('N70', 'Quad', 'Unidad de energía de acuerdo al sistema imperial de unidades', 'quad'),
('N71', 'Termia (energía comercial)', 'Unidad de energía calorífica en uso comercial, dentro de Estados Unidos definida como: 1 thm (EC) = 100 000 BtuIT.', 'thm (EC)'),
('N72', 'Termia (UEA)', 'Unidad de energía térmica en uso comercial.', 'thm (US)'),
('N73', 'Unidad térmica británica (termoquímica) por libra', 'Unidad de la energía calorífica según el sistema imperial de unidades dividió por la unidad de la libra de avoirdupois según el sistema de avoirdupois de unidades.', 'Btuth/lb'),
('N74', 'Unidad térmica británica (tabla internacional) por hora pie cuadrado grado fahrenheit.', 'Unidad del coeficiente de transición térmica según el sistema Imperial de unidades.', 'BtuIT/(h·ft²·ºF)'),
('N75', 'Unidad térmica británica (termoquímico) por hora pie cuadrado grado farenheit.', 'Unidad del coeficiente de transición térmica según el sistema imperial de unidades.', 'Btuth/(h·ft²·ºF)'),
('N76', 'Unidad térmica británica (tabla internacional) por segundo pie cuadrado grado fahrenheit.', 'Unidad del coeficiente de transición térmica según el sistema imperial de unidades.', 'BtuIT/(s·ft²·ºF)'),
('N77', 'Unidad térmica británica (termoquímico) por segundo pie cuadrado grado fahrenheit.', 'Unidad del coeficiente de transición térmica según el sistema imperial de unidades.', 'Btuth/(s·ft²·ºF)'),
('N78', 'Kilowatt por metro cuadrado kelvin', '1000 veces la unidad derivada watt, dividida por el producto de la potencia de unidad base, metro, por el exponente 2 y la unidad base, kelvin, del sistema internacional de unidades.', 'kW/(m²·K)'),
('N79', 'Kelvin por pascal', 'Unidad base del sistema internacional kelvin, dividido entre pascal, unidad base del sistema internacional', 'K/Pa'),
('N80', 'Watt por metro grado celsius', 'Unidad derivada del sistema internacional, watt, dividido por el producto de la unidad base, metro, y la unidad de temperatura grados Celsius.', 'W/(m·°C)'),
('N81', 'Kilowatt por metro kelvin', '1000 veces de la unidad derivada, watt, dividido por el producto de la unidad de base metro y la unidad base kelvin, ambas del sistema internacional.', 'kW/(m·K)'),
('N82', 'Kilowatt por metro grado celsius', '1000 veces de la unidad derivada, watt, dividido por el producto de la unidad base metro y la unidad de temperatura grados Celsius.', 'kW/(m·°C)'),
('N83', 'Metro por grado celsius metro', NULL, 'm/(°C·m)'),
('N84', 'Grado fahrenheit hora por unidad térmica británica (tabla internacional)', 'Unidad no conforme al sistema internacional de unidades,de la resistencia térmica según el sistema Imperial de unidades.', 'ºF/(BtuIT/h)'),
('N85', 'Grado fahrenheit hora por unidad térmica británica (termoquímico)', 'Unidad no conforme al sistema internacional de unidades,de la resistencia térmica según el sistema Imperial de unidades.', 'ºF/(Btuth/h)'),
('N86', 'Grado fahrenheit segundo por unidad térmica británica (tabla internacional)', 'Unidad no conforme al sistema internacional de unidades,de la resistencia térmica según el sistema Imperial de unidades.', 'ºF/(BtuIT/s)'),
('N87', 'Grago fahrenheit segundo por unidad térmica británica (termoquímico)', 'Unidad no conforme al sistema internacional de unidades,de la resistencia térmica según el sistema Imperial de unidades.', 'ºF/(Btuth/s)'),
('N88', 'Grado fahrenheit hora pie cuadrado por unidad térmica británica (tabla internacional) pulgada', 'Unidad de resistencia térmica específica según el sistema Imperial de unidades', 'ºF·h·ft²/(BtuIT·in)'),
('N89', 'Grado fahrenheit hora pie cuadrado por unidad térmica británica (termoquímico) pulgada.', 'Unidad de resistencia térmica específica según el sistema Imperial de unidades', 'ºF·h·ft²/(Btuth·in)'),
('N90', 'Kilofaradio', '1000 veces del faradio, unidad derivada del sistema internacional', 'kF'),
('N91', 'Joule recíproco', NULL, '1/J'),
('N92', 'Picosiemens', '0.000 000 000 001 veces de la unidad derivada  siemens del sistema internacional de unidades.', 'pS'),
('N93', 'Amperio por pascal', 'Unidad base amperio dividido por la unidad derivada pascal.', 'A/Pa'),
('N94', 'Franklin', 'CGS (Centímetro-Gram-Segundo sistema) unidad de la carga eléctrica, donde la carga asciende exactamente a 1 franklin donde la fuerza de 1 dina sobre una carga igual se realiza a una distancia de 1 cm.', 'Fr')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();