INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('C26', 'Milisegundo', NULL, 'ms'),
('C27', 'Milisiemens', NULL, 'mS'),
('C28', 'MilliSievert', NULL, 'mSv'),
('C29', 'Militesla', NULL, 'mT'),
('C3', 'Microvoltios por metro', NULL, 'µV/m'),
('C30', 'Milivoltio por metro', NULL, 'mV/m'),
('C31', 'Miliwatt', NULL, 'mW'),
('C32', 'Miliwatt por metro cuadrado', 'Es equivalente a una milésima de vatio.', 'mW/m²'),
('C33', 'Miliweber', NULL, 'mWb'),
('C34', 'Mol', 'Es la cantidad de sustancia de un sistema que contiene tantas entidades elementales como átomos hay en 0,012 kilogramos de carbono 12.', 'mol'),
('C35', 'Mol por decimetro cúbico', NULL, 'mol/dm³'),
('C36', 'Mol por metro cúbico', NULL, 'mol/m³'),
('C37', 'Kilobits', 'Unidad de información igual a 10³(1000) bits (dígitos binarios).', 'kbit'),
('C38', 'Mol por litro', NULL, 'mol/l'),
('C39', 'Nanoamperio', NULL, 'nA'),
('C4', 'partido de carga', NULL, NULL),
('C40', 'NanoCulombio', NULL, 'nC'),
('C41', 'Nanofaradio', NULL, 'nF'),
('C42', 'Nanofaradio por metro', NULL, 'nF/m'),
('C43', 'Nanohenry', NULL, 'nH'),
('C44', 'Nanohenry por metro', NULL, 'nH/m'),
('C45', 'Nanómetro', 'Medida de longitud que equivale a la milmillonésima parte del metro.', 'nm'),
('C46', 'NanoOhm metro', NULL, 'nΩ·m'),
('C47', 'Nanosegundo', NULL, 'ns'),
('C48', 'Nanotesla', NULL, 'nT'),
('C49', 'Nanowatt', NULL, 'nW'),
('C5', 'Costo', NULL, NULL),
('C50', 'Neperio', 'El neper o neperio es una unidad de medida relativa que se utiliza frecuentemente en el campo de la telecomunicación, para expresar relaciones entre voltajes o intensidades.', 'Np'),
('C51', 'Neperio por segundo', NULL, 'Np/s'),
('C52', 'Picómetro', 'Es una unidad de longitud del SI que equivale a una billonésima (0,000 000 000 001 o 1×10-12) parte de un metro.', 'pm'),
('C53', 'Newton metro segundo', NULL, 'N·m·s'),
('C54', 'Newton metro cuadrado por kilogramo cuadrado', NULL, 'N·m²/kg²'),
('C55', 'Newton por metro cuadrado', NULL, 'N/m²'),
('C56', 'Newton por milimetro cuadrado', NULL, 'N/mm²'),
('C57', 'Newton segundo', NULL, 'N·s'),
('C58', 'Segundos newton por metro', NULL, 'N·s/m'),
('C59', 'Octava', 'Una unidad utilizada en la música para describir la relación de la frecuencia entre las notas.', NULL),
('C6', 'celda', NULL, NULL),
('C60', 'Ohm centímetro', NULL, 'Ω·cm'),
('C61', 'Ohm metro', NULL, 'Ω·m'),
('C62', 'Uno', 'Sinónimo: unidad', '1'),
('C63', 'Pársec', 'Es una unidad de medida astronómica bastante utilizada para calcular grandes distancias entre objetos.', 'pc'),
('C64', 'Pascal por kelvin', NULL, 'Pa/K'),
('C65', 'Pascal segundo', 'Es la viscosidad dinámica de un fluido homogéneo, en el cual, el movimiento rectilíneo y uniforme de una superficie plana de 1 metro cuadrado, da lugar a una fuerza retardatriz de 1 newton, cuando hay una diferencia de velocidad de 1 metro por segundo entre dos planos paralelos separados por 1 metro de distancia.', 'Pa·s'),
('C66', 'Segundos pascal por metro cúbico', NULL, 'Pa·s/m³'),
('C67', 'Segundos pascal por metro', NULL, 'Pa· s/m'),
('C68', 'Petajoule', NULL, 'PJ'),
('C69', 'Phon', 'Unidad de volumen del sonido subjetivo. Un sonido tiene p phons de sonoridad si se parece al oyente a ser iguales en intensidad, con el sonido de un tono puro de frecuencia 1 kilohertz y de la fuerza p decibelios.', NULL),
('C7', 'Centipoise', NULL, 'cP'),
('C70', 'Picoamperio', NULL, 'pA'),
('C71', 'PicoCulombio', NULL, 'pC'),
('C72', 'Picofaradio por metro', NULL, 'pF/m'),
('C73', 'Picohenry', NULL, 'pH'),
('C74', 'Kilobits por segundo', 'Unidad de información igual a 10 ³  (1000) bits (dígitos binarios) por segundo.', 'kbit/s'),
('C75', 'Picowatt', NULL, 'pW'),
('C76', 'Picowatt  por metro cuadrado', 'Es igual a la trillonésima parte de un vatio (10−12).', 'pW/m²'),
('C77', 'Calibre de libra', NULL, NULL),
('C78', 'Libra fuerza', NULL, 'lbf'),
('C79', 'Kilovoltios horas amperios', 'Unidad de energía acumulada de 1000 amperios voltioios durante un período de una hora.', 'kVAh'),
('C8', 'MilliCulombio por kilogramo', NULL, 'mC/kg'),
('C80', 'Rad', NULL, 'rad'),
('C81', 'Radián', 'Es la unidad de medida de un ángulo con vértice en el centro de un círculo cuyos lados son cortados por el arco de la circunferencia, y que además dicho arco tiene una longitud igual a la del radio.', 'rad'),
('C82', 'Radianmetro cuadrado por Mol', NULL, 'rad·m²/mol'),
('C83', 'Rradian metro cuadrado por kilogramo', NULL, 'rad·m²/kg'),
('C84', 'Radían por metro', NULL, 'rad/m'),
('C85', 'Reciprocidad Ámstrong', NULL, 'Å⁻¹'),
('C86', 'Reciprocidad del metro cúbico', NULL, 'm⁻³'),
('C87', 'Reciprocidad metro cúbico por segundo', 'Sinonimo: Reciprocidad del segundo por metro cúbico.', 'm⁻³/s'),
('C88', 'Recíproco joule por metro cúbico', NULL, 'eV⁻¹/m³'),
('C89', 'Henry recíproco', NULL, 'H⁻¹'),
('C9', 'Grupo bobinas', 'Unidad de conteo que define el número de grupos de bobinas (grupo bobina: grupos de elementos dispuestos por longitudes de los objetos colocados en una secuencia de círculos concéntricos unido).', NULL),
('C90', 'Recíproco Henry', NULL, 'J⁻¹/m³'),
('C91', 'Recíprocidad de kelvin ó kelvin a la potencia menos 1', NULL, 'K⁻¹'),
('C92', 'Reciprocidad Metro', NULL, 'm⁻¹'),
('C93', 'Reciprocidad Metro cuadrado', 'Sinónimo: Reciprocidad de metro cuadrado', 'm⁻²'),
('C94', 'Reciprocidad Minuto', NULL, 'min⁻¹'),
('C95', 'Reciprocidad Mol', 'Es una propiedad física definida como su masa por unidad de cantidad de sustancia.', 'mol⁻¹'),
('C96', 'Reciprocidad Pascal o pascal a la potencia menos 1', NULL, 'Pa⁻¹'),
('C97', 'Reciprocidad Segundo', NULL, 's⁻¹'),
('C98', 'Segundo recíproco por metro cúbico', NULL, 'S $ ^ {1} $ / m $ ³ $'),
('C99', 'Reciprocidad Segundo por metro cuadrado', NULL, 's⁻¹/m²'),
('CCT', 'Capacidad de carga en toneladas métricas', 'Unidad de masa que define la capacidad de carga, expresada como el número de toneladas métricas.', NULL),
('CDL', 'Candela', 'La candela es una de las unidades básicas del Sistema Internacional, de intensidad luminosa.', 'cd'),
('CE', 'Cada mes', NULL, NULL),
('CEL', 'Grados celsius', 'Consulte ISO 80000-5 (Cantidades y unidades - Parte 5: Termodinámica)', '°C'),
('CEN', 'Centenar', 'Una unidad de recuento de definir el número de unidades en múltiplos de 100.', NULL),
('CG', 'Tarjeta', 'Unidad de conteo que define el número de unidades de la tarjeta (tarjeta: papel rígido grueso o cartón).', NULL),
('CGM', 'Centígramo', NULL, 'cg'),
('CK', 'Conector', NULL, NULL),
('CKG', 'Culombio por kilogramo', NULL, 'C/kg'),
('CLF', 'Cientos de hojas', 'Una unidad de recuento de definir el número de hojas, expresado en unidades de cien hojas.', NULL),
('CLT', 'Centilitro', 'Medida de volumen, de símbolo cl, que es igual a la centésima parte de un litro.', 'cl'),
('CMK', 'Centímetro cuadrado', 'Medida de longitud, de símbolo cm, que es igual a la centésima parte de un metro.', 'cm²'),
('CMQ', 'Centímetro cúbico', 'Medida de longitud, de símbolo cm, que es igual a la centésima parte de un metro.', 'cm³'),
('CMT', 'Centímetro', 'Es una unidad de longitud. Es el segundo submúltiplo del metro y equivale a la centésima parte de él.', 'cm'),
('CNP', 'Cientos de paquetes', 'Unidad de recuento para definir el número de cientos de paquetes (cien paquete: conjunto de un centenar de artículos empaquetados juntos).', NULL),
('CNT', 'Cental (UK)', 'Una unidad de masa igual a cien  kilos (EUA).', NULL),
('COU', 'Culombio', 'Es la cantidad de electricidad transportada en 1 segundo por una corriente de intensidad 1 amperio.', 'C'),
('CTG', 'Contenido en gramos', 'Unidad de masa que define el número de gramos de un elemento con nombre en un producto.', NULL),
('CTM', 'Quilatage métrico', 'Es una unidad de masa igual a 200  mg y se utiliza para la medición de las piedras preciosas y perlas .', NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();