INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('TW', 'Mil hojas', NULL, NULL),
('U1', 'Tratamiento', 'Unidad de conteo que define el número de tratamientos (tratamiento: sujección a la acción de un agente químico, físico o biológico)', NULL),
('U2', 'Número de tabletas', 'Unidad de conteo que define el número de tabletas', NULL),
('UA', 'Torr', NULL, 'Torr'),
('UB', 'Linea de telecomunicaciones en servicio promedio', 'Unida de conteo que define el número medio de líneas de servicio', NULL),
('UC', 'Puerto de telecomunicaciones', 'Uindad de conteo que define el número de púertos de acceso a la red', NULL),
('UD', 'Décimo minuto', NULL, NULL),
('UE', 'Hora de décimo', NULL, NULL),
('UF', 'Uso por línea de telecomunicaciones promedio', NULL, NULL),
('UH', 'Diez mil yardas', NULL, NULL),
('UM', 'Millón de unidades', NULL, NULL),
('UN', 'Newton metro', NULL, 'N·m'),
('VA', 'Voltio-amperio por kilogramo', NULL, 'V·A / kg'),
('VLT', 'Voltio', 'Es la unidad derivada del Sistema Internacional para el potencial eléctrico, la fuerza electromotriz y la tensión eléctrica.', 'V'),
('VP', 'Volumen porcentual', 'Unidad de medida de concentración, expresada tipícamente como el porcentaje de volumen de un soluto en una solución', NULL),
('VS', 'Visita', NULL, NULL),
('W2', 'Kilo húmedo', 'Unidad de masa que define el número de kilogramos de un producto, incluido el contenido de agua del producto.', NULL),
('W4', 'Dos semanas', NULL, NULL),
('WA', 'Watt por kilogramo', 'Unidad de potencia', 'W/kg'),
('WB', 'Libra húmeda', 'Unidad de masa que define el número de libras de un material, incluyendo el contenido de agua del material', NULL),
('WCD', 'Cable', 'Unidad de volumen utilizada para medir la madera. Un pie de tabla equivale a 1/2 de un pie cúbico.', NULL),
('WE', 'Tonelada húmeda', 'Unidad de masa que define el número de toneladas de un material, incluyendo el contenido de agua del material.', NULL),
('WEB', 'Weber', 'Es el flujo magnético que, al atravesar un circuito de una sola espira produce en la misma una fuerza electromotriz de 1 volt si se anula dicho flujo en un segundo por decaimiento uniforme.', 'Wb'),
('WEE', 'Semana', 'Es el período de tiempo estándar utilizado para los ciclos de días de trabajo y de descanso en la mayoría de las partes del mundo.', 'wk'),
('WG', 'Galón de vino', 'Unidad de volumen igual a 231 pulgadas cúbicas', NULL),
('WH', 'Rueda', NULL, NULL),
('WHR', 'Watt hora', NULL, 'W·h'),
('WI', 'Peso por pulgada cuadrada', NULL, NULL),
('WM', 'Mes de trabajo', 'Unidad de tiempo que define el número de meses de trabajo.', NULL),
('WR', 'Envolver', NULL, NULL),
('WSD', 'Estándar', 'Unidad de volumen de madera acabada igual a 165 pies cúbicos.', 'std'),
('WTT', 'Watt', 'Es la potencia que da lugar a una producción de energía igual a 1 joule por segundo.', 'W'),
('WW', 'Mililitro de agua', 'Unidad de volumen igual al número de mililitros de agua.', NULL),
('X1', 'Cadena de gunter', 'Empleada para medir distancias, formada por 100 eslabones metálicos, equivalentes a una longitud total de 20.1168 metros (66 pies) que aún es ampliamente usada en los países anglosajones.', 'ch (UK)'),
('X1A', 'Tambor de acero', NULL, NULL),
('X1B', 'Tambor de aluminio', NULL, NULL),
('X1D', 'Tambor contrachapado', NULL, NULL),
('X1F', 'Contenedor flexible', 'Contenedor de empaque de construcción flexible.', NULL),
('X1G', 'Tambor de fibra', NULL, NULL),
('X1w', 'Tambor de madera', NULL, NULL),
('X2C', 'Barril de madera', NULL, NULL),
('X3A', 'Bidón de acero', NULL, NULL),
('X3H', 'Bidón de plástico', NULL, NULL),
('X43', 'Bolsa de gran tamaño', 'Bolsa de tela de plástico o de papel que tiene las dimensiones del pallet sobre el que está construido.', NULL),
('X44', 'Bolsa de plastico', 'Un tipo de bolsa de plástico, normalmente utilizada para envolver piezas promocionales, publicaciones, muestras de productos y / o catálogos.', NULL),
('X4A', 'Caja de acero', NULL, NULL),
('X4B', 'Caja de aluminio', NULL, NULL),
('X4C', 'Caja de  madera natural', NULL, NULL),
('X4D', 'Caja de contrachapado', NULL, NULL),
('X4F', 'Caja de madera reconstituida', NULL, NULL),
('X4G', 'Caja de cartón', NULL, NULL),
('X4H', 'Caja de plástico', NULL, NULL),
('X5H', 'Bolsa de plástico tejido', NULL, NULL),
('X5L', 'Bolsa textil', NULL, NULL),
('X5M', 'Bolsa de papel', NULL, NULL),
('X6H', 'Recipiente de plástico, Contenedor compuesto.', NULL, NULL),
('X6P', 'Recipiente de vidrio, Contenedor compuesto.', NULL, NULL),
('X7A', 'Estuche para carro', 'Tipo de contenedor portátil diseñado para almacenar equipo para el transporte en un automóvil.', NULL),
('X7B', 'Estuche de madera', 'Un estuche de madera para retener sustancias o artículos.', NULL),
('X8A', 'Pallet de madera', 'Plataforma o caja abierta de madera, en la que se conservan las mercancías para facilitar su manejo mecánico durante el transporte y almacenamiento.', NULL),
('X8B', 'Cajón de madera', 'Un contenedor de madera, en el que se conservan las mercancías para facilitar su manipulación mecánica durante el transporte y almacenamiento.', NULL),
('X8C', 'Madera flejada', 'Piezas sueltas o sin contenedor de madera atadas o envueltas.', NULL),
('XAA', 'Contenedor intermedio  para gráneles de plástico rígido', NULL, NULL),
('XAB', 'Contenedor de fibra', 'Recipiente de contención de fibra, utilizado para retener sustancias o artículos.', NULL),
('XAC', 'Contenedor de papel', 'Recipiente de contención de papel, para retener sustancias o artículos.', NULL),
('XAD', 'Contenedor de madera', 'Recipiente de contención de madera, para retener sustancias o artículos.', NULL),
('XAE', 'Aerosol', 'Una unidad de cuenta que define el número de Aerosoles', NULL),
('XAF', 'Pallet modular con collares,  80cms * 60cms', 'Pallet de tamaño estándar con dimensiones de 80 centímetros por 60 centímetros (cms).', NULL),
('XAG', 'Pallet o empaquetado', 'La carga del pallet se asegura con una película de plástico transparente envuelta alrededor y luego encogido firmemente.', NULL),
('XAH', 'Pallet, 100cms X 110cms', 'Pallet tamaño estándar con dimensiones de 100 centímetros por 110 centímetros (cms).', NULL),
('XAI', 'Contenedor tipo concha', NULL, NULL),
('XAJ', 'Cono', 'Contenedor utilizado en el transporte de material lineal como el hilo.', NULL),
('XAL', 'Esféra', 'Recipiente de contención esférico para retener sustancias o artículos.', NULL),
('XAM', 'Ampolleta no protegida', NULL, NULL),
('XAP', 'Ampolleta protegida', NULL, NULL),
('XAT', 'Atomizador', NULL, NULL),
('XAV', 'Cápsula', NULL, NULL),
('XB4', 'Cinturón', 'Banda utiliza para retener varios artículos juntos.', NULL),
('XBA', 'Barril', NULL, NULL),
('XBB', 'Bobina', NULL, NULL),
('XBC', 'Cajón para botellas / Estante para botellas', NULL, NULL),
('XBD', 'Tablero', NULL, NULL),
('XBE', 'Flejado', NULL, NULL),
('XBF', 'Globo no protegido', NULL, NULL),
('XBG', 'Bolso', 'Recipiente de material flexible con tapa abierta o cerrada.', NULL),
('XBH', 'Manojo', NULL, NULL),
('XBI', 'Compartimiento', NULL, NULL),
('XBJ', 'Cubeta', NULL, NULL),
('XBK', 'Cesta', NULL, NULL),
('XBL', 'Paca comprimida', NULL, NULL),
('XBM', 'Cuenco', NULL, NULL),
('XBN', 'Paca no comprimida', NULL, NULL),
('XBO', 'Botella no-protegida y cilíndrica', 'Recipiente de forma cilíndrica de cuello estrecho sin material de empaque protector externo.', NULL),
('XBP', 'Globo protegido', NULL, NULL),
('XBQ', 'Botella cilíndrica protegida', 'Recipiente de forma cilíndrica de cuello estrecho con material de empaque protector externo.', NULL),
('XBR', 'Barra', NULL, NULL),
('XBS', 'Botella, no-protegida en forma de bulbo', 'Recipiente en forma de bulbo de cuello estrecho sin material de empaque protector externo.', NULL),
('XBT', 'Rollo de tela', NULL, NULL),
('XBU', 'Butt', 'Barril de 1/2 tonel', NULL),
('XBV', 'Botella de bulbo protegido', 'Recipiente en forma de bulbo de cuello estrecho con material de empaque protector externo.', NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();