INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('D98', 'Libra masiva', NULL, NULL),
('D99', 'manga', NULL, NULL),
('DAA', 'Decar', NULL, 'daa'),
('DAD', 'Decena de días', 'Unidad de tiempo que define el número de días en múltiplos de 10.', NULL),
('DAY', 'Día', 'Se denomina día (del latín dies) al lapso que tarda la Tierra desde que el Sol está en el punto más alto sobre el horizonte hasta que vuelve a estarlo.', 'd'),
('DB', 'Libra seca', 'Unidad de masa que define el número de libras de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('DC', 'Disco (disco)', NULL, NULL),
('DD', 'Grado [unidad de ángulo]', 'Es el resultado de dividir el ángulo llano en 180 partes iguales.', '°'),
('DE', 'Acuerdo', NULL, NULL),
('DEC', 'Década', 'Unidad de recuento de definir el número de décadas (década: cantidad igual a 10 o tiempo igual a 10 años).', NULL),
('DG', 'Decigramo', NULL, 'dg'),
('DI', 'dispensador', NULL, NULL),
('DJ', 'Decagramo', NULL, 'dag'),
('DLT', 'Decilitro', NULL, 'dl'),
('DMA', 'Decámetro cúbico', NULL, 'dam³'),
('DMK', 'Decímetro cuadrado', 'Medida de longitud, de símbolo dm, que es igual a la décima parte de un metro.', 'dm²'),
('DMO', 'Kiloliter norma', 'Unidad de volumen que define el número de kilolitros de un producto a una temperatura de 15 grados centígrados, sobre todo en relación con los aceites de hidrocarburos.', NULL),
('DMQ', 'Decímetro cúbico', 'Medida de longitud, de símbolo dm, que es igual a la décima parte de un metro.', 'dm³'),
('DMT', 'Decímetro', 'Es una unidad de longitud. Es el primer submúltiplo del metro y equivale a la décima parte de él.', 'dm'),
('DN', 'Decinewton metro', NULL, 'dN·m'),
('DPC', 'Docenas de piezas', 'Unidad de recuento para definir el número de piezas en múltiplos de 12 (pieza: un solo artículo, el artículo o ejemplar).', NULL),
('DPR', 'Docenas de pares', 'Unidad de recuento de definir el número de pares en múltiplos de 12 (par: ítem descrito por dos de).', NULL),
('DPT', 'Peso de desplazamiento', 'Unidad de masa que define el volumen de agua de mar de un barco desplaza, expresada como el número de toneladas.', NULL),
('DQ', 'registro de datos', NULL, NULL),
('DRA', 'Dram (EUA)', 'Sinónimo: dracma (Reino Unido), dram Troy', NULL),
('DRI', 'Dram (UK)', 'Son las siglas de la voz inglesa Dynamic Random Access Memory, que significa memoria dinámica de acceso aleatorio (o RAM dinámica), para denominar a un tipo de tecnología de memoria RAM basada en condensadores, los cuales pierden su carga progresivamente, necesitando de un circuito dinámico de refresco que, cada cierto período, revisa dicha carga y la repone en un ciclo de refresco.', NULL),
('DRL', 'Docena de rodillos', 'Unidad de recuento de definir el número de rollos, expresado en doce unidades de rodillos.', NULL),
('DRM', 'Drachm (UK)', NULL, NULL),
('DS', 'monitor', NULL, NULL),
('DT', 'Tonelada seca', 'Unidad de masa que define el número de toneladas de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('DTN', 'Decitonelada métrica', 'Sinónimo: centner, métrico 100 kg; Quintal, métrico 100 kg', 'dt or dtn'),
('DU', 'dina', NULL, 'Dyn'),
('DWT', 'Pennyweight', 'La unidad obsoleta pennyweight era Unidad de masa utilizada en el Reino Unido antes de 1971. Se consideraba equivalente a la masa de un penique, y equivale a la 1/240 parte de una libra troy. Se abrevia pwt.', NULL),
('Dx', 'Dina por centímetro', NULL, 'Dyn / cm'),
('DY', 'Libro de directorio', NULL, NULL),
('DZN', 'Docena', 'Unidad de recuento de definir el número de unidades en múltiplos de 12.', 'DOZ'),
('DZP', 'Docena de paquete', 'Unidad de conteo que define el número de paquetes en múltiplos de 12 (paquete: unidad de embalaje estándar).', NULL),
('E01', 'Newton por centímetro cuadrado', 'Medida de la presión expresada en newtons por centímetro cuadrado', 'N/cm²'),
('E07', 'Megawatt hora por hora', 'Unidad de energía acumulado de un millón de vatios durante un período de una hora.', 'MW·h/h'),
('E08', 'Megavatios por hertz', 'Unidad de energía expresada como el cambio de carga en millones de watts que provocará un desplazamiento de frecuencia de un hertz.', 'MW/Hz'),
('E09', 'Miliamperio hora', 'Unidad de carga de potencia entregada a razón de una milésima parte de un amperio durante un período de una hora.', 'mA·h'),
('E10', 'Día de grado', 'Unidad de medida utilizada en la meteorología y la ingeniería para medir la demanda de calentamiento o enfriamiento durante un período determinado de días.', 'deg da'),
('E11', 'Gigacalorie', 'Una unidad de energía térmica equivalente a mil millones de calorías.', NULL),
('E12', 'Mille', 'Unidad de recuento de definir el número de cigarrillos en unidades de 1.000.', NULL),
('E14', 'Kilocaloría (tabla internacional)', NULL, 'kcalIT'),
('E15', 'Kilocaloría (termoquímica) por hora', NULL, 'kcalth/h'),
('E16', 'Millón de btu (ti) por hora', 'Unidad de potencia igual a un millón de unidades térmicas británicas por hora.', 'BtuIT/h'),
('E17', 'Pie cúbico por segundo', 'Unidad de volumen igual a un pie cúbico pasa por un punto dado en un periodo de un segundo.', 'ft³/s'),
('E18', 'Tonelada por hora', 'Una unidad de peso o masa equivalente a una tonelada métrica por hora.', 't/h'),
('E19', 'Ping', 'Unidad de área equivalente a 3,3 metros cuadrados.', NULL),
('E20', 'Megabit por segundo', 'Unidad de información igual a 10 ⁶  (1000000) bits (dígitos binarios) por segundo.', 'Mbit/s'),
('E21', 'Shares', 'Unidad de recuento para definir el número de acciones (proporción: un total o una parte de las partes en que se divide el capital de una entidad comercial).', NULL),
('E22', 'Tue', 'Unidad de recuento para definir el número de unidades equivalentes a veinte pies (TEU) como una medida de la capacidad de carga en contenedores.', NULL),
('E23', 'Neumático', 'Unidad de recuento de definir el número de neumáticos (una cubierta sólida o llena de aire colocado alrededor de una llanta de rueda para formar un contacto suave con la carretera, absorber los golpes y proporcionar tracción).', NULL),
('E25', 'Unidad activa', 'Unidad de conteo que define el número de unidades activas dentro de una sustancia.', NULL),
('E27', 'Dosis', 'Unidad de recuento de definir el número de dosis (dosis: una cantidad definida de un medicamento o fármaco).', NULL),
('E28', 'Tonelada seca de aire', 'Unidad de masa que define el número de toneladas de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('E3', 'remolque', NULL, NULL),
('E30', 'Hebra', 'Unidad de recuento de definir el número de hebras (hebra: de largo,, flexible, solo hilo delgado, tiras de fibra, filamento constituyente o múltiplos de la misma, trenzados entre sí).', NULL),
('E31', 'Metro cuadrado por litro', 'Unidad de recuento de definir el número de metros cuadrados por litro.', 'm²/l'),
('E32', 'Litros por hora', 'Unidad de recuento de definir el número de litros por hora.', 'l/h'),
('E33', 'Por mil pies', 'Unidad de recuento de definir el número de pies por mil unidades.', NULL),
('E34', 'Gigabyte', 'Unidad de información igual a 10⁹ bytes.', 'Gbyte'),
('E35', 'Terabyte', 'Unidad de información igual a 10¹² bytes.', 'Tbyte'),
('E36', 'Petabyte', 'Unidad de información igual a 10¹⁵ bytes.', 'Pbyte'),
('E37', 'Pixel', 'Unidad de recuento de definir el número de píxeles (píxel: elemento de imagen).', NULL),
('E38', 'Megapíxeles', 'Unidad de recuento igual a 10 $ ⁶ $ (1000000) píxeles (elementos de imagen).', NULL),
('E39', 'Puntos por pulgada', 'Unidad de información que define el número de puntos por pulgada lineal como una medida de la resolución o nitidez de una imagen gráfica.', 'dpi'),
('E4', 'Kilo bruto', 'Unidad de masa que define el número total de kilogramos antes de las deducciones.', NULL),
('E40', 'Parte por cien mil', 'Unidad de proporción igual a 10⁻⁵.', 'ppht'),
('E41', 'Kilogramo-fuerza por milímetro cuadrado', NULL, 'kgf·m/cm²'),
('E42', 'Kilogramo-fuerza por centímetro cuadrado', NULL, 'kgf/cm²'),
('E43', 'Joule por centímetro cuadrado', 'Una unidad de energía que define el número de julios por centímetro cuadrado.', 'J/cm²'),
('E44', 'Metros kilogramo-fuerza por centímetro cuadrado', 'Unidad de torsión que define el medidor de par kilogramo-fuerza por centímetro cuadrado.', 'kgf·m/cm²'),
('E45', 'MiliOhm', NULL, 'mΩ'),
('E46', 'Kilovatio hora por metro cúbico', 'Unidad de consumo de energía expresada como kilovatio hora por metro cúbico.', 'kW·h/m³'),
('E47', 'Kilovatio hora por kelvin', 'Unidad de consumo de energía expresada como kilovatio hora por kelvin.', 'kW·h/K'),
('E48', 'Unidad de servicio', 'Unidad de conteo que define el número de unidades de servicio (unidad de servicio: definido período / propiedad / centro / utilidad de alimentación).', NULL),
('E49', 'Día de trabajo', 'Unidad de recuento de definir el número de días de trabajo (jornada de trabajo: un día en el que se lleva a cabo normalmente un trabajo).', NULL),
('E5', 'Tonelada métrica larga', 'Utilice ton (UK) o tonelada larga (US) (código común LTN)', NULL),
('E50', 'Unidad de cuenta', 'Unidad de recuento de definir el número de unidades de contabilidad.', NULL),
('E51', 'Trabajo', 'Unidad de recuento de definir el número de puestos de trabajo.', NULL),
('E52', 'Run foot', 'Unidad de conteo para definir la distancia (en la unidad Pie) que se dan en una carrera).', NULL),
('E53', 'Prueba', 'Unidad de recuento de definir el número de pruebas.', NULL),
('E54', 'Viaje', 'Unidad de recuento de definir el número de viajes.', NULL),
('E55', 'Utilizar', 'Unidad de recuento de definir el número de veces que se utiliza un objeto.', NULL),
('E56', 'Bien', 'Unidad de recuento para definir el número de pozos.', NULL),
('E57', 'Zona', 'Unidad de conteo que define el número de zonas.', NULL),
('E58', 'Exabit por segundo', 'Unidad de información igual a 10¹⁸ bits (dígitos binarios) por segundo.', 'Ebit/s'),
('E59', 'Exbibyte', 'Unidad de información igual a 2⁶⁰ bytes.', 'Eibyte'),
('E60', 'Pebibyte', 'Unidad de información igual a 2⁵⁰ bytes.', 'Pibyte'),
('E61', 'Tebibyte', 'Unidad de información igual a 2⁴⁰ bytes.', 'Tibyte'),
('E62', 'Gibibyte', 'Unidad de información igual a 2³⁰ bytes.', 'Gibyte'),
('E63', 'Mebibyte', 'Unidad de información igual a 2²⁰ bytes.', 'Mibyte'),
('E64', 'Kibibyte', 'Unidad de información igual a 2¹⁰ bytes.', 'Kibyte'),
('E65', 'Exbibit por metro', 'Unidad de información igual a 2⁶⁰ bits (dígitos binarios) por metro.', 'Eibit/m'),
('E66', 'Exbibit por metro cuadrado', 'Unidad de información igual a 2⁶⁰ bits (dígitos binarios) por metro cuadrado.', 'Eibit/m²'),
('E67', 'Exbibit por metro cúbico', 'Unidad de información igual a 2⁶⁰ bits (dígitos binarios) por metro cúbico.', 'Eibit/m³'),
('E68', 'Gigabyte por segundo', 'Unidad de información igual a 10⁹ bytes por segundo.', 'Gbyte/s'),
('E69', 'Gibibit por metro', 'Unidad de información igual a 2³⁰ bits (dígitos binarios) por metro.', 'Gibit/m')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();