INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('18', 'Tambor de cincuenta y cinco galones (EUA)', NULL, NULL),
('19', 'Camión cisterna', NULL, NULL),
('26', 'Tonelada real', NULL, NULL),
('29', 'Libra por mil pies cuadrados', NULL, 'Lb / kft²'),
('30', 'Día de potencia de caballos por tonelada métrica de aire seco', NULL, NULL),
('31', 'Pescar', NULL, NULL),
('32', 'Kilogramo por tonelada métrica seca del aire', NULL, NULL),
('36', 'Pie cúbico por minuto por pie cuadrado', 'Se requiere factor de conversión', 'Ft³ / (min / ft²)'),
('44', 'Bolsa a granel de quinientos kilos', NULL, NULL),
('45', 'Bolsa a granel de trescientos kilos', NULL, NULL),
('46', 'Bolsa a granel de cincuenta libras', NULL, NULL),
('47', 'Bolso de cincuenta libras', NULL, NULL),
('48', 'Carga masiva', NULL, NULL),
('53', 'Kilogramo teórico', NULL, NULL),
('54', 'Tonelada teórica (UK)', NULL, NULL),
('62', 'Por ciento por 1000 horas', NULL, NULL),
('63', 'Tasa de fracaso en el tiempo', NULL, NULL),
('64', 'Libra por pulgada cuadrada, calíbre', NULL, NULL),
('66', 'Oersted', NULL, 'Oe'),
('69', 'Escala específica de prueba', NULL, NULL),
('71', 'Voltios amperios por libra', NULL, NULL),
('72', 'Vatio por libra', NULL, NULL),
('73', 'Amperios por centímetro', NULL, NULL),
('76', 'Gauss', NULL, 'Gs'),
('78', 'Kilogauss', NULL, 'Ks'),
('84', 'Kilopound-force por pulgada cuadrada', 'Unidad de presión que define el número de kilopounds fuerza por pulgada cuadrada. 

Utilice kip por pulgada cuadrada (código común N20).', 'Klbf / in²'),
('90', 'Saybold segundo universal', NULL, NULL),
('92', 'Calorías por centímetro cúbico', NULL, NULL),
('93', 'Calorías por gramo', 'Utilice calorías de la tabla internacional (IT) por gramo (código común D75).', 'Cal / g'),
('94', 'Unidad de curl', NULL, NULL),
('95', 'Veinte mil galones', NULL, NULL),
('96', 'Diez mil galones (US)', NULL, NULL),
('97', 'Diez kilos de tambor', NULL, NULL),
('98', 'Quince kilos de tambor', NULL, NULL),
('05', 'Ascensor', NULL, NULL),
('06', 'Pequeño aerosol', NULL, NULL),
('08', 'Montón de calor', NULL, NULL),
('10', 'Grupos', 'Una unidad de conteo que define el número de grupos (grupo: conjunto de elementos clasificados juntos).', NULL),
('11', 'Equipos', 'Unidad de recuento que define el número de equipos (equipo: un conjunto completo de equipo / materiales / objetos utilizados para un propósito específico).', NULL),
('13', 'Raciones', 'Una unidad de recuento para definir el número de raciones (ración: una sola porción de las disposiciones).', NULL),
('14', 'Shot', 'Unidad de medida para liquidos.', NULL),
('15', 'Palo, medida militar.', 'Unidad para el momento de rotación relacionado con la longitud según el sistema de unidades Anglo-Americanas e Imperial.', NULL),
('16', 'Tambor de 115 kilogramos', NULL, NULL),
('17', 'Tambor de cien libras', NULL, NULL),
('1A', 'Milla de carros', NULL, NULL),
('1B', 'Recuento de automóviles', NULL, NULL),
('1C', 'Conteo de locomotoras', NULL, NULL),
('1D', 'Caboose count', NULL, NULL),
('1E', 'Coche vacío', NULL, NULL),
('1F', 'Milla de tren', NULL, NULL),
('1G', 'Galón del uso del combustible (los EUA)', NULL, NULL),
('1H', 'Milla de caboose', NULL, NULL),
('1I', 'Tipo de interés fijo', 'Unidad de cantidad expresada como una tasa predeterminada o conjunto para el uso de una instalación o servicio.', NULL),
('1J', 'Tonelada milla', NULL, NULL),
('1K', 'Milla locomotora', NULL, NULL),
('1L', 'Recuento total de automóviles', NULL, NULL),
('1M', 'Milla total del coche', NULL, NULL),
('1X', 'Cuarto de milla', NULL, NULL),
('20', 'Contenedores de veinte pies', 'Unidad de conteo que define el número de contenedores de transporte que miden 20 pies de longitud.', NULL),
('21', 'Contenedor de cuarenta pies', 'Unidad de conteo que define el número de contenedores de transporte que miden 40 pies de longitud.', NULL),
('22', 'Decilitro por gramo', NULL, 'dl/g'),
('23', 'Gramo por centímetro cúbico', NULL, 'g/cm³'),
('24', 'Libra teórica', 'Unidad de masa que define la masa esperada de material expresado como el número de libras.', NULL),
('25', 'Gramo por centímetro cuadrado', NULL, 'g/cm²'),
('27', 'Tonelada teórica', 'Unidad de masa que define la masa esperada de material, expresada como el número de toneladas.', NULL),
('28', 'Kilogramo por metro cuadrado', NULL, 'kg/m²'),
('2A', 'Radián por segundo', 'Es la velocidad de un cuerpo que, con una rotación uniforme alrededor de un eje fijo, gira en 1 segundo, 1 radián.', 'rad/s'),
('2B', 'Radián por segundo cuadrado', 'Es la aceleración angular de un cuerpo animado de una rotación uniformemente variada alrededor de un eje fijo, cuya velocidad angular, varía 1 radián por segundo, en 1 segundo.', 'rad/s²'),
('2C', 'Roentgen', NULL, 'R'),
('2G', 'Voltios CA', 'Una unidad de potencial eléctrico en relación a la corriente alterna (CA).', 'V'),
('2H', 'Voltios CD', 'Unidad de potencial eléctrico en relación con corriente directa (CD).', 'V'),
('2I', 'Unidad térmica británica (tabla internacional) por hora', NULL, 'BtuIT/h'),
('2J', 'Centímetro cúbico por segundo', NULL, 'cm³/s'),
('2K', 'Pie cúbico por hora', NULL, 'ft³/h'),
('2L', 'Pie cúbico por minuto', NULL, 'ft³/min'),
('2M', 'Centímetro por segundo', NULL, 'cm/s'),
('2N', 'Decibel', 'Medida de sonoridad o sensación sonora que es igual a la décima parte de un bel.', 'dB'),
('2P', 'Kilobyte', 'Unidad de información igual a 10 ³  (1000) bytes.', 'kbyte'),
('2Q', 'Kilobecquerel', NULL, 'kBq'),
('2R', 'Kilocurie', NULL, 'kCi'),
('2U', 'Megagramo', NULL, 'Mg'),
('2V', 'Megagrama por hora', NULL, 'Mg / h'),
('2X', 'Metro por minuto', NULL, 'm/min'),
('2Y', 'Milliroentgen', NULL, 'mR'),
('2Z', 'Milivoltio', NULL, 'mV'),
('33', 'Kilopascal por grtr', NULL, 'kPa·m²/g'),
('34', 'Kilopascal por milimetro', NULL, 'kPa/mm'),
('35', 'Milimetro por un segundo centimetro cuadrado', NULL, 'ml/(cm²·s)'),
('37', 'Onza por pie cuadrado', NULL, 'oz/ft²'),
('38', 'Onzas por pie cuadrado por 0,01 pulgadas', NULL, 'oz/(ft²/cin)'),
('3B', 'Megajoule', NULL, 'MJ'),
('3C', 'Manmonth', 'Unidad de cuenta que define el número de meses que una persona o personas pueden desempeñar alguna actividad.', NULL),
('3E', 'Libra por libra de producto', NULL, NULL),
('3G', 'Libra por pieza de producto', NULL, NULL),
('3H', 'Kilogramo por kilogramo de producto', NULL, NULL),
('3I', 'Kilogramo por pedazo de producto', NULL, NULL),
('40', 'Mililitro por segundo', NULL, 'ml/s'),
('41', 'Mililitro por minuto', NULL, 'ml/min'),
('4B', 'Gorra', NULL, NULL),
('4C', 'Centistokes', NULL, 'cSt')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();