INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('K90', 'Libra-fuerza por pulgada cuadrada yarda cúbica por segundo', NULL, 'psi·yd³/s'),
('K91', 'Libra-fuerza segundo por pie cuadrado', NULL, 'lbf·s/ft²'),
('K92', 'Libra-fuerza segundo por pulgada cuadrada', NULL, 'lbf·s/in²'),
('K93', 'Reciprocidad psi', NULL, '1/psi'),
('K94', 'Cuarto (líquido, UK) por día', NULL, 'qt (UK liq.)/d'),
('K95', 'Cuarto (líquido, UK) por hora', NULL, 'qt (UK liq.)/h'),
('K96', 'Cuarto (líquido, UK) por minuto', NULL, 'qt (UK liq.)/min'),
('K97', 'Cuarto (líquido, UK) por segundo', NULL, 'qt (UK liq.)/s'),
('K98', 'Cuarto (líquido, estados unidos) por día', NULL, 'qt (US liq.)/d'),
('K99', 'Cuarto (líquido, estados unidos) por hora', NULL, 'qt (US liq.)/h'),
('KA', 'Pastel', 'Unidad de conteo que define el número de pasteles (torta: objeto en forma de una masa plana y compacta).', NULL),
('KAT', 'Katal', 'Una unidad de actividad catalítica que define la actividad catalítica de las enzimas y otros catalizadores.', 'kat'),
('KB', 'Kilocaracter', 'Unidad de información igual a 10³ (1000) caracteres.', NULL),
('KBA', 'Kilobar', NULL, 'kbar'),
('KCC', 'Kilogramo de cloruro de colina', 'Unidad de masa igual a mil gramos de cloruro de colina.', 'kg C₅ H₁₄ClNO'),
('KD', 'Kilogram decimal', NULL, NULL),
('KDW', 'Kilogramo de peso neto drenado', 'Unidad de masa que define el número neto de kilogramos de un producto, sin tener en cuenta el contenido líquido del producto.', 'kg/net eda'),
('KEL', 'Kelvin', 'Unidad de temperatura termodinámica, es la fracción 1/273,16 de la temperatura termodinámica del punto triple del agua.', 'K'),
('KF', 'Kilopacket', NULL, NULL),
('KGM', 'Kilogramo', 'Una unidad de masa igual a mil gramos.', 'kg'),
('KGS', 'Kilogramo por segundo', NULL, 'kg/s'),
('KHY', 'Kilogramo de peróxido de hidrógeno', 'Unidad de masa igual a mil gramos de peróxido de hidrógeno.', 'kg H₂O₂'),
('KHZ', 'Kilohertz', 'Medida de frecuencia que es igual a 1000 hertz.', 'kHz'),
('KI', 'Kilogramo por milímetro de ancho', NULL, NULL),
('KIC', 'Kilogramo, incluyendo el contenedor', 'Unidad de masa que define el número de kilogramos de un producto, incluido su contenedor.', NULL),
('KIP', 'Kilogramo, incluyendo el empaquetado interno', 'Unidad de masa que define el número de kilogramos de un producto, incluyendo sus materiales de embalaje internos.', NULL),
('KJ', 'Kilosegmento', 'Unidad de información igual a 10³ (1000) segmentos.', NULL),
('KJO', 'Kilojoule', NULL, 'kJ'),
('KL', 'Kilogramo por metro', NULL, 'kg/m'),
('KLK', 'Porcentaje de material seco láctico', 'Unidad de proporción que define el porcentaje de material láctico seco en un producto.', NULL),
('KLX', 'Kilolux', 'Una unidad de iluminancia igual a mil lux.', 'klx'),
('KMA', 'Kilogramo de metilamina', 'Unidad de masa igual a mil gramos de metilamina.', 'kg met.am.'),
('KMH', 'Kilómetro por hora', NULL, 'km/h'),
('KMK', 'Kilómetro cuadrado', 'Es la unidad de superficie de área que se corresponde con un cuadrado de un kilómetro de lado.', 'km²'),
('KMQ', 'Kilogramo por metro cúbico', 'Unidad de peso expresada en kilogramos de una sustancia que llena un volumen de un metro cúbico.', 'kg/m³'),
('KMT', 'Kilómetro', 'Es una unidad de longitud. Es el tercer múltiplo del metro, equivalente a 1000 metros. Su símbolo es km y no acepta plural ni lleva punto final —excepto cuando se encuentra como último elemento de una frase u oración— por no tratarse de una abreviatura.', 'km'),
('KNI', 'Kilogramo de nitrógeno', 'Unidad de masa igual a mil gramos de nitrógeno.', 'kg N'),
('KNM', 'Kolonewton por metro cuadrado', NULL, 'KN/m2'),
('KNS', 'Kilogram sustancia nombrada', 'Unidad de masa igual a un kilogramo de una sustancia llamada.', NULL),
('KNT', 'Nudo', 'El nudo es una medida de velocidad utilizada tanto para navegación marítima como aérea, equivalente a 1852 m/hora. También se utiliza en meteorología para medir la velocidad de los vientos.', 'kn'),
('KO', 'Miliequivalentes de potasa cáustica por gramo de producto', 'Unidad de conteo que define el número de miligramos de hidróxido de potasio por gramo de producto como una medida de la concentración de hidróxido de potasio en el producto.', NULL),
('KPA', 'Kilopascal', NULL, 'kPa'),
('KPH', 'Kilogramo de hidróxido de potasio (potasa cáustica)', 'Unidad de masa igual a mil gramos de hidróxido de potasio (potasa cáustica).', 'kg KOH'),
('KPO', 'Kilogramo de óxido de potasio', 'Unidad de masa igual a mil gramos de óxido de potasio.', 'kg K₂O'),
('KPP', 'Kilogramo de pentóxido de fósforo (anhídrido fosfórico)', 'Unidad de masa igual a mil gramos de anhídrido fosfórico de pentóxido de fósforo.', NULL),
('KR', 'Kiloroentgen', NULL, 'kR'),
('KS', 'Mil libras por pulgada cuadrada', NULL, NULL),
('KSD', 'Kilogramo de sustancia 90% seco', 'Unidad de masa igual a mil gramos de una sustancia llamada 90% seca.', 'kg 90 % sdt'),
('KSH', 'Kilogramo de hidróxido de sodio (sodio cáustica)', 'Unidad de masa igual a mil gramos de hidróxido sódico (sosa cáustica).', 'kg NaOH'),
('KT', 'Kit', 'Unidad de conteo que define el número de kits (kit: bañera, barril o cubo).', NULL),
('KTN', 'Kilotonelada Métrica', NULL, 'kt'),
('KUR', 'Kilogramo de uranio', 'Unidad de masa igual a mil gramos de uranio.', 'kg U'),
('KVA', 'Kilovoltio - amperio', NULL, 'kV·A'),
('KVR', 'Kilovar', NULL, 'kvar'),
('KVT', 'Kilovoltio', NULL, 'kV'),
('KW', 'Kilogramo por milímetro', NULL, 'kg/mm'),
('KWH', 'Kilowatt hora', NULL, 'kW·h'),
('KWN', 'Kilowatt hora por metro cúbico normalizado', 'Kilowatt hora por metro cúbico normalizado (temperatura 0 ° C y presión 101325 milibares).', NULL),
('KWO', 'Kilogramo de trióxido de tungsteno', 'A unit of mass equal to one thousand grams of tungsten trioxide.', 'kg WO₃'),
('KWS', 'Kilowatt hora por metro cúbico estándar', 'Kilowatt hora por metro cúbico normalizado (temperatura 15 ° C y presión 101325 milibares).', NULL),
('KWT', 'Kilowatt', NULL, 'kW'),
('KX', 'Mililitro por kilogramo', NULL, 'ml/kg'),
('L10', 'Cuarto (líquido, estados unidos) por minuto', NULL, 'qt (US liq.)/min'),
('L11', 'Cuarto (líquido, estados unidos) por segundo', NULL, 'qt (US liq.)/s'),
('L12', 'Metro por segundo kelvin', NULL, '(m/s)/K'),
('L13', 'Metro por segundo bar', NULL, '(m/s)/bar'),
('L14', 'Metro cuadrado hora grado celsius por kilocaloría (tabla internacional)', NULL, 'm²·h·°C/kcal'),
('L15', 'Milipascal segundo por kelvin', NULL, 'mPa·s/K'),
('L16', 'Milipascal segundo por bar', NULL, 'mPa·s/bar'),
('L17', 'Miligramo por metro cúbico kelvin', NULL, '(mg/m³)/K'),
('L18', 'Miligramo por metro cúbico bar', NULL, '(mg/m³)/bar'),
('L19', 'Mililitro por litro', NULL, 'ml/l'),
('L2', 'Litro por minuto', NULL, 'l/min'),
('L20', 'Reciprocidad del milimetro cúbico', NULL, '1/mm³'),
('L21', 'Milimetro cúbico por metro cúbico', NULL, 'mm³/m³'),
('L23', 'Mol por hora', NULL, 'mol/h'),
('L24', 'Mol por kilogramo kelvin', NULL, '(mol/kg)/K'),
('L25', 'Mol por kilogramo bar', NULL, '(mol/kg)/bar'),
('L26', 'Mol por litreo kelvin', NULL, '(mol/l)/K'),
('L27', 'Mol por litro bar', NULL, '(mol/l)/bar'),
('L28', 'Mol por metro cúbico kelvin', NULL, '(mol/m³)/K'),
('L29', 'Mol por metro cúbico bar', NULL, '(mol/m³)/bar'),
('L30', 'Mol por minuto', NULL, 'mol/min'),
('L31', 'Milliroentgen aequivalent men', NULL, 'mrem'),
('L32', 'Nanogramo por kilogramo', NULL, 'ng/kg'),
('L33', 'Onza (avoirdupois) por día', NULL, 'oz/d'),
('L34', 'Onza (avoirdupois) por hora', NULL, 'oz/h'),
('L35', 'Onza (avoirdupois) por minuto', NULL, 'oz/min'),
('L36', 'Onza (avoirdupois) por segundo', NULL, 'oz/s'),
('L37', 'Onza (avoirdupois) por galón (UK)', NULL, 'oz/gal (UK)'),
('L38', 'Onza (avoirdupois) por galón (EUA)', NULL, 'oz/gal (US)'),
('L39', 'Onza (avoirdupois) por pulgada cúbica', NULL, 'oz/in³'),
('L40', 'Onza fuerza', NULL, 'ozf'),
('L41', 'Onza (avoirdupois) fuerza pulgada', NULL, 'ozf·in'),
('L42', 'Picosiemens por metro', NULL, 'pS/m'),
('L43', 'Peck (UK)', 'Un peck es una unidad tradicional de medida de volúmenes. Aunque puede ser utilizado para medir seco y líquido, se utiliza generalmente para las materias secas. Es igual a 1/4 bushel, 2 galones, o 8 cuartos de galón.', 'pk (UK)'),
('L44', 'Peck (UK) por día', NULL, 'pk (UK)/d'),
('L45', 'Peck (UK) por hora', NULL, 'pk (UK)/h'),
('L46', 'Peck (UK) por minuto', NULL, 'pk (UK)/min'),
('L47', 'Peck (UK) por segundo', NULL, 'pk (UK)/s')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();