INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('E70', 'Gibibit por metro cuadrado', 'Unidad de información igual a 2³⁰ bits (dígitos binarios) por metro cuadrado.', 'Gibit/m²'),
('E71', 'Gibibit por metro cúbico', 'Unidad de información igual a 2³⁰ bits (dígitos binarios) por metro cúbico.', 'Gibit/m³'),
('E72', 'Kibibit por metro', 'Unidad de información igual a 2¹⁰ bits (dígitos binarios) por metro.', 'Kibit/m'),
('E73', 'Kibibit por metro cuadrado', 'Unidad de información igual a 2¹⁰ bits (dígitos binarios) por metro cuadrado.', 'Kibit/m²'),
('E74', 'Kikibit por metro cúbico.', 'Unidad de información igual a 2¹⁰ bits (dígitos binarios) por metro cúbico.', 'Kibit/m³'),
('E75', 'Mebbit por metro.', 'Unidad de información igual a 2²⁰ bits (dígitos binarios) por metro.', 'Mibit/m'),
('E76', 'Mebbitt por metro cuadrado.', 'Unidad de información igual a 2²⁰ bits (dígitos binarios) por metro cuadrado.', 'Mibit/m²'),
('E77', 'Mebbit por metro cúbico.', 'Unidad de información igual a 2²⁰ bits (dígitos binarios) por metro cúbico.', 'Mibit/m³'),
('E78', 'Petabit', 'Unidad de información igual a 10¹⁵ los bits (dígitos binarios).', 'Pbit'),
('E79', 'Pebibit por segundo.', 'Unidad de información igual a 10¹⁵ bits (dígitos binarios) por segundo.', 'Pbit/s'),
('E80', 'Pebibit por metro.', 'Unidad de información igual a 2⁵⁰ bits (dígitos binarios) por metro.', 'Pibit/m'),
('E81', 'Pebibit por metro cuadrado.', 'Unidad de información igual a 2⁵⁰ bits (dígitos binarios) por metro cuadrado.', 'Pibit/m²'),
('E82', 'Pebibit por metro cúbico.', 'Unidad de información igual a 2⁵⁰ bits (dígitos binarios) por metro cúbico.', 'Pibit/m³'),
('E83', 'Tebibit.', 'Unidad de información igual a 10¹² los bits (dígitos binarios).', 'Tbit'),
('E84', 'Tebibit por segundo', 'Unidad de información igual a 10¹² bits (dígitos binarios) por segundo.', 'Tbit/s'),
('E85', 'Tebibit por metro.', 'Unidad de información igual a 2⁴⁰ bits (dígitos binarios) por metro.', 'Tibit/m'),
('E86', 'Tebibit por metro cúbico.', 'Unidad de información igual a 2⁴⁰ bits (dígitos binarios) por metro cúbico.', 'Tibit/m³'),
('E87', 'Tebibit por metro cuadrado', 'Unidad de información igual a 2⁴⁰ bits (dígitos binarios) por metro cuadrado.', 'Tibit/m²'),
('E88', 'Bit por metro', 'Unidad de información igual a 1 bit (dígito binario) por metro.', 'bit/m'),
('E89', 'Bit por metro cuadrado', 'Unidad de información igual a 1 bit (dígito binario) por metro cuadrado.', 'bit/m²'),
('E90', 'Centímetro recíproco', NULL, 'cm⁻¹'),
('E91', 'Día recíproco', NULL, 'd⁻¹'),
('E92', 'Decímetro cúbico por hora', NULL, 'dm³/h'),
('E93', 'Kilogramo por hora', NULL, 'kg/h'),
('E94', 'KiloMol por segundo', NULL, 'kmol/s'),
('E95', 'Mol por segundo', NULL, 'mol/s'),
('E96', 'Grado por segundo', NULL, '°/s'),
('E97', 'Mililitro por gadro celsius metro', NULL, 'mm/(°C·m)'),
('E98', 'Grado celsius por kelvin', NULL, '°C/K'),
('E99', 'Hectopascal por bar', NULL, 'hPa/bar'),
('EA', 'Elemento', 'Unidad de conteo que define el número de elementos considerados como unidades separadas.', NULL),
('EB', 'Casilla de correo electrónico', 'Es el destino al que correo electrónico se entregan los mensajes. Es el equivalente de un buzón en el sistema postal.', NULL),
('EP', 'Paquete de once', NULL, NULL),
('EQ', 'Galón equivalente', 'Unidad de volumen que define el número de galones de producto producido a partir de concentrado.', NULL),
('F01', 'Bit por metro cúbico', 'Unidad de información igual a 1 bit (dígito binario) por metro cúbico.', 'bit/m³'),
('F02', 'Kelvin por kelvin', NULL, 'K/K'),
('F03', 'Kilopascal por bar', NULL, 'kPa/bar'),
('F04', 'Milibar por bar', NULL, 'mbar/bar'),
('F05', 'Megapascal por bar', NULL, 'MPa/bar'),
('F06', 'Poise por bar', NULL, 'P/bar'),
('F07', 'Pascal por bar', NULL, 'Pa/bar'),
('F08', 'Miliamperio por pulgada', NULL, 'mA/in'),
('F1', 'Mil pies cúbicos por día', NULL, NULL),
('F10', 'Kelvin por hora', NULL, 'K/h'),
('F11', 'Kelvin por minuto', NULL, 'K/min'),
('F12', 'Kelvin por segundo', NULL, 'K/s'),
('F13', 'Slug', 'Una unidad de masa. Un slug es la masa acelerada a 1 pie por segundo por segundo por una fuerza de 1 libra.', 'slug'),
('F14', 'Gramo por kelvin', NULL, 'g/K'),
('F15', 'Kilogramo por kelvin', NULL, 'kg/K'),
('F16', 'Miligramo por kelvin', NULL, 'mg/K'),
('F17', 'Libra fuerza por pie', NULL, 'lbf/ft'),
('F18', 'Kilogramo centímetro cuadrado', NULL, 'kg·cm²'),
('F19', 'Kilogramo milimetro cuadrado', NULL, 'kg·mm²'),
('F20', 'Libra pulgada cuadrada', NULL, 'lb·in²'),
('F21', 'Libra fuerza pulgada', NULL, 'lbf·in'),
('F22', 'Libra fuerza por pie entre amperio', NULL, 'lbf·ft/A'),
('F23', 'Gramo por decímetro cúbico', NULL, 'g/dm³'),
('F24', 'Kilogramo por kiloMol', NULL, 'kg/kmol'),
('F25', 'Gramo por hertz', NULL, 'g/Hz'),
('F26', 'Gramo por día', NULL, 'g/d'),
('F27', 'Gramo por hora', NULL, 'g/h'),
('F28', 'Gramo por minuto', NULL, 'g/min'),
('F29', 'Gramo por segundo', NULL, 'g/s'),
('F30', 'Kilogramo por día', NULL, 'kg/d'),
('F31', 'Kilogramo por minuto', NULL, 'kg/min'),
('F32', 'Miligramo por dia', NULL, 'mg/d'),
('F33', 'Miligramo por minuto', NULL, 'mg/min'),
('F34', 'Miligramo por segundo', NULL, 'mg/s'),
('F35', 'Gramo por día kelvin', NULL, 'g/(d·K)'),
('F36', 'Gramo por hora kelvin', NULL, 'g/(h·K)'),
('F37', 'Gramo por minuto kelvin', NULL, 'g/(min·K)'),
('F38', 'Gramo por segundo kelvin', NULL, 'g/(s·K)'),
('F39', 'Kilogramo por día kelvin', NULL, 'kg/(d·K)'),
('F40', 'Kilogramo por hora kelvin', NULL, 'kg/(h·K)'),
('F41', 'Kilogramo por minuto kelvin', NULL, 'kg/(min·K)'),
('F42', 'Kilogramo por segundo kelvin', NULL, 'kg/(s·K)'),
('F43', 'Miligramo por día kelvin', NULL, 'mg/(d·K)'),
('F44', 'Miligramo por hora kelvin', NULL, 'mg/(h·K)'),
('F45', 'Miligramo por minuto kelvin', NULL, 'mg/(min·K)'),
('F46', 'Miligramo por segundo kelvin', NULL, 'mg/(s·K)'),
('F47', 'Newton por milímetro', NULL, 'N/mm'),
('F48', 'Libra fuerza por pulgada', NULL, 'lbf/in'),
('F49', 'Rod (Unidad de distancia)', 'Unidad de distancia equivalente a 5.5 yardas (16 pies 6 pulgadas)', 'rd (US)'),
('F50', 'Micrómetro por kelvin', NULL, 'µm/K'),
('F51', 'Centímetro por kelvin', NULL, 'cm/K'),
('F52', 'Metro por kelvin', NULL, 'm/K'),
('F53', 'Mililitro por kelvin', NULL, 'mm/K'),
('F54', 'MiliOhm por metro', NULL, 'mΩ/m'),
('F55', 'Ohm por milla (milla estatal)', NULL, 'Ω/mi'),
('F56', 'Ohm por kilómetro', NULL, 'Ω/km'),
('F57', 'Miliamperio por libra-fuerza por pulgada cuadrada', NULL, 'mA/(lbf/in²)'),
('F58', 'Bar recíproco', NULL, '1/bar'),
('F59', 'Miliamperio por bar', NULL, 'mA/bar'),
('F60', 'Grado celsius por bar', NULL, '°C/bar'),
('F61', 'Kelvin por bar', NULL, 'K/bar'),
('F62', 'Gramo por día bar', NULL, 'g/(d·bar)'),
('F63', 'Gramo por hora bar', NULL, 'g/(h·bar)'),
('F64', 'Gramo por minuto bar', NULL, 'g/(min·bar)'),
('F65', 'Gramo por segundo bar', NULL, 'g/(s·bar)'),
('F66', 'Kililogramo por día bar', NULL, 'kg/(d·bar)')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();