INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('L48', 'Peck (seco, estados unidos) por día', NULL, 'pk (US dry)/d'),
('L49', 'Peck (seco, estados unidos) por hora', NULL, 'pk (US dry)/h'),
('L50', 'Peck (seco, estados unidos) por minuto', NULL, 'pk (US dry)/min'),
('L51', 'Peck (seco, estados unidos) por segundo', NULL, 'pk (US dry)/s'),
('L52', 'Libra.fuerza por pulgada cuadrada por libra fuerza por pulgada cuadrada', NULL, 'psi/psi'),
('L53', 'Pinta (UK) por día', NULL, 'pt (UK)/d'),
('L54', 'Pinta (UK) por hora', NULL, 'pt (UK)/h'),
('L55', 'Pinta (UK) por minuto', NULL, 'pt (UK)/min'),
('L56', 'Pinta (UK) por segundo', NULL, 'pt (UK)/s'),
('L57', 'Pinta (líquido, estados unidos) por día', NULL, 'pt (US liq.)/d'),
('L58', 'Pinta (líquido, estados unidos) por hora', NULL, 'pt (US liq.)/h'),
('L59', 'Pinta (líquido, estados unidos) por minuto', NULL, 'pt (US liq.)/min'),
('L60', 'Pinta (líquido, estados unidos) por segundo', NULL, 'pt (US liq.)/s'),
('L61', 'Pinta (US seco)', 'Utilice pinta seca (código común PTD)', 'Pt (US seco)'),
('L62', 'Cuarto de galón (seco de los EUA)', 'Utilice cuarto seco (EUA) (código común QTD)', 'Qt (US seco)'),
('L63', 'Slug por día', NULL, 'slug/d'),
('L64', 'Slug por pie segundo', NULL, 'slug/(ft·s)'),
('L65', 'Slug por pie cúbico', NULL, 'slug/ft³'),
('L66', 'Slug por hora', NULL, 'slug/h'),
('L67', 'Slug por minuto', NULL, 'slug/min'),
('L68', 'Slug por segundo', NULL, 'slug/s'),
('L69', 'Tonelada por kelvin', NULL, 't/K'),
('L70', 'Tonelada por bar', NULL, 't/bar'),
('L71', 'Tonelada por día', NULL, 't/d'),
('L72', 'Tonelada por día kelvin', NULL, '(t/d)/K'),
('L73', 'Tonelada por día bar', NULL, '(t/d)/bar'),
('L74', 'Tonelada por hora kelvin', NULL, '(t/h)/K'),
('L75', 'Tonelada por hora bar', NULL, '(t/h)/bar'),
('L76', 'Tonelada por metro cúbico kelvin', NULL, '(t/m³)/K'),
('L77', 'Tonelada por metro cúbico bar', NULL, '(t/m³)/bar'),
('L78', 'Tonelada por minuto', NULL, 't/min'),
('L79', 'Tonelada por minuto kelvin', NULL, '(t/min)/K'),
('L80', 'Tonelada por minuto bar', NULL, '(t/min)/bar'),
('L81', 'Tonelada por segundo', NULL, 't/s'),
('L82', 'Tonelada por segundo kelvin', NULL, '(t/s)/K'),
('L83', 'Tonelada por segundo bar', NULL, '(t/s)/bar'),
('L84', 'Tonelada (flota UK)', NULL, 'British shipping ton'),
('L85', 'Tonelada larga por día', NULL, 'ton (UK)/d'),
('L86', 'Tonelada (flota estados unidos)', NULL, '(US) shipping ton'),
('L87', 'Tonelada corta por grado fahrenheit', NULL, 'ton (US)/°F'),
('L88', 'Tonelada corta por día', NULL, 'ton (US)/d'),
('L89', 'Tonelada corta por hora grados fahrenheit', NULL, 'ton (US)/(h·°F)'),
('L90', 'Tonelada corta por hora libra-fuerza por pulgada cuadrada', NULL, '(ton (US)/h)/psi'),
('L91', 'Tonelada corta por psi', NULL, 'ton (US)/psi'),
('L92', 'Tonelada larga (UK) por yarda cúbica', NULL, 'ton.l/yd³ (UK)'),
('L93', 'Tonelada corta (estados unidos) por yarda cúbica', NULL, 'ton.s/yd³ (US)'),
('L94', 'Tonelada fuerza', NULL, 'ton.sh-force'),
('L95', 'Año común', 'Es un año civil de 365 días, uno menos que el año bisiesto, por lo que tiene exactamente 52 semanas y un día. El reparto de los años civiles entre años comunes y años bisiestos se hace de acuerdo con el calendario gregoriano: en cada período de 400 años hay 303 comunes y 97 bisiestos.', 'y (365 days)'),
('L96', 'Año sideral', 'Es el tiempo que trascurre entre dos pasos consecutivos de la Tierra por un mismo punto de su órbita, tomando como referencia a las estrellas.', 'y (sidereal)'),
('L98', 'Yarda por grado fahrenheit', NULL, 'yd/°F'),
('L99', 'Yarda por psi (libra por pulgada cuadrada)', NULL, 'yd/psi'),
('LA', 'Libra por pulgada cúbica', NULL, 'lb/in³'),
('LAC', 'Porcentaje de exceso de lactosa', 'Unidad de proporción que define el porcentaje de lactosa en un producto que excede un nivel de porcentaje definido.', NULL),
('LBR', 'Libra', 'Unidad monetaria de Irlanda (hasta su sustitución por el euro), Reino Unido, Chipre, Egipto, Líbano, Malta, Siria y otros países.', 'lb'),
('LBT', 'Troy pound', NULL, NULL),
('LC', 'Centímetro lineal', NULL, NULL),
('LD', 'Litro por día', NULL, 'l/d'),
('LE', 'Lite', NULL, NULL),
('LEF', 'Hoja', 'Unidad de conteo que define el número de hojas.', NULL),
('LF', 'Pie lineal', 'Unidad de conteo que define el número de pies (12 pulgadas) de longitud de un objeto de ancho uniforme.', NULL),
('LH', 'Hora de trabajo', 'Unidad de tiempo que define el número de horas de trabajo.', NULL),
('LI', 'Pulgada lineal', NULL, NULL),
('LJ', 'Spray grande', NULL, NULL),
('LK', 'Enlazar', 'Unidad de distancia igual a 0.01 cadena.', NULL),
('LM', 'Metro lineal', 'Unidad de conteo que define el número de metros de longitud de un objeto de ancho uniforme.', NULL),
('LN', 'Longitud', 'Unidad de distancia que define la extensión lineal de un elemento medido de extremo a extremo.', NULL),
('LO', 'Lote [unidad de adquisición]', 'Unidad de conteo que define el número de lotes (lote: una colección de artículos asociados).', NULL),
('LP', 'Libra líquida', 'Unidad de masa que define el número de libras de una sustancia líquida.', NULL),
('LPA', 'Litro de alcohol puro', 'Unidad de volumen igual a un litro de alcohol puro.', NULL),
('LR', 'Capa', 'Unidad de conteo que define el número de capas.', NULL),
('LS', 'Suma global', 'Unidad de conteo que define el número de cantidades monetarias completas o completas.', NULL),
('LTN', 'Tonelada (UK) o tonelada larga (estados unidos)', 'Sinónimo: tonelada bruta (2240 ​​lb)', 'ton (UK)'),
('LTR', 'Litro', 'Es una unidad de volumen equivalente a un decímetro cúbico (1 dm³). Su uso es aceptado en el Sistema Internacional de Unidades (SI), aunque ya no pertenece estrictamente a él.', 'l'),
('LUB', 'Tonelada métrica, aceite lubricante', 'Unidad de masa que define el número de toneladas métricas de aceite lubricante.', NULL),
('LUM', 'Lumen', 'El lumen es la unidad estándar del flujo luminoso de una fuente de luz. Es una unidad derivada del sistema internacional, basada en la candela.', 'lm'),
('LUX', 'Lux', 'Un lux es la incidencia perpendicular de un lumen en una superficie de 1 metro cuadrado. Equivale a 0.0929 lúmenes.', 'lx'),
('LX', 'Yarda lineal por libra', NULL, NULL),
('LY', 'Yarda lineal', 'Unidad de conteo que define el número de unidades de 36 pulgadas en longitud de un objeto de ancho uniforme.', NULL),
('M0', 'cinta magnética', NULL, NULL),
('M1', 'Miligramo por litro', NULL, 'mg/l'),
('M10', 'Reciprocidad de la yarda cuadrada', NULL, '1/yd³'),
('M11', 'Yarda cúbica por grado fahrenheit', NULL, 'yd³/°F'),
('M12', 'Yarda cúbica por día', NULL, 'yd³/d'),
('M13', 'Yarda cúbica por hora', NULL, 'yd³/h'),
('M14', 'Yarda cúbica por psi (libra por pulgada cuadrada)', NULL, 'yd³/psi'),
('M15', 'Yarda cúbica por minuto', NULL, 'yd³/min'),
('M16', 'Yarda cúbica por segundo', NULL, 'yd³/s'),
('M17', 'Kilohertz metro', NULL, 'kHz·m'),
('M18', 'Gigahertz metro', NULL, 'GHz·m'),
('M19', 'Beaufort', 'Una medida empírica para describir la velocidad del viento basada principalmente en condiciones marinas observadas. La escala de Beaufort indica la velocidad del viento por números que típicamente varían de 0 para la calma, a 12 para el huracán.', 'Bft'),
('M20', 'Recíproco de megakelvin ó megakelvin a la potencia menos 1', NULL, '1/MK'),
('M21', 'Kilovoltio-amperio hora recíprocidad', NULL, '1/kVAh'),
('M22', 'Milímetro por centímetro cuadrado minuto', NULL, '(ml/min)/cm²'),
('M23', 'Newton por centímetro', NULL, 'N/cm'),
('M24', 'Ohm kilómetro', NULL, 'Ω·km'),
('M25', 'Porcentaje por grado celsius', 'Unidad de proporción, igual a 0,01, en relación a una temperatura de un grado.', '%/°C'),
('M26', 'GigaOhm por metro', NULL, 'GΩ/m'),
('M27', 'Megahertz metro', NULL, 'MHz·m'),
('M29', 'Kilogramo por kilogramo', NULL, 'kg/kg'),
('M30', 'voltio-amperio segundo recíprocidad', NULL, '1/(V·A·s)')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();