INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('XJY', 'Bidón, cilíndrico', NULL, NULL),
('XKG', 'Barrilete', NULL, NULL),
('XKI', 'Kit (Conjunto de piezas)', 'Conjunto de artículos o implementos utilizados para un propósito específico.', NULL),
('XLE', 'Valijas', 'Colección de bolsas, cajas y / o contenedores que contienen objetos personales para un viaje.', NULL),
('XLG', 'Bitacora', NULL, NULL),
('XLT', 'Lote', NULL, NULL),
('XLU', 'Caja de arrastre', 'Caja de madera para el transporte y almacenamiento de frutas y verduras.', NULL),
('XLV', 'Contenedor pequeño', 'Contenedor de madera o metal, usado para empacar artículos de uso doméstico y personales.', NULL),
('XLZ', 'Registros  con fleje/ agrupados/ armados', NULL, NULL),
('XMA', 'Cajón metálico', 'Caja de contención hecha de metal para retener sustancias o artículos.', NULL),
('XMB', 'Múltiplo de bolsas', NULL, NULL),
('XMC', 'Cajón para leche', NULL, NULL),
('XME', 'Contenedor de metal', 'Tipo de caja de contención hecha de metal para retener sustancias o artículos, no especificado de otro modo como equipo de transporte.', NULL),
('XMR', 'Recipiente de metal', 'Recipiente de contención de metal para retener sustancias o artículos.', NULL),
('XMS', 'Saco milti-pared', NULL, NULL),
('XMT', 'Tapete', NULL, NULL),
('XMW', 'Contenedor envuelto en plástico', 'Recipiente de contención envuelto en plástico para retener sustancias o artículos.', NULL),
('XMX', 'Caja pequeña de cerillos', NULL, NULL),
('XNA', 'No disponible', NULL, NULL),
('XNE', 'Sin empaque o no empaquetado', NULL, NULL),
('XNF', 'Sin empaque o no empaquetado, unidad simple', NULL, NULL),
('XNG', 'Sin empaque o no empaquetado, unidades múltiples', NULL, NULL),
('XNS', 'Caja nido', NULL, NULL),
('XNT', 'Red', NULL, NULL),
('XNU', 'Red de plástico con tubo', NULL, NULL),
('XNV', 'Red textil con tubo', NULL, NULL),
('XOA', 'Pallet, Según la clasificación de la compañía (Commonwealth Handling Equipment Pool (CHEP) 40 cm x 60 cm', 'Pallet de dimensiones 40 centímetros x 60 centímetros.', NULL),
('XOB', 'Pallet, Según la clasificación de la compañía (Commonwealth Handling Equipment Pool (CHEP) 80 cm x 120 cm', 'Pallet de dimensiones 80 centímetros x 120 centímetros.', NULL),
('XOC', 'Pallet, Según la clasificación de la compañía (Commonwealth Handling Equipment Pool (CHEP) 100 cm x 120 cm', 'Pallet de dimensiones 100 centímetros x 120 centímetros.', NULL),
('XOD', 'Pallet, AS 4068-1993', 'Pallet con  estándar australiano de dimensiones 115.5 centímetros x 116.5 centímetros.', NULL),
('XOE', 'Pallet, ISO T11', 'Pallet con estándar ISO de dimensiones 110 centímetros x 110 centímetros, prevalente en la región Asia-Pacífico.', NULL),
('XOF', 'Plataforma, peso o dimensión no especificada', 'Plataforma de carga equivalente del Pallet de dimensiones desconocidas o peso desconocido.', NULL),
('XOK', 'Bloque', 'Una pieza sólida de una sustancia dura, tal como granito, que tiene uno o más lados planos.', NULL),
('XOT', 'Octabin', 'Envase estándar de cartón de grandes dimensiones para almacenar por ejemplo verduras, gránulos de plástico u otros productos secos.', NULL),
('XP2', 'Charola', 'Recipiente ancho y abierto, usualmente de metal.', NULL),
('XPA', 'Cajetilla', 'Paquete pequeño.', NULL),
('XPB', 'Pallet, Caja combinada y abierta con caja y pallet.', NULL, NULL),
('XPC', 'Paquete postal', NULL, NULL),
('XPD', 'Pallet modular con collares (80cms * 100cms)', 'Pallet tamaño estándar de dimensiones 80 centímetros por 100 centímetros (cms).', NULL),
('XPE', 'Pallet modular con collares (80cms * 120cms)', 'Pallet tamaño estándar de dimensiones 80 centímetros por 120 centímetros (cms).', NULL),
('XPF', 'Corral', 'Pequeño recinto abierto para retener animales.', NULL),
('XPG', 'Placa', NULL, NULL),
('XPH', 'Cantaro', NULL, NULL),
('XPI', 'Pleca', NULL, NULL),
('XPJ', 'Canastilla', NULL, NULL),
('XPK', 'Paquete', 'Unidad de empaque estándar.', NULL),
('XPL', 'Balde', NULL, NULL),
('XPN', 'Tablón', NULL, NULL),
('XPO', 'Bolsa pequeña', NULL, NULL),
('XPR', 'Contenedor de plástico', 'Recipiente de contención de plástico para retener sustancias o artículos.', NULL),
('XPT', 'Maceta', NULL, NULL),
('XPU', 'Cacerola', NULL, NULL),
('XPV', 'Tubos, con fleje/ agrupados/ armados', NULL, NULL),
('XPX', 'Pallet', 'Plataforma o caja abierta, generalmente de madera, en la que se conservan las mercancías para facilitar el manejo mecánico durante el transporte y almacenamiento.', NULL),
('XPY', 'Placas con fleje/ agrupados/ armados', NULL, NULL),
('XPZ', 'Tablones con fleje/ agrupados/ armados', NULL, NULL),
('XQA', 'Tambor de acero con cabeza no desmontable', NULL, NULL),
('XQB', 'Tambor de  acero con cabeza extraíble', NULL, NULL),
('XQC', 'Tambor de aluminio con cabeza no extraíble', NULL, NULL),
('XQD', 'Tambor de aluminio con cabeza extraíble', NULL, NULL),
('XQF', 'Tambor, plástico con cabeza no desmontable', NULL, NULL),
('XQG', 'Tambor, plástico, cabeza extraíble', NULL, NULL),
('XQH', 'Barril de madera con tapón', NULL, NULL),
('XQJ', 'Barril de madera con cabeza desprendible', NULL, NULL),
('XQK', 'Bidón de acero con cabeza no desmontable', NULL, NULL),
('XQL', 'Bidón de acero con cabeza desmontable', NULL, NULL),
('XQM', 'Bidón de plástico con cabeza no desmontable', NULL, NULL),
('XQN', 'Bidón de plástico con cabeza extraíble', NULL, NULL),
('XQP', 'Caja de madera natural estándar', NULL, NULL),
('XQQ', 'Caja de madera natural con muros a prueba de filtraciones', NULL, NULL),
('XQR', 'Caja de plástico expandida', NULL, NULL),
('XQS', 'Caja de plástico sólida', NULL, NULL),
('XRD', 'Rod', NULL, NULL),
('XRG', 'Anillo', NULL, NULL),
('XRJ', 'Estante, Perchero para ropa', NULL, NULL),
('XRK', 'Estante', NULL, NULL),
('XRL', 'Carrete', 'Dispositivo giratorio cilíndrico con un reborde en cada extremo en el que se enrollan los materiales.', NULL),
('XRO', 'Rollo', NULL, NULL),
('XRT', 'Red Roja', 'Material de confinamiento hecho de redes de malla roja para retener artículos (por ejemplo árboles).', NULL),
('XRZ', 'Varillas  con fleje/ agrupados/ armados', NULL, NULL),
('XSA', 'Saco', NULL, NULL),
('XSB', 'Losa', NULL, NULL),
('XSC', 'Cajón poco profundo', NULL, NULL),
('XSD', 'Huso', NULL, NULL),
('XSE', 'Baúl', NULL, NULL),
('XSH', 'Bolsa pequeña hermética', NULL, NULL),
('XSI', 'Patín', 'Una plataforma o plataforma móvil baja para facilitar el manejo y transporte de mercancías.', NULL),
('XSK', 'Carcasa esqueleto', NULL, NULL),
('XSL', 'Hoja de deslizamiento', 'Láminas de plástico duro se utilizan principalmente como la base sobre la cual apilan mercancías para optimizar el espacio dentro de un contenedor. Puede utilizarse como alternativa a un embalaje paletizado.', NULL),
('XSM', 'Hoja de metal', NULL, NULL),
('XSO', 'Carrete pequeño', 'Contenedor de empaque utilizado en el transporte de artículos tales como alambre, cable, cinta e hilo.', NULL),
('XSP', 'Hoja de empaque de plástico', NULL, NULL),
('XSS', 'Cajón de acero', NULL, NULL),
('XSU', 'Maleta', NULL, NULL),
('XSV', 'Sobre de acero', NULL, NULL),
('XSW', 'Envoltorio', 'Mercancías retenidas en una película de plástico transparente que ha sido envuelta alrededor y luego encogido fuertemente a las mercancías.', NULL),
('XSY', 'Manga', NULL, NULL),
('XSZ', 'Hojas  con fleje/ agrupados/ armados', NULL, NULL),
('XT1', 'Tableta', 'Artículo suelto o sin empaque en forma de barra, bloque o pieza.', NULL),
('XTB', 'Tina', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();