INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('A64', 'Erg por segundo centímetro cuadrado', NULL, 'Erg / (s · cm²)'),
('A65', 'Erg por centímetro cuadrado segundo', NULL, 'Erg / (cm² · s)'),
('A66', 'Erg centímetro cuadrado', NULL, 'Erg · cm²'),
('A67', 'Erg centímetro cuadrado por gramo', NULL, 'Erg · cm² / g'),
('A68', 'Exajoule', NULL, 'EJ'),
('A69', 'Faradio por metro', NULL, 'F/m'),
('A7', 'Amperio por milímetro cuadrado', NULL, 'A/mm²'),
('A70', 'Femtojoule', NULL, 'fJ'),
('A71', 'Femtómetro', 'Es la unidad de longitud que equivale a una milbillónesima parte del metro.', 'fm'),
('A73', 'Pie por segundo al cuadrado', NULL, 'ft/s²'),
('A74', 'Pie libra-fuerza por segundo', NULL, 'ft·lbf/s'),
('A75', 'Tonelada de carga', 'Unidad de información que normalmente se utiliza para la facturación, que se define como sea el número de toneladas métricas o el número de metros cúbicos, lo que sea mayor.', NULL),
('A76', 'Galón', 'Es una unidad de volumen que se emplea en los países anglófonos (especialmente Estados Unidos) o con influencia de estos (como Liberia, Guatemala, Panamá, Honduras, Nicaragua, El Salvador, Colombia y parcialmente en México), para medir volúmenes de líquidos, principalmente la gasolina y su precio. Antiguamente, el volumen de un galón dependía de lo que se midiera, y dónde. Sin embargo, en el siglo XIX existían dos definiciones de uso común: "galón de vino" (wine gallon) y "galón de cerveza británico" (ale gallon).', 'Gal'),
('A77', 'Gaussian CGS (Centímetro-Gram-Segundo sistema) unidad de desplazamiento', NULL, NULL),
('A78', 'Gaussiano CGS (Centímetro-Gram-Segundo sistema) unidad de corriente eléctrica', NULL, NULL),
('A79', 'Gaussian CGS (Centímetro-Gram-Segundo sistema) unidad de carga eléctrica', NULL, NULL),
('A8', 'Amperio segundo', NULL, 'A·s'),
('A80', 'Gaussiano CGS (Centímetro-Gram-Segundo sistema) unidad de la fuerza del campo eléctrico', NULL, NULL),
('A81', 'Gaussian CGS (Centímetro-Gram-Segundo sistema) unidad de polarización eléctrica', NULL, NULL),
('A82', 'Gaussiano CGS (Centímetro-Gram-Segundo sistema) unidad de potencial eléctrico', NULL, NULL),
('A83', 'Gaussian CGS (Centímetro-Gram-Segundo sistema) unidad de magnetización', NULL, NULL),
('A84', 'GigaCulombio por metro cúbico', NULL, 'GC/m³'),
('A85', 'Gigaelectrónvoltio', NULL, 'GeV'),
('A86', 'Gigahertz', 'Es un múltiplo de la unidad de medida de frecuencia hercio (Hz) y equivale a 109 (1 000 000 000) Hz. Por lo tanto, tiene un período de oscilación de 1 nanosegundo. Las ondas de radio con frecuencias cercanas al gigahercio se denominan microondas.', 'GHz'),
('A87', 'GigaOhm', NULL, 'GΩ'),
('A88', 'GigaOhm metro', NULL, 'GΩ·m'),
('A89', 'Gigapascal', NULL, 'GPa'),
('A9', 'Tarífa', 'Unidad de cantidad expresada como una tasa para el uso de una instalación o servicio.', NULL),
('A90', 'Gigawatt', NULL, 'GW'),
('A91', 'Grado centesimal', 'Sinónimo: grado
El grado centesimal o gon —también llamado gradián (plural: gradianes) y gonio — es una unidad de medida de ángulos planos, alternativa al grado sexagesimal y al radián.', 'gon'),
('A93', 'Gramo por metro cúbico', NULL, 'g/m³'),
('A94', 'Gramo por Mol', NULL, 'g/mol'),
('A95', 'Gray', 'Es una unidad derivada del Sistema Internacional de Unidades que mide la dosis absorbida de radiaciones ionizantes por un determinado material. Un Gray es equivalente a la absorción de un julio de energía ionizante por un kilogramo de material irradiado.', 'Gy'),
('A96', 'Gray por segundo', NULL, 'Gy/s'),
('A97', 'Hectopascal', NULL, 'hPa'),
('A98', 'Henry por metro', NULL, 'H/m'),
('A99', 'Bit', 'Unidad de información igual a un dígito binario.', 'bit'),
('AA', 'Balón', 'Unidad de recuento para definir el número de bolas (Balón: objeto formado en la forma de esfera).', NULL),
('AB', 'Paquete a granel', 'Unidad de recuento para definir el número de artículos por paquete a granel.', 'pk'),
('ACR', 'Acre', 'Es una medida de superficie, usada en agricultura en varios países.', 'acre'),
('ACT', 'Actividad', 'Unidad de recuento para definir el número de actividades (actividad: una unidad de trabajo o acción).', NULL),
('AD', 'Byte', 'Unidad de información igual a 8 bits.', 'byte'),
('AE', 'Amperio por metro', '(a veces llamado amperio vuelta por metro) es la unidad SI de la corriente de campo magnético.', 'A/m'),
('AH', 'Minuto adicional', 'Unidad de tiempo que define el número de minutos, además de los minutos referenciados.', NULL),
('AI', 'Minuto y medio por llamada', 'Unidad de recuento para definir el número de minutos para el intervalo medio de una llamada.', NULL),
('AJ', 'policía', NULL, NULL),
('AK', 'Braza', 'Una braza es una unidad de longitud náutica, usada generalmente para medir la profundidad del agua. Se llama braza porque equivale a la longitud de un par de brazos extendidos, aproximadamente dos metros, ó 6 pies en el sistema de medición estadounidense. Actualmente es considerada arcaica e imprecisa.', 'fth'),
('AL', 'Línea de acceso', 'Unidad de recuento para definir el número de líneas de acceso telefónico.', NULL),
('AMH', 'Amperio hora', 'Unidad de carga electrica definida por la cantidad de carga acumulada por un flujo constante de un amperio por 1 hora.', 'A·h'),
('AMP', 'Amperio', 'Es la intensidad de una corriente constante que manteniéndose en dos conductores paralelos, rectilíneos, de longitud infinita, de sección circular despreciable y situados a una distancia de un metro uno de otro en el vacío, produciría una fuerza igual a 2·10-7 newton por metro de longitud.', 'A'),
('ANN', 'Año', 'Unidad de tiempo equivalente a 365.25 días.', 'y'),
('AP', 'Libra de aluminio solamente', NULL, NULL),
('APZ', 'Onza troy u onza farmacéutica', NULL, 'tr oz'),
('AQ', 'Unidad del factir anti-hemofilico.', 'Unidad de medida para la potencia de la sangre (US).', NULL),
('AR', 'supositorio', NULL, NULL),
('ARE', 'Are', 'Sinónimo: decametro cuadrado', 'un'),
('AS', 'Variedad', 'Unidad de recuento para definir el número de surtidos (variedad: conjunto de elementos agrupados en una colección mixta).', NULL),
('ASM', 'Grado alcohólico en masa', 'Unidad de masa que define el grado alcohólico de un líquido.', NULL),
('ASU', 'Grado alcohólico volumétrico', 'Unidad de volumen que define el grado alcohólico de un líquido (por ejemplo, alcohol, vino, cerveza, etc.), a menudo a una temperatura específica.', NULL),
('ATM', 'Atmósfera estándar', 'Es un modelo de la atmósfera terrestre que permite obtener los valores de presión, temperatura, densidad y viscosidad del aire en función de la altitud. Su función es proporcionar un marco de referencia invariante para la navegación aérea y para la realización de cálculos aerodinámicos consistentes.', 'atm'),
('ATT', 'Atmósfera técnica', NULL, 'a'),
('AW', 'Relleno de polvo en viales', NULL, NULL),
('AWG', 'Calibre de alambre americano', 'También conocido como el calibre del cable Brown & Sharpe , es un estandarizado calibre del cable sistema utilizado desde 1857 predominantemente en Norteamérica para los diámetros de vuelta, no ferroso,, sólido eléctricamente conductor de alambre.', 'AWG'),
('AY', 'Montaje', 'Una unidad de recuento de definir el número de conjuntos (montaje: artículos que consisten de partes componentes).', NULL),
('AZ', 'Unidad térmica británica (tabla internacional) por libra', NULL, 'BtuIT/lb'),
('B0', 'Btu por pie cúbico', NULL, 'BTU / ft³'),
('B1', 'Barril (EUA) por día', NULL, 'barrel (US)/d'),
('B10', 'Bits por segundo', 'Unidad de información igual a un dígito binario por segundo.', 'bit/s'),
('B11', 'Joule por kilogramo kelvin', 'Es la capacidad térmica másica de un cuerpo homogéneo de una masa de 1 kilogramo, en el que el aporte de una cantidad de calor de un joule, produce una elevación de temperatura termodinámica de 1 kelvin.', 'J/(kg·K)'),
('B12', 'Joule por metro', NULL, 'J/m'),
('B13', 'Joule por metro cuadrado', 'Sinónimo: joule por metro cuadrado', 'J/m²'),
('B14', 'Joule por metro a la cuarta potencia', NULL, 'J/m⁴'),
('B15', 'Juole por Mol', NULL, 'J/mol'),
('B16', 'Juoule por Mol kelvin', NULL, 'J/(mol·K)'),
('B17', 'Crédito', 'Unidad de recuento de definir el número de entradas realizadas en el haber de una cuenta.', NULL),
('B18', 'Segundos joule', NULL, 'J·s'),
('B19', 'Dígito', 'Unidad de información que define la cantidad de números utiliza para formar un número.', NULL),
('B2', 'litera', NULL, NULL),
('B20', 'Joule metro cuadrado por kologramo', NULL, 'J·m²/kg'),
('B21', 'Kelvin por watt', NULL, 'K/W'),
('B22', 'Kiloamperio', NULL, 'kA'),
('B23', 'Kiloamperio por metro cuadrado', NULL, 'kA/m²'),
('B24', 'Kiloamperio por metro', NULL, 'kA/m'),
('B25', 'Kilobecquerel por metrocúbico', NULL, 'kBq/kg'),
('B26', 'KiloCulombio', NULL, 'kC'),
('B27', 'KiloCulombio por metro cúbico', NULL, 'kC/m³'),
('B28', 'KiloCulombio por metro cuadrado', NULL, 'kC/m²'),
('B29', 'Kiloelectrónvoltio', NULL, 'keV'),
('B3', 'Libra de bateo', 'Unidad de masa que define el número de libras de fibra acolchada.', NULL),
('B30', 'Gibibit', 'Unidad de información igual a 2³⁰ los bits (dígitos binarios).', 'Gibit'),
('B31', 'Kilogramo metro por segundo', NULL, 'kg·m/s'),
('B32', 'Kilogramo metro cuadrado', NULL, 'kg·m²'),
('B33', 'Kilogramo metro cuadrado por segundo', NULL, 'kg·m²/s'),
('B34', 'Kilogramo por decímetro cúbico', NULL, 'kg/dm³'),
('B35', 'Kilogramo por litro', NULL, 'kg/l or kg/L'),
('B36', 'Calorías (termoquímicas) por gramo', NULL, 'cal th / g'),
('B37', 'Kilogramo de fuerza', NULL, 'Kgf'),
('B38', 'Kilogramo-metro de la fuerza', NULL, 'Kgf · m'),
('B39', 'Kilogramo-fuerza del metro por segundo', NULL, 'Kgf · m / s'),
('B4', 'Barril, unidad imperial', 'Unidad de volumen utilizado para medir cerveza. Un barril de cerveza es igual a 36 galones imperiales.', NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();