INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('F67', 'Kilogramo por hora bar', NULL, 'kg/(h·bar)'),
('F68', 'Kilogramo por minuto bar', NULL, 'kg/(min·bar)'),
('F69', 'Kilogramo por segundo bar', NULL, 'kg/(s·bar)'),
('F70', 'Miligramo por día bar', NULL, 'mg/(d·bar)'),
('F71', 'Miligramo por hora bar', NULL, 'mg/(h·bar)'),
('F72', 'Miligramo por minuto bar', NULL, 'mg/(min·bar)'),
('F73', 'Miligramo por segundo bar', NULL, 'mg/(s·bar)'),
('F74', 'Gramo por bar', NULL, 'g/bar'),
('F75', 'Miligramo por bar', NULL, 'mg/bar'),
('F76', 'Miliamperio por milímetro', NULL, 'mA/mm'),
('F77', 'Pascal segundo por kelvin', NULL, 'Pa.s/K'),
('F78', 'Pulgada de agua', NULL, 'inH₂O'),
('F79', 'Pulgada de mercurio', NULL, 'inHg'),
('F80', 'Caballos de fuerza de agua', 'Define la cantidad de potencia requerida para mover un volumen dado de agua contra la aceleración de la gravedad a una elevación especificada (cabezal de presión).', NULL),
('F81', 'Bar por kelvin', NULL, 'bar/K'),
('F82', 'Hectopascal por kelvin', NULL, 'hPa/K'),
('F83', 'Kilopascal por kelvin', NULL, 'kPa/K'),
('F84', 'Milibar por kelvin', NULL, 'mbar/K'),
('F85', 'Megapascal por kelvin', NULL, 'MPa/K'),
('F86', 'Poise por kelvin', NULL, 'P/K'),
('F87', 'Voltio por litro minuto', NULL, 'V/(l·min)'),
('F88', 'Newton centímetro', NULL, 'N·cm'),
('F89', 'Newton metro por grados', NULL, 'Nm/°'),
('F9', 'Fibra por centímetro cúbico de aire', NULL, NULL),
('F90', 'Newton metro por amperio', NULL, 'N·m/A'),
('F91', 'Bar litro por segundo', NULL, 'bar·l/s'),
('F92', 'Bar metro cúbico por segundo', NULL, 'bar·m³/s'),
('F93', 'Hectopascal litro por segundo', NULL, 'hPa·l/s'),
('F94', 'Hectopascal metro cúbico por segundo', NULL, 'hPa·m³/s'),
('F95', 'Milibar litro por segundo', NULL, 'mbar·l/s'),
('F96', 'Milibar metro cúbico por segundo', NULL, 'mbar·m³/s'),
('F97', 'Megapascal litro por segundo', NULL, 'MPa·l/s'),
('F98', 'Megapascal metro cúbico por segundo', NULL, 'MPa·m³/s'),
('F99', 'Pascal litro por segundo', NULL, 'Pa·l/s'),
('FAH', 'Grado fahrenheit', 'Consulte ISO 80000-5 (Cantidades y unidades - Parte 5: Termodinámica)', '°F'),
('FAR', 'Farad', 'Es la capacidad de un condensador eléctrico que entre sus armaduras aparece una diferencia de potencial eléctrico de 1 volt, cuando está cargado con una cantidad de electricidad igual a 1 coulomb.', 'F'),
('FB', 'campo', NULL, NULL),
('FBM', 'Medidor de fibra', 'Unidad de longitud que define el número de metros de fibra individual.', NULL),
('FC', 'Mil pies cúbicos', 'Unidad de volumen igual a mil pies cúbicos.', 'kft³'),
('FD', 'Millones de partículas por pie cúbico', NULL, NULL),
('FE', 'Pie de pista', NULL, NULL),
('FF', 'Cien metros cúbicos', 'Unidad de volumen igual a cien metros cúbicos.', NULL),
('FG', 'Parche transdérmico', NULL, NULL),
('FH', 'MicroMol', NULL, 'µmol'),
('FIT', 'Fallas en el tiempo', 'Unidad de conteo que define el número de fallos que se pueden esperar en un intervalo de tiempo especificado. Las tasas de fallo de los componentes semiconductores se especifican a menudo como FIT (fallas en la unidad de tiempo) donde 1 FIT = 10?? / h.', 'FIT'),
('FL', 'Flake ton', 'Unidad de masa que define el número de toneladas de una sustancia en copos (escamas: un pequeño fragmento plano).', NULL),
('FM', 'Millones de pies cúbicos', NULL, 'Mft³'),
('FOT', 'Pie', 'Unidad de medida empleada por aeronautas, equivale a 30.48 cm', 'ft'),
('FP', 'Libra por pie cuadrado', NULL, 'lb/ft²'),
('FR', 'Pie por minuto', NULL, 'ft/min'),
('FS', 'Pie por segundo', NULL, 'ft/s'),
('FTK', 'Pie cuadrado', 'Es una unidad de superficie del sistema anglosajón de unidades, equivalente a un cuadrado de un pie de lado.', 'ft²'),
('FTQ', 'Pie cúbico', NULL, 'ft³'),
('G01', 'Pascal metro cúbico por segundo', NULL, 'Pa·m³/s'),
('G04', 'Centímetro por bar', NULL, 'cm/bar'),
('G05', 'Metro por bar', NULL, 'm/bar'),
('G06', 'Milímetro por bar', NULL, 'mm/bar'),
('G08', 'Pulgada cuadrada por segundo', NULL, 'in²/s'),
('G09', 'Metro cuadrado por segundo kelvin', NULL, 'm²/(s·K)'),
('G10', 'Stokes por kelvin', NULL, 'St/K'),
('G11', 'Gramo por centímetro cúbico bar', NULL, 'g/(cm³·bar)'),
('G12', 'Gramo por decímetro cúbico bar', NULL, 'g/(dm³·bar)'),
('G13', 'Gramo por litro bar', NULL, 'g/(l·bar)'),
('G14', 'Gramo por metro cúbico bar', NULL, 'g/(m³·bar)'),
('G15', 'Gramo por mililitro bar', NULL, 'g/(ml·bar)'),
('G16', 'Kilogramo por centímetro cúbico bar', NULL, 'kg/(cm³·bar)'),
('G17', 'Kilogramo por litro bar', NULL, 'kg/(l·bar)'),
('G18', 'Kilogramo por metro cúbico bar', NULL, 'kg/(m³·bar)'),
('G19', 'Newton metro por kilogramo', NULL, 'N·m/kg'),
('G2', 'Galón (EUA) por minuto', NULL, 'gal (US) /min'),
('G20', 'Libra-fuerza pie por libra', NULL, 'lbf·ft/lb'),
('G21', 'Taza (unidad de volumen)', NULL, 'cup (US)'),
('G23', 'Peck', 'Es una unidad de medida imperial y habitual en  Estados Unidos de volumen seco.', 'pk (US)'),
('G24', 'Cucharada (estados unidos)', '1/2 onzas fluidas, 3 cucharaditas, 15 mililitros', 'tablespoon (US)'),
('G25', 'Cucharilla (estados unidos)', '1/6 onzas fluidas o 5 mililitros', 'teaspoon (US)'),
('G26', 'Estere', NULL, 'st'),
('G27', 'Centímetro cúbico por kelvin', NULL, 'cm³/K'),
('G28', 'Litro por kelvin', NULL, 'l/K'),
('G29', 'Metro cúbico por kelvin', NULL, 'm³/K'),
('G3', 'Galón (RU) por minuto', NULL, 'gal (UK) /min'),
('G30', 'Mililitro por klevin', NULL, 'ml/K'),
('G31', 'Kilogramo por centímetro cúbico', NULL, 'kg/cm³'),
('G32', 'Onza (avoirdupois) por yarda cúbica', NULL, 'oz/yd³'),
('G33', 'Gramo por centímetro cúbico kelvin', NULL, 'g/(cm³·K)'),
('G34', 'Gramo por decímetro cúbico kelvin', NULL, 'g/(dm³·K)'),
('G35', 'Gramo por litro kelvin', NULL, 'g/(l·K)'),
('G36', 'Gramo por metro cúbico kelvin', NULL, 'g/(m³·K)'),
('G37', 'Gramo por mililitro kelvin', NULL, 'g/(ml·K)'),
('G38', 'Kilogramo por centímetro cúbico kelvin', NULL, 'kg/(cm³·K)'),
('G39', 'Kilogramo por litro kelvin', NULL, 'kg/(l·K)'),
('G40', 'Kilogramo por metro cúbico kelvin', NULL, 'kg/(m³·K)'),
('G41', 'Metro cuadrado por segundo bar', NULL, 'm²/(s·bar)'),
('G42', 'Microsiemens por centímetro', NULL, 'µS/cm'),
('G43', 'Microsiemens por metro', NULL, 'µS/m'),
('G44', 'Nanosiemens por centímetro', NULL, 'nS/cm'),
('G45', 'Nanosiemens por metro', NULL, 'nS/m'),
('G46', 'Stokes por bar', NULL, 'St/bar'),
('G47', 'Centímetro cúbico por día', NULL, 'cm³/d'),
('G48', 'Centímetro cúbico por hora', NULL, 'cm³/h'),
('G49', 'Centímetro cúbico por minuto', NULL, 'cm³/min')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();