INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('4E', 'Veinte pack', NULL, NULL),
('4G', 'Microlitro', NULL, 'µl'),
('4H', 'Micra', 'El micrómetro, micrón o micra es una unidad de longitud equivalente a una milésima parte de un milímetro.', 'µm'),
('4K', 'Miliamperio', NULL, 'mA'),
('4L', 'Megabyte', 'Unidad que se usa para cuantificar un caudal de datos equivalente a 1000 kb/s.', 'Mbyte'),
('4M', 'Miligramo por hora', NULL, 'mg/h'),
('4N', 'Megabequerel', NULL, 'MBq'),
('4O', 'Microfaradio', NULL, 'µF'),
('4P', 'Newton por metro', NULL, 'N/m'),
('4Q', 'Onza pulgada', NULL, 'oz·in'),
('4R', 'Onza pie', NULL, 'oz·ft'),
('4T', 'Picofaradio', NULL, 'pF'),
('4U', 'Libra por hora', NULL, 'lb/h'),
('4W', 'Tonelada (EUA) por hora', NULL, 'ton (US) /h'),
('4X', 'Kilolitro por hora', NULL, 'kl/h'),
('56', 'Sitas', 'Unidad de área de placa de estaño igual a un área de superficie de 100 metros cuadrados.', NULL),
('57', 'Malla', 'Una unidad de recuento de definir el número de hebras por pulgada como una medida de la finura de un producto tejido.', NULL),
('58', 'kilogramo neto', 'Unidad de masa que define el número total de kilogramos después de las deducciones.', NULL),
('59', 'Parte por millón', 'Una unidad de proporción igual a 10⁻⁶.', 'ppm'),
('5A', 'Barril por minuto', NULL, 'barrel (US)/min'),
('5B', 'Batch', 'Unidad de conteo que define el número de lotes (lote: cantidad de material producido en una operación o número de animales o personas que vienen a la vez).', NULL),
('5C', 'Galón (US) por mil', NULL, NULL),
('5E', 'Mmscf/day', 'Unidad de volumen equivalente a un millón (1,000,000) pies cúbicos de gas por día.', NULL),
('5F', 'Libra por mil', NULL, NULL),
('5G', 'bomba', NULL, NULL),
('5H', 'Escenario', NULL, NULL),
('5I', 'Pies cúbicos estándar', 'Utilice estándar (código común WSD)', 'Std'),
('5J', 'Caballos de potencia hidráulica', 'Unidad de potencia de la definición de los caballos de potencia hidráulica suministrada por una bomba de fluido dependiendo de la viscosidad del fluido.', NULL),
('5K', 'Contar por minuto', NULL, NULL),
('5P', 'Nivel sísmico', NULL, NULL),
('5Q', 'Línea sísmica', NULL, NULL),
('60', 'Tanto por ciento en peso', 'Una unidad de proporción igual a 10⁻².', NULL),
('61', 'Parte por mil millones (EUA)', 'Una unidad de proporción igual a 10⁻⁹.', 'ppb'),
('74', 'Milipascal', NULL, 'mPa'),
('77', 'Mili-pulgada', NULL, 'mil'),
('80', 'Libra por pulgada cuadrado absoluta', NULL, 'lb/in²'),
('81', 'Henry', 'Un henry es la unidad para la inductancia eléctrica en el Sistema Internacional de Unidades. Es la inductancia eléctrica de un circuito cerrado en el que se produce una fuerza electromotriz de 1 voltio, cuando la corriente eléctrica que recorre el circuito varía uniformemente a razón de un amperio por segundo.', 'H'),
('85', 'Pie libra-fuerza', NULL, 'ft·lbf'),
('87', 'Libra por pie cúbico', NULL, 'lb/ft³'),
('89', 'Poise', 'El poise (símbolo: P) es la unidad de viscosidad dinámica del sistema cegesimal de unidades.', 'P'),
('91', 'Stokes', 'El Stokes es la unidad de viscosidad cinemática en el Sistema Cegesimal de Unidades', 'St'),
('A1', '15 ° C calorías', NULL, 'Cal $ _ $'),
('A10', 'Amperio por metro cuadrado por joule segundo', NULL, 'A·m²/(J·s)'),
('A11', 'Ángstrom', 'El ángstrom es una unidad de longitud empleada principalmente para expresar longitudes de onda, distancias moleculares y atómicas, etc.', 'Å'),
('A12', 'Unidad astronómica', 'Es una unidad de longitud igual por definición a 149 597 870 700 metros, y que equivale aproximadamente a la distancia media entre el planeta Tierra y el Sol.', 'ua'),
('A13', 'Attojoule', 'Una unidad SI de la energía, el trabajo, y el calor igual a 10 -18 joules', 'aJ'),
('A14', 'Barn', 'Es una unidad de superficie, equivalente a 10-28 m² (100 femtómetros cuadrados). Sus múltiplos son muy utilizados en física de partículas para medir las secciones eficaces en reacciones nucleares, y sus inversos para medir luminosidades.', 'b'),
('A15', 'Barn por electrovoltio', NULL, 'b/eV'),
('A16', 'Barn por electrovoltio', NULL, 'b/(sr·eV)'),
('A17', 'Barn por esteroradian', NULL, 'b/sr'),
('A18', 'Becquerel por kilogramo', NULL, 'Bq/kg'),
('A19', 'Becquerel por metro cúbico', NULL, 'Bq/m³'),
('A2', 'Amperio por centímetro', NULL, 'A/cm'),
('A20', 'Unidad térmica británica (tabla internacional) por segundo pie cuadrado grado rankine.', NULL, 'BtuIT/(s·ft²·°R)'),
('A21', 'Unidad térmica británica (tabla internacional) por libra grado rankine', NULL, 'Btu/IT(lb·°R)'),
('A22', 'Unidad térmica británica (tabla internacional) por segundo pie grado rankine', NULL, 'BtuIT/(s·ft·°R)'),
('A23', 'Unidad térmica británica (tabla internacional) por hora pie cuadrado grado rankine.', NULL, 'BtuIT/(h·ft²·°R)'),
('A24', 'Candela por metro cuadrado', NULL, 'cd/m²'),
('A25', 'Caballo de vapor', 'Sinónimo: Caballo de fuerza métrico', 'CV'),
('A26', 'Culombio metro', NULL, 'C·m'),
('A27', 'Culombio metro cuadrado por voltio', NULL, 'C·m²/V'),
('A28', 'Culombio por centímetro cúbico', NULL, 'C/cm³'),
('A29', 'Culombio por metro cúbico', NULL, 'C/m³'),
('A3', 'Amperio por milímetro', NULL, 'A/mm'),
('A30', 'Culombio por milimetro cúbico', NULL, 'C/mm³'),
('A31', 'Culombio por kilogramo-segundo', NULL, 'C/(kg·s)'),
('A32', 'Culombio por Mol', NULL, 'C/mol'),
('A33', 'Culombio por centímetro cuadrado', NULL, 'C/cm²'),
('A34', 'Culombio por metro cuadrado', NULL, 'C/m²'),
('A35', 'Culombio por milímetro cuadrado', NULL, 'C/mm²'),
('A36', 'Centimetro cúbico por Mol', NULL, 'cm³/mol'),
('A37', 'Decimetro cuadrado por Mol', NULL, 'dm³/mol'),
('A38', 'Cubic pooulo p', NULL, 'm³/C'),
('A39', 'Metro cúbico por kilogramo', NULL, 'm³/kg'),
('A4', 'Amperio por centímetro cuadrado', NULL, 'A/cm²'),
('A40', 'Metro cubbico por Mol', NULL, 'm³/mol'),
('A41', 'Amperio por metro cuadrado', NULL, 'A/m²'),
('A42', 'Curie por kilogramo', NULL, 'Ci/kg'),
('A43', 'Tonelaje de peso muerto', 'Unidad de masa que define la diferencia entre el peso de un barco cuando está completamente vacío y su peso cuando está completamente cargado, expresado como el número de toneladas.', 'dwt'),
('A44', 'Decalitro', NULL, 'dal'),
('A45', 'Decámetro', 'Medida de longitud, de símbolo dam o Dm, que es igual a 10 metros.', 'dam'),
('A47', 'Decitex', 'Unidad de densidad de hilo. Un decitex es igual a una masa de 1 gramo por 10 kilómetros de longitud.', 'dtex (g/10km)'),
('A48', 'Grado rankine', 'Consulte ISO 80000-5 (Cantidades y unidades - Parte 5: Termodinámica)', '°R'),
('A49', 'Negador', 'Unidad de densidad de hilo. Una denier es igual a una masa de 1 gramo por 9 kilómetros de longitud.', 'den (g/9 km)'),
('A5', 'Amperio metro cuadrado', NULL, 'A·m²'),
('A50', 'Dina segundo por centímetro cúbico', NULL, 'Dyn · s / cm³'),
('A51', 'Dina segundo por centímetro', NULL, 'Dyn · s / cm'),
('A52', 'Dina segundo por centímetro a la quinta potencia', NULL, 'Dyn · s / cm⁵'),
('A53', 'Electrónvoltio', NULL, 'eV'),
('A54', 'Electrovoltio por metro', NULL, 'eV/m'),
('A55', 'Electrovoltio por metro cuadrado', NULL, 'eV·m²'),
('A56', 'Electrovoltio metro cuadrado por kilogramo', NULL, 'eV·m²/kg'),
('A57', 'Ergio', NULL, 'ergio'),
('A58', 'Erg por centímetro', NULL, 'Erg / cm'),
('A59', 'La cobertura de nubes 8-parte', 'Unidad de recuento para definir el número de octavos de partes como una medida de la cobertura de nubes de la ccúpula celeste. 

''Sinónimo: OKTA, OCTA', NULL),
('A6', 'Amperio por metro cuadrado Kelvin cuadrado', NULL, 'A/(m²·K²)'),
('A60', 'Erg por centímetro cúbico', NULL, 'Erg / cm³'),
('A61', 'Erg por gramo', NULL, 'Erg / g'),
('A62', 'Erg por segundo gramo', NULL, 'Erg / g · s'),
('A63', 'Erg por segundo', NULL, 'Ergs')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();