INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol) VALUES 
('B41', 'Kilojoule por kelvin', NULL, 'kJ/K'),
('B42', 'Kilojoule por kilogramo', NULL, 'kJ/kg'),
('B43', 'Kilojoule por kilogramo kelvin', NULL, 'kJ/(kg·K)'),
('B44', 'Kilojoule por Mol', NULL, 'kJ/mol'),
('B45', 'KiloMol', NULL, 'kmol'),
('B46', 'KiloMol por metro cúbico', NULL, 'kmol/m³'),
('B47', 'Kilonewton', NULL, 'kN'),
('B48', 'Kilonewton metro', NULL, 'kN·m'),
('B49', 'KiloOhm', NULL, 'kΩ'),
('B5', 'palanquilla', NULL, NULL),
('B50', 'KiloOhm metro', NULL, 'kΩ·m'),
('B51', 'KiloLibra', 'Sinónimo: Kilogramo-fuerza', 'Kp'),
('B52', 'Kilosegundo', NULL, 'ks'),
('B53', 'Kilosiemens', NULL, 'kS'),
('B54', 'Kilosiemens por metro', NULL, 'kS/m'),
('B55', 'Kilovoltio por metro', NULL, 'kV/m'),
('B56', 'Kiloweber por metro', NULL, 'kWb/m'),
('B57', 'Año luz', 'Unidad de longitud que considera la distancia a la que viaja la luz en el vacío en un año.', 'ly'),
('B58', 'Litro por Mol', NULL, 'l/mol'),
('B59', 'Lumen hora', NULL, 'lm·h'),
('B6', 'Bollo', NULL, NULL),
('B60', 'Lumen por metro cuadrado', NULL, 'lm/m²'),
('B61', 'Luminosidad por watt', NULL, 'lm/W'),
('B62', 'Lumen segundo', NULL, 'lm·s'),
('B63', 'Hora de luz', NULL, 'lx·h'),
('B64', 'Segundo de luz', NULL, 'lx·s'),
('B65', 'Maxwell', NULL, 'Mx'),
('B66', 'Megaamperio por metro cuadrado', NULL, 'MA/m²'),
('B67', 'Megabecquerel por kilogramo', NULL, 'MBq/kg'),
('B68', 'Gigabit', 'Unidad de información igual a 10⁹ los bits (dígitos binarios).', 'Gbit'),
('B69', 'MegaCulombio por metro cúbico', NULL, 'MC/m³'),
('B7', 'Ciclo', 'Unidad de recuento de definir el número de ciclos (ciclo: un período recurrente de duración definida).', NULL),
('B70', 'MegaCulombio por metro cuadrado', NULL, 'MC/m²'),
('B71', 'Megaelectrónvoltio', NULL, 'MeV'),
('B72', 'Megagramo por metro cúbico', NULL, 'Mg/m³'),
('B73', 'Meganewton', NULL, 'MN'),
('B74', 'Meganewton metro', NULL, 'MN·m'),
('B75', 'MegaOhm', NULL, 'MΩ'),
('B76', 'MegaOhm metro', NULL, 'MΩ·m'),
('B77', 'Megasiemens por metro', NULL, 'MS/m'),
('B78', 'Megavoltio', NULL, 'MV'),
('B79', 'Megavoltio por metro', NULL, 'MV/m'),
('B8', 'Joule por metro cúbico', NULL, 'J/m³'),
('B80', 'Gigabit por segundo', 'Unidad de información igual a 10⁹ bits (dígitos binarios) por segundo.', 'Gbit/s'),
('B81', 'Reciprocidad del metro cuadrado, reciprocidad del segundo', NULL, 'm⁻²/s'),
('B82', 'Pulgadas por pie lineal', 'Unidad de longitud que define el número de pulgadas por pie lineal.', NULL),
('B83', 'Metro a la cuarta potencia', NULL, 'm⁴'),
('B84', 'Microamperio', NULL, 'µA'),
('B85', 'Microbar', NULL, 'µbar'),
('B86', 'MicroCulombio', NULL, 'µC'),
('B87', 'MicroCulombio por metro cúbico', NULL, 'µC/m³'),
('B88', 'MicroCulombio por metro cuadrado', NULL, 'µC/m²'),
('B89', 'Microfaradio por metro', NULL, 'µF/m'),
('B9', 'Batt', NULL, NULL),
('B90', 'Microhenry', NULL, 'µH'),
('B91', 'Microhenry por metro', NULL, 'µH/m'),
('B92', 'Micronewton', NULL, 'µN'),
('B93', 'Micronewton metro', NULL, 'µN·m'),
('B94', 'Micro Ohm', NULL, 'µΩ'),
('B95', 'MicroOhm metro', NULL, 'µΩ·m'),
('B96', 'Micropascal', NULL, 'µPa'),
('B97', 'Microrradián', 'Unidad de distancia angular igual a una milésima de milliradian. Unidad angular - una unidad de medida para ángulos.', 'µrad'),
('B98', 'Microsegundo', NULL, 'µs'),
('B99', 'Microsiemens', NULL, 'µS'),
('BAR', 'Bar [unidad de presión]', 'Se denomina bar a una unidad de presión equivalente a un millón de barias, aproximadamente igual a una atmósfera (1 atm). Su símbolo es «bar».', 'bar'),
('BB', 'Caja base', 'Una unidad de área de 112 hojas de productos de estaño (placa de estaño, acero libre de estaño o placa negra) 14 por 20 pulgadas o 31,360 pulgadas cuadradas.', NULL),
('BFT', 'Tablero de pies', 'Unidad de medida para el volumen de la madera en el Estados Unidos y Canadá . Es el volumen de una longitud de un pie de una placa de un pie de ancho y una pulgada de grosor.', 'fbm'),
('BH', 'Cepillo', NULL, NULL),
('BHP', 'Potencia al freno', NULL, 'BHP'),
('BIL', 'Billon', 'Sinonimo: Trillon en EUA.', NULL),
('BLD', 'Barril seco (EUA)', NULL, 'bbl (US)'),
('BLL', 'Barril (EUA)', 'Un barril estadounidense es igual a:

42 galones estadounidenses
168 cuartos estadounidenses
336 pintas estadounidenses
1344 gills estadounidenses
5376 onzas líquidas estadounidenses
158.987294928 litros', 'barrel (US)'),
('BP', 'Tabledo de cien pies', NULL, NULL),
('BPM', 'Latidos por minuto', 'El número de latidos por minuto.', 'BPM'),
('BQL', 'Becquerel', 'Es la actividad de una fuente radiactiva en la que se desintegra un núcleo por segundo en un dado instante.', 'Bq'),
('BTU', 'Unidad térmica británica (tabla internacional)', NULL, 'BtuIT'),
('BUA', 'Bushel (EUA)', 'El bushel es una unidad de medida de capacidad para mercancía sólida en los países anglosajones (países de habla inglesa). Se utiliza en el comercio de granos, harinas y otros productos análogos.', 'bu (US)'),
('BUI', 'Bushel (UK)', 'Un bushel tiene 4 pecks o 32 quarts, y equivale a 1,03205 del bushel de los Estados Unidos, que a su vez equivale a 0,35238 hectolitros. La palabra bushel está cayendo en desuso rápidamente.', 'bushel (UK)'),
('BW', 'Peso base', NULL, NULL),
('BZ', 'Millones de BTUs', NULL, NULL),
('C0', 'Llamada', 'Una unidad de recuento de definir el número de llamadas (call: sesión de comunicación o de visita).', NULL),
('C1', 'Libra de producto compuesto (peso total)', NULL, NULL),
('C10', 'Milifaradio', NULL, 'mF'),
('C11', 'Miligalón', NULL, 'mGal'),
('C12', 'Miligramo por metro', NULL, 'mg/m'),
('C13', 'MilliGray', NULL, 'mGy'),
('C14', 'Milihenry', NULL, 'mH'),
('C15', 'Milijoule', NULL, 'mJ'),
('C16', 'Milímetro por segundo', NULL, 'mm/s'),
('C17', 'Milímetro cuadrado por segundo', NULL, 'mm²/s'),
('C18', 'MiliMol', NULL, 'mmol'),
('C19', 'Mol por kilogramo', NULL, 'mol/kg'),
('C2', 'Carset', NULL, NULL),
('C20', 'Milinewton', NULL, 'mN'),
('C21', 'Kibibit', 'Unidad de información igual a 2¹⁰ (1024) bits (dígitos binarios).', 'Kibit'),
('C22', 'Milinewton por metro', NULL, 'mN/m'),
('C23', 'MiliOhm metro', NULL, 'mΩ·m'),
('C24', 'Milipascal segundo', NULL, 'mPa·s'),
('C25', 'Milirradián', 'Es una unidad derivada sistema internacional para la medición angular , que se define como una milésima parte de un radián (0,001 radianes).', 'mrad'),
('D9', 'Dina por centímetro cuadrado', NULL, 'Dyn / cm²'),
('E5', 'Tonelada métrica larga', 'Utilice ton (UK) o tonelada larga (US) (código común LTN)', NULL)
ON CONFLICT (code) DO UPDATE SET
            name = EXCLUDED.name,
            description = EXCLUDED.description,
            symbol = EXCLUDED.symbol,
            updated_at = NOW();