INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('SG', 'Segmento', 'Unidad de información equivalente a 64000bytes', NULL),
('SHT', 'Tonelada de envíos', 'Unidad de masa que define el número de toneladas para el envío.', NULL),
('SIE', 'Siemens', 'Se denomina siemens a la unidad derivada del SI para la medida de la conductancia eléctrica.', 'S'),
('SK', 'Camión cisterna con división', NULL, NULL),
('SM3', 'Metro cúbico estándar', 'Metro cúbico estándar (temperatura 15 ° C y presión 101325 milibares)', NULL),
('SMI', 'Milla (milla estatal)', 'Medida de longitud, especialmente utilizada en marina, que equivale a 1,852 m.', 'mile'),
('SN', 'Barra cuadrada', NULL, 'Rd²'),
('SQ', 'Cuadrado', 'Unidad de conteo que define el número de cuadrados (cuadrado: forma rectangular)', NULL),
('SQR', 'Cuadrado y techado', 'Unidad de conteo que conteo que define el número de plazas de materiales para techos, medida en múltiplos de 100 pies cuadrados', NULL),
('SR', 'Tira', 'Unidad de conteo que define el número de tiras (pieza larga y estrecha de un objeto)', NULL),
('SS', 'Medida métrica de hoja', NULL, NULL),
('SST', 'Estandar corto (7200 partidos)', NULL, NULL),
('STC', 'Palo', 'Unidad de conteo que define el número de palos (palo: pieza delgada y a menudo cilíndirca de una sustancia)', NULL),
('STI', 'Estone (UK)', NULL, 'st'),
('STK', 'Palo, cigarrillo', 'Unidad de conteo que define el número de cigarrillos en la unidad más pequeña para el cálculo de la población y/o del trabajo', NULL),
('STL', 'Litro estándar', 'Unidad de volumen que define el número de litros de un producto a una temperatura de 15 grados celsius, especialmente en relación con los aceites de hidrocarburos', NULL),
('STN', 'Tonelada (estados unidos) o tonelada corta (UK y estados unidos)', 'Sinónimo: tonelada neta (2000 lb)', 'ton (US)'),
('STW', 'Paja', 'Unidad de conteo que define el número de pajitas (paja:un tubo delgado utilizado para succionar liquidos)', NULL),
('SW', 'Número de madejas', 'Unidad de conteo que define el número de madejas (skein:un paquete de hilo o hilo suelto)', NULL),
('SX', 'Envío', 'Unidad de conteo que define el número de envíos (embarque: una cantidad de mercancias embarcadas o transportadas)', NULL),
('SYR', 'Jeringuilla', 'Unidad de conteo que define el número de jeringuillas (jeringa: un pequeño dispositivo para bombear, pulverizar y/o inyectar liquidos a través de una pequeña abertura)', NULL),
('T0', 'Linea de telecomunicaciones en servicio', 'Unidad de conteo que define el número de líneas de servicio', NULL),
('T1', 'Mil libras', NULL, NULL),
('T3', 'Mil pedazos', 'Unidad de conteo que define el número de piezas en múltiplos de 1000 (pieza: un solo artículo, artículo o ejemplar)', NULL),
('T4', 'Bolsa de mil', NULL, NULL),
('T5', 'Mil envolturas', NULL, NULL),
('T6', 'Mil galones (US)', NULL, NULL),
('T7', 'Impresión de mil', NULL, NULL),
('T8', 'Mil pulgadas lineales', NULL, NULL),
('TA', 'Décimo de pie cúbico', NULL, NULL),
('TAB', 'Tonelada de registro bruto', 'Una unidad de masa igual al total de las imágenes cúbicas antes de las deducciones, donde 1 registro t es igual a 100 pies cúbicos.Véase el Convenio internacional sobre el arqueo de los buques.', NULL),
('TAH', 'Kiloamperio-hora (milamperio-hora)', NULL, 'kA·h'),
('TAN', 'Número de acido total', 'Unidad de química que define la cantidad de hidróxido de potasio (KOH) en miligramos que se necesita para neutralizar los ácidos en un gramo de aceite. Es una medida importante de la calidad del petróleo crudo', 'TAN'),
('TC', 'Camión', NULL, NULL),
('TD', 'Termico', NULL, NULL),
('TE', 'Totalizador', NULL, NULL),
('TF', 'Diez yardas cuadradas', NULL, NULL),
('TI', 'Mil pulgadas cuadradas', 'Unidad de medida imperial', NULL),
('TIC', 'Tonelada métrica, incluido el contenedor', 'Unidad de masa que define el número de toneladas métricas de un producto, incluyendo su contenedor', NULL),
('TIP', 'Tonelada métrica, incluido el embalaje interior', 'Unidad de masa que define el número de toneladas metricas de un producto, incluyendo sus materiales de embalaje interior', NULL),
('TJ', 'Mil centímetros cuadrados', NULL, NULL),
('TKM', 'Tonelada kilometro', 'Unidad de información típicamente usada para propósitos de facturación, expresada como el número de toneladas (toneladas métricas) movidas sobre una distancia de un kilómetro', 't·km'),
('TL', 'Mil pies (lineal)', NULL, NULL),
('TMS', 'Kilogramo de carne importada, menos despojos', 'Unidad de masa equivalente a mil gramos de carne importada, sin tener en cuenta los subproductos menos valiosos como las montañas', NULL),
('TNE', 'Tonelada (tonelada métrica)', 'Sinónimo: tonelada métrica', 't'),
('TP', 'Paquete de diez', 'Unidad de conteo que define el número de elementos en múltiplos de 10', NULL),
('TPI', 'Dientes por pulgada', 'El número de dientes por pulgada', 'TPI'),
('TPR', 'Decenas de pares', 'Unidad de conteo que define el número de pares en multiplos de 10 (par:elemento descrito por dos)', NULL),
('TQ', 'Mil pies', NULL, NULL),
('TQD', 'Mil metros cúbicos por día', 'Unidad de volumen igual a mil metros cúbicos por día', 'km³/d'),
('TR', 'Diez pies cuadrados', NULL, NULL),
('TRL', 'Trillones (eur)', 'Unidad de escala númerica', NULL),
('TSD', 'Tonelada de sustancia 90% seca', NULL, NULL),
('TSH', 'Tonelada de vapor por hora', NULL, NULL),
('TST', 'Decena de conjuntos', 'Unidad de conteo que define el número de conjuntos en múltiplos de 10 (conjunto: un número de objetos agrupados)', NULL),
('TT', 'Mil metros lineales', NULL, NULL),
('TTS', 'Decenas de millar de pegatinas', 'Unidad de conteo que define el número de palos multiples de 10000 (Pegatina: pieza delgada y a menudo cilíndrica de una sustancia)', NULL),
('TV', 'Mil kilogramos', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();