INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('M31', 'Kilogramo por kilómetro', NULL, 'kg/km'),
('M32', 'Segundos pascal por litro', NULL, 'Pa·s/l'),
('M33', 'MiliMol por litro', NULL, 'mmol/l'),
('M34', 'Newton metro por metro cuadrado', NULL, 'N·m/m²'),
('M35', 'Milivoltio - amperio', NULL, 'mV·A'),
('M36', 'Mes de 30 días', 'Unidad de cuenta que define el número de meses expresado en múltiplos de 30 días, un día es igual a 24 horas.', 'mo (30 days)'),
('M37', 'Actual 360', 'Unidad de cuenta que define el número de años expresado en múltiplos de 360 días, un día es igual a 24 horas.', 'y (360 days)'),
('M38', 'Kilómetro por segundo cuadrado', '1000 veces de la unidad base del sistema internacional dividido por la potencia de la unidad base del sistema internacional por el segundo al  exponente 2.', 'km/s²'),
('M39', 'Centímetro por segundo cuadrado', '0.01 veces de unidad de base del sistema internacional dividido por la potencia de la unidad de base del sistema internacional en segundo lugar por el exponente 2.', 'cm/s²'),
('M4', 'Valor monetario', 'Unidad de medida expresada como un monto monetario.', NULL),
('M40', 'Yarda por segundo cuadrado', 'Unidad de longitud de acuerdo con el sistema Anglo-Americano y el sistema imperial de unidades, dividido por la potencia de la unidad del sistema internacional, segundo elevado al exponente 2.', 'yd/s²'),
('M41', 'Milímetro por segundo cuadrado', '0.001 veces de unidad de base del sistema internacional, dividido por la potencia de la unidad de base del sistema internacional por el segundo exponente 2.', 'mm/s²'),
('M42', 'Milla (milla estatal)  por segundo cuadrado', 'Unidad de la longitud según el sistema Imperial de unidades dividido por la potencia de la unidad base del sistema internacional por segundo por el exponente 2.', 'mi/s²'),
('M43', 'Mil (unidad de Medida Militar)', 'Unidad para indicar un ángulo en la zona militar, igual a la 6400ª parte del círculo completo del 360° ó 2  pi radian.', 'mil'),
('M44', 'Revolución', 'Unidad para identificar un ángulo de un círculo de 360 grados ó 2*pi*radio (Referencia ISO/TC12 SI Guía).', 'rev'),
('M45', 'Grado por segundo cuadrado', '360 partes de un círculo completo dividido por la potencia de la unidad de base SI en segundo lugar y el exponente 2.', '°/s²'),
('M46', 'Revolución por minuto', NULL, 'r/min'),
('M47', 'Circular Mil', 'Unidad que representa el área del círculo de un mil de diámetro.', 'cmil'),
('M48', 'Milla cuadrada (basado en u.s survey foot)', 'Unidad de área que es principalmente usada en la agricultura y en la forestación.', 'mi² (US survey)'),
('M49', 'Cadena', 'Es una unidad de longitud utilizada para medir terrenos. Equivale a 20,1168 metros, y en inglés se llama surveyor chain.', 'ch (US survey)'),
('M5', 'Microcurie', NULL, 'µCi'),
('M50', 'Estadio', 'Unidad comunmente usada en Gran Bretaña en distancias rurales: 1 furlong = 40 rods = 10 cadenas (UK) =1/8 de milla = 1/10 furlong = 220 yardas =660 pies.', 'fur'),
('M51', 'Pie (Topografía UEA)', 'Unidad comunmente usada en los estados unidos para la inspección de artillería.', 'ft (US survey)'),
('M52', 'Milla', 'Unidad comunmente usada en los Estados Unidos para la inspección de artillería.', 'mi (US survey)'),
('M53', 'Metro por pascal', 'Metro, unidad del Sistema Internacional dividido por Pascal, Unidad del Sistema Internacional', 'm/Pa'),
('M55', 'Metro por radián', 'Unidad del factor de conversión para la implementación de rotación a movimiento lineal.', 'm/rad'),
('M56', 'Shake', 'Unidad para un periódo muy corto.', 'shake'),
('M57', 'Milla por minuto', 'Unidad de velocidad del sistema inglés de unidades.', 'mi/min'),
('M58', 'Milla por segundo', 'Unidad de velocidad del sistema inglés de unidades.', 'mi/s'),
('M59', 'Metro por segundo pascal', 'Metro dividido por el producto de SI unidad base segundo y el derivado unidad SI pascal.', '(m/s)/Pa'),
('M60', 'Metro por hora', 'Metro,unidad del sistema internacional dividido por la unidad de hora.', 'm/h'),
('M61', 'Pulgada por año', 'Unidad de longitud según el sistema de unidades Anglo-Americano y el sistema Imperial de unidades dividido por la unidad común año de 365 días.', 'in/y'),
('M62', 'Kilómetro por segundo', '1000 veces del medidor de unidad de base SI dividido por la segunda unidad de base SI.', 'km/s'),
('M63', 'Pulgada por minuto', 'Unidad de pulgada de acuerdo con el sistema de unidades Anglo-Americanas e Imperial dividido por el minuto de unidad.', 'in/min'),
('M64', 'Yarda por segundo', 'Unidad de yarda de acuerdo con el sistema de unidades Anglo-Americanas e Imperial dividido por la unidad de base segundo.', 'yd/s'),
('M65', 'Yarda por minuto', 'Unidad de yarda de acuerdo con el sistema de unidades Anglo-Americanas e Imperial dividido por el minuto de unidad.', 'yd/min'),
('M66', 'Yarda por hora', 'Unidad de yarda de acuerdo con el sistema Anglo-Americano y el sistema Imperial de unidades, dividido por la unidad de minuto.', 'yd/h'),
('M67', 'Acre-pie', 'Unidad de volúmen, la cúal es usada en los Estados Unidos para medir la capacidad de las presas.', 'acre-ft (US survey)'),
('M68', 'Cordón', 'Unidad tradicional del volumen de leña apilada que se ha medido con un cordón.', 'cord'),
('M69', 'Milla cúbica (reinounido)', NULL, 'mi³'),
('M7', 'Micro-pulgada', NULL, 'µin'),
('M70', 'Unidad tradicional de capacidad de carga', NULL, 'RT'),
('M71', 'Metro cúbico por pascal (joules)', 'Unidad de Energía del sistema internacional, metro elevado al exponente 3 y dividido por la unidad pascal.', 'm³/Pa'),
('M72', 'Bel', 'las décimas de bel, o decibeles. El logaritmo de la relación del sonido o la señal con un estándar proporciona la medición del decibel. ... El símbolo correspondiente a la unidad es B, pero dB es la unidad estándar.', 'B'),
('M73', 'Kilogramo por metro cúbico pascal', 'Unidad base del sistema internacional kilogramo, dividido por el producto de metro elevado al exponente 3 por pascal.', '(kg/m³)/Pa'),
('M74', 'Kilogramo por pascal', NULL, 'kg/Pa'),
('M75', 'Kilolibra fuerza', '100 veces la unidad de fuerza, libra fueza de acuerdo con la relación del sistema de unidades  Anglo-Americano', 'kip'),
('M76', 'Poundal', 'Unidad no conforme al sistema internacional de la potencia, que corresponde a una masa de una libra multiplicada con la aceleración de un pie por segundo cuadrado.', 'pdl'),
('M77', 'Kilogramo metro por segundo cuadrado', 'Producto del kilogramo,unidad base del sistema internacional y del metro, unidad base del sistema internacional dividido por la potencia del segundo elevado al exponente 2.', 'kg·m/s²'),
('M78', 'Pond', '0.001 veces de la unidad del peso, definida como una masa de 1 kg que se encuentra sobre una fuerza de peso de 1 kp por la fuerza gravitatoria al nivel del mar, que corresponde a una fuerza de 9,806 65 newton.', 'p'),
('M79', 'Pie cuadrado por hora', 'Potencia de la unidad pie, de acuerdo con el sistema Anglo-Americano e Imperial de unidades, elevado al exponente 2 y dividido por la unidad derivada pascal del sistema internacional de unidades.', 'ft²/h'),
('M80', 'Stokes por pascal', 'CGS (Centímetro-Gramo-Segundo sistema) unidad stokes dividido por la unidad derivada del sistema internacional, pascal.', 'St/Pa'),
('M81', 'Centímetro cuadrado por segundo', NULL, 'cm²/s'),
('M82', 'Metro cuadrado por segundo pascal', 'Potencia de la unidad base, metro, del sistema internacional con el exponente 2, dividido por la unidad base, segundo, y la unidad derivada, pascal, ambas del sistema internacional.', '(m²/s)/Pa'),
('M83', 'Denier', 'Unidad tradicional para la indicación de la masa lineal de fibras e hilados textiles.', 'den'),
('M84', 'Libra por yarda', 'Unidad de masa lineal según el sistema de unidades avoirdupois.', 'lb/yd'),
('M85', 'Tonelada, ensayo', 'Unidad de masa no conforme al sistema internacional, utilizada en la mineralogía para determinar la concentración de metales preciosos en el mineral de acuerdo con la masa del metal precioso en miligramos en una muestra de la masa de un sonido de ensayo (número de onzas troy en una tonelada corta (1 000 lb)).', NULL),
('M86', 'Libra Alemana', 'Anticuada unidad de masa usada en Alemania.', 'pfd'),
('M87', 'Kilogramo por segundo pascal', 'Es la unidad base kilogramo dividido por el producto de la unidad base segundo y la derivada de la unidad pascal.', '(kg/s)/Pa'),
('M88', 'Tonelada por mes', 'Unidad tonelada métrica dividida por la unidad mes', 't/mo'),
('M89', 'Tonelada por año', 'Unidad tonelada métrica dividida por la unidad año con 365 días', 't/y'),
('M9', 'Millones de btu por 1000 pies cúbicos', NULL, 'MBTU/kft³'),
('M90', 'Kilolibra por hora', '1000 veces la unidad de la masa libra avoirdupois de acuerdo con el sistema unitario avoirdupois dividido por la unidad de hora.', 'klb/h'),
('M91', 'Libra por libra', 'Proporción de la masa consistente en la libra avoirdupois según el sistema unitario avoirdupois dividido por la libra avoirdupois según el sistema unitario avoirdupois.', 'lb/lb'),
('M92', 'Libra fuerza pie', 'Producto de la unidad libra fuerza, de acuerdo con el sistema de unidades Anglo-Americano, y la unidad pie, de acuerdo con el sistema de unidades, Anglo-Americano y el sistema imperial de unidades.', 'lbf·ft'),
('M93', 'Newton metro por radián', 'Producto de la unidad derivada del sistema internacional, newton y de la unidad base , metro, dividida por la unidad radián.', 'N·m/rad'),
('M94', 'Kilogramo metro', 'Unidad de desequilibrio como producto del kilogramo  y el metro.', 'kg·m'),
('M95', 'Poundal pie', 'Producto de la unidad poundal, no conforme al sistema internacional de unidades, y la unidad pie, de acuerdo con el sistema de unidades Anglo-Americano y el sistema imperial.', 'pdl·ft'),
('M96', 'Poundal pulgada', 'Producto de la unidad poundal, no conforme al sistema internacional de unidades, y la unidad pulgada, de acuerdo con el sistema de unidades Anglo-Americano y el sistema imperial.', 'pdl·in'),
('M97', 'Dina metro', 'CGS (Centímetro-Gramo-Segundo sistema) unidad del momento de rotación.', 'dyn·m'),
('M98', 'Kilogramo centímetro por segundo', 'Producto del kilogramo de unidad de base SI y  0.01 veces de metro unidad de base SI dividido por la unidad de base SI en segundo.', 'kg·(cm/s)'),
('M99', 'Gramo centímetro por segundo', 'Producto del 0.001 veces del kilogramo de la unidad base SI y el 0,01 veces del metro de la unidad base SI dividido por la unidad base SI, segundo.', 'g·(cm/s)'),
('MA', 'Máquina por unidad', NULL, NULL),
('MAH', 'Megavoltio amperio reactivo hora', 'Define la cantidad total de potencia reactiva a través de un sistema de potencia.', 'Mvar·h'),
('MAL', 'Megalitro', NULL, 'Ml'),
('MAM', 'Megametro', 'Es la unidad de longitud que equivale a un millón de metros.', 'Mm'),
('MAR', 'Megavar', 'Una unidad de potencia reactiva eléctrica representada por una corriente de mil amperios que fluye debido a una diferencia de potencial de mil voltios donde el seno del ángulo de fase entre ellos es 1.', 'kvar'),
('MAW', 'Megawatt', 'Unidad de potencia que define la tasa de energía transferida o consumida cuando una corriente de 1000 amperios fluye debido a un potencial de 1000 volts al factor de potencia unitario.', 'MW'),
('MBE', 'Mil equivalente de ladrillo estándar', 'Unidad de cuenta que define el número de mil unidades equivalentes de ladrillo.', NULL),
('MBF', 'Mil pies de tabla', NULL, NULL),
('MBR', 'Milibar', NULL, 'mbar'),
('MC', 'Microgramo', NULL, 'µg'),
('MCU', 'Milicurie', NULL, 'mCi'),
('MD', 'Tonelada métrica seca al aire', 'Unidad de conteo que define el número de toneladas métricas de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('MF', 'Miligramo por pie cuadrado por lado', NULL, NULL),
('MGM', 'Miligramo', 'Medida de masa, de símbolo mg, que es igual a la milésima parte de un gramo.', 'mg'),
('MHZ', 'Megahertz', 'Medida de frecuencia que es igual a 1 millón de hertz.', 'MHz'),
('MIK', 'Milla cuadrada (milla estatal)', 'Es una unidad de superficie equivalente a un cuadrado cuyos lados miden una milla estatutaria.', 'mi²'),
('MIL', 'Mil', 'Es un número natural que se escribe 1000 o 10³ en notación científica, y que sigue del 999 y precede al 1001.', NULL),
('MIN', 'Minuto [unidad de tiempo]', 'Es una unidad de tiempo que equivale a la sexagésima parte de una hora. También comprende 60 segundos. Su símbolo es min (adviértase que no es una abreviatura: no admite mayúscula, ni punto, ni plural).', 'min'),
('MIO', 'Millon', 'Es igual a mil millares, o 106. El concepto de millón también se puede expresar mediante el prefijo mega antepuesto a unidades del SI. Etimología: millón proviene del término italiano milione (del latín: mille).', NULL),
('MIU', 'Unidad internacional de millon', 'Unidad de cuenta que define el número de unidades internacionales en múltiplos de 106.', NULL),
('MK', 'Miligramo por pulgada cuadrada', NULL, 'Mg / in²'),
('MLD', 'Mil millones', 'Sinónimo: billon (US)', NULL),
('MLT', 'Mililitro', 'Medida de volumen, de símbolo ml, que es igual a la milésima parte de un litro.', 'ml'),
('MMK', 'Milímetro cuadrado', 'Medida de longitud, de símbolo mm, que es igual a la milésima parte de un metro.', 'mm²'),
('MMQ', 'Milímetro cúbico', 'Medida de longitud, de símbolo mm, que es igual a la milésima parte de un metro.', 'mm³'),
('MMT', 'Milímetro', 'Es una unidad de longitud. Es el tercer submúltiplo del metro y equivale a la milésima parte de él.', 'mm'),
('MND', 'Kilogramo, peso seco', 'Unidad de masa que define el número de kilogramos de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('MON', 'Mes', 'Unidad de tiempo equivalente a 1/12 de año de 365.25 días.', 'mo')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();