INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('HM', 'Milla por hora (milla estatal)', NULL, 'mile/h'),
('HMQ', 'Millones de metros cúbicos', 'Unidad de volumen igual a un millón de metros cúbicos.', 'Mm³'),
('HMT', 'Hectómetro', 'Es una unidad de longitud. Equivale a 100 metros. Hecto es el prefijo para 100 en el Sistema Internacional de Unidades.', 'hm'),
('HN', 'Milímetro convencional de mercurio', NULL, 'Mm Hg'),
('HO', 'Cien onzas troy', NULL, NULL),
('HP', 'Milímetro convencional de agua', NULL, 'Mm H $ ₂ $ O'),
('HPA', 'Hectolitro de alcohol puro', 'Unidad de volumen igual a cien litros de alcohol puro.', NULL),
('HS', 'Cien pies cuadrados', NULL, NULL),
('HT', 'media hora', NULL, NULL),
('HTZ', 'Hertz', 'Unidad de frecuencia del Sistema Internacional, de símbolo Hz, que equivale a la frecuencia de un fenómeno periódico cuyo período es 1 segundo.', 'Hz'),
('HUR', 'Hora', 'Es una unidad de tiempo que se corresponde con la vigésimo-cuarta parte de un día solar medio.', 'h'),
('HY', 'Cien yardas', NULL, NULL),
('IA', 'Pulgada libra', NULL, 'in·lb'),
('IC', 'Contar por pulgada', NULL, NULL),
('IE', 'Personas', 'Unidad de conteo que define el número de personas.', NULL),
('IF', 'Pulgadas de agua', 'Use una pulgada de agua (código común F78)', NULL),
('II', 'Columna pulgada', NULL, NULL),
('IM', 'Impresión', NULL, NULL),
('INH', 'Pulgada', 'Es una unidad de longitud antropométrica que equivale al ancho de la primera falange del pulgar, y más específicamente a su falange distal.', 'in'),
('INK', 'Pulgada cuadrada', 'Es una unidad de medida imperial, equivalente a la superficie de un cuadrado cuyo lado posee 1 pulgada de longitud (2,54 centímetros).', 'in²'),
('INQ', 'Pulgada cúbica', 'Sinónimo: pulgada cuadrada', 'in³'),
('IP', 'póliza de seguros', NULL, NULL),
('ISD', 'Grado internacional de azúcar', 'Unidad de medida que define el contenido de azúcar de una solución, expresada en grados.', NULL),
('IT', 'Recuento por centímetro', NULL, NULL),
('IU', 'Pulgada por segundo', NULL, 'in/s'),
('IV', 'Pulgada por segundo al cuadrado', NULL, 'in/s²'),
('J10', 'Por ciento por milímetro', 'Unidad de proporción, igual a 0,01, en relación a un milímetro.', '%/mm'),
('J12', 'Por mille por psi', 'Unidad de presión igual a una milésima de psi (libra-fuerza por pulgada cuadrada).', '‰/psi'),
('J13', 'Grado api', 'Unidad de densidad relativa como una medida de cuán pesado o ligero es un líquido de petróleo comparado con agua (API: American Petroleum Institute).', '°API'),
('J14', 'Grado baume (escala de origen)', 'Unidad tradicional de densidad relativa para líquidos. Nombrado en honor de Antoine Baumé.', '°Bé'),
('J15', 'Grado baume (us pesado)', 'Unidad de densidad relativa para líquidos más pesados que el agua.', '°Bé (US heavy)'),
('J16', 'Grado baume (luz de los EUA)', 'Unidad de densidad relativa para líquidos más ligeros que el agua.', '°Bé (US light)'),
('J17', 'Grado balling', 'Unidad de densidad como medida del contenido de azúcar, especialmente de mosto de cerveza. Nombrado en honor de Karl Balling.', '°Balling'),
('J18', 'Grado brix', 'Unidad de proporcion utilizada para medir la proporcion de masa de azúcar disuelta a agua de un líquido. Nombrado en honor de Adolf Brix', '°Bx'),
('J19', 'Grado fahrenheit hora pie cuadrado por unidad térmica británica (termoquímico).', NULL, '°F·h·ft²/Btuth'),
('J2', 'Joule por kilogramo', NULL, 'J/kg'),
('J20', 'Grado fahrenheit por kelvin', NULL, '°F/K'),
('J21', 'Grado fahrenheit por bar', NULL, '°F/bar'),
('J22', 'Grado fahrenheit hora pie cuadrado por unidad térmica británica (tabla internacional).', NULL, '°F·h·ft²/BtuIT'),
('J23', 'Grado fahrenheit por hora', NULL, '°F/h'),
('J24', 'Grado fahrenheit por minuto', NULL, '°F/min'),
('J25', 'Grado fahrenheit por segundo', NULL, '°F/s'),
('J26', 'Reciprocidad grado fahrenheit', NULL, '1/°F'),
('J27', 'Grado oechsle', 'Unidad de densidad como medida del contenido de azúcar de mosto, el licor no fermentado del que se elabora el vino. Nombrado en honor de Ferdinand Oechsle.', '°Oechsle'),
('J28', 'Grado rankine por hora', NULL, '°R/h'),
('J29', 'Grado rankine por minuto', NULL, '°R/min'),
('J30', 'Grado rankine por segundo', NULL, '°R/s'),
('J31', 'Grado twaddel.', 'Unidad de densidad para líquidos que son más pesados que el agua. 1 grado Twaddle representa una diferencia en gravedad específica de 0,005.', '°Tw'),
('J32', 'Micropoise', NULL, 'µP'),
('J33', 'Microgramo por kilogramo', NULL, 'µg/kg'),
('J34', 'Microgramo por metro cúbico kelvin', NULL, '(µg/m³)/K'),
('J35', 'Microgramo por metro cúbico bar', NULL, '(µg/m³)/bar'),
('J36', 'Microlitro por litro', NULL, 'µl/l'),
('J38', 'Baud', 'Es Unidad de medida utilizada en telecomunicaciones, que representa el número de símbolos por segundo en un medio de transmisión digital.1 Cada símbolo puede comprender 1 o más bits, dependiendo del esquema de modulación.', 'Bd'),
('J39', 'Unidad térmica británica (significado)', NULL, 'Btu'),
('J40', 'Unidad térmica británica (tabla internacional) pie por hora pie cuadrado grado fahrenheit.', NULL, 'BtuIT·ft/(h·ft²·°F)'),
('J41', 'Unidad térmica británica (tabla internacional) pulgada por hora pie cuadrado grado fahrenheit.', NULL, 'BtuIT·in/(h·ft²·°F)'),
('J42', 'Unidad térmica británica (tabla internacional) pulgada por segundo pie cuadrado grado fahrenheit.', NULL, 'BtuIT·in/(s·ft²·°F)'),
('J43', 'Unidad térmica británica (tabla internacional) por libra grado fahrenheit', NULL, 'BtuIT/(lb·°F)'),
('J44', 'Unidad térmica británica (tabla internacional) por minuto', NULL, 'BtuIT/min'),
('J45', 'Unidad térmica británica (tabla internacional) por segundo', NULL, 'BtuIT/s'),
('J46', 'Unidad térmica británica (termoquímico) pie por hora pie cuadrado grado fahrenheit.', NULL, 'Btuth·ft/(h·ft²·°F)'),
('J47', 'Unidad térmica británica (termoquímica) por hora', NULL, 'Btuth/h'),
('J48', 'Unidad térmica británica (termoquímico) pulgada por hora pie cuadrado grado fahrenheit.', NULL, 'Btuth·in/(h·ft²·°F)'),
('J49', 'Unidad térmica británica (termoquímico) pulgada por segundo pie cuadrado grado fahrenheit.', NULL, 'Btuth·in/(s·ft²·°F)'),
('J50', 'Unidad térmica británica (termoquímico) por libra grado fahrenheit', NULL, 'Btuth/(lb·°F)'),
('J51', 'Unidad térmica británica (termoquímica) por minuto', NULL, 'Btuth/min'),
('J52', 'Unidad térmica británica (termoquímica) por segundo', NULL, 'Btuth/s'),
('J53', 'Culombio metro cuadrado por kilogramo', NULL, 'C·m²/kg'),
('J54', 'Megabaud', 'Unidad de velocidad de transmisión de señal igual a 106 (1000000) eventos de señalización por segundo.', 'MBd'),
('J55', 'Watt segundo', NULL, 'W·s'),
('J56', 'Bar por bar', NULL, 'bar/bar'),
('J57', 'Barril (uk petróleo)', 'Es el nombre de varias unidades de volumen usadas en el Reino Unido y en los Estados Unidos.', 'bbl (UK liq.)'),
('J58', 'Barril (petróleo UK) por minuto', NULL, 'bbl (UK liq.)/min'),
('J59', 'Barril (petróleo UK) por día', NULL, 'bbl (UK liq.)/d'),
('J60', 'Barril (petróleo UK) por hora', NULL, 'bbl (UK liq.)/h'),
('J61', 'Barril (petróleo UK) por segundo', NULL, 'bbl (UK liq.)/s'),
('J62', 'Barril (petróleo estados unidos) por hora', NULL, 'bbl (US)/h'),
('J63', 'Barril (petróleo estados unidos) por segundo', NULL, 'bbl (US)/s'),
('J64', 'Bushel (UK) por día', NULL, 'bu (UK)/d'),
('J65', 'Bushel (UK) por hora', NULL, 'bu (UK)/h'),
('J66', 'Bushel (UK) por minuto', NULL, 'bu (UK)/min'),
('J67', 'Bushel (UK) por segundo', NULL, 'bu (UK)/s'),
('J68', 'Bushel (seco,estados unidos) por día', NULL, 'bu (US dry)/d'),
('J69', 'Bushel (seco,estados unidos) por hora', NULL, 'bu (US dry)/h'),
('J70', 'Bushel (seco,estados unidos) por minuto', NULL, 'bu (US dry)/min'),
('J71', 'Bushel (seco,estados unidos) por segundo', NULL, 'bu (US dry)/s'),
('J72', 'Centinewton metro', NULL, 'cN·m'),
('J73', 'Centipoise por kelvin', NULL, 'cP/K'),
('J74', 'Centipoise por bar', NULL, 'cP/bar'),
('J75', 'Caloría', 'Unidad de energía térmica, de símbolo cal, que equivale a la cantidad de calor necesaria para elevar 1 grado centígrado la temperatura de 1 gramo de agua.', 'cal'),
('J76', 'Caloría (tabla internacional) por gramo gadro celsius', NULL, 'calIT/(g·°C)'),
('J78', 'Caloría (termoquímica) por centímetro segundo grado celsius', NULL, 'calth/(cm·s·°C)'),
('J79', 'Caloría (termoquímico) por gramo gadro celsius', NULL, 'calth/(g·°C)'),
('J81', 'Caloría (termoquímica) por minuto', NULL, 'calth/min'),
('J82', 'Caloría (termoquímica) por segundo', NULL, 'calth/s'),
('J83', 'Clo', 'Clo es una unidad de medida empleada para el índice de indumento.', 'clo'),
('J84', 'Centímetro por segundo kelvin', NULL, '(cm/s)/K'),
('J85', 'Centímetro por segundo bar', NULL, '(cm/s)/bar'),
('J87', 'Centímetro cúbico por metro cúbico', NULL, 'cm³/m³')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();