INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('CTN', 'Tonelada de contenido (métrica)', 'Unidad de masa que define el número de toneladas métricas de un elemento con nombre en un producto.', NULL),
('CUR', 'Curie', 'El Curie (Ci) es la unidad antigua de medida de radiactividad, definida como la actividad de in gramo del isótopo Ra-226, su equivalencia es: 1Ci = 3,7 1010 Bq.', 'Ci'),
('CWA', 'Hundred pound', NULL, 'cwt (US)'),
('CWI', 'Hundredweight', NULL, 'cwt (UK)'),
('CZ', 'Combo', NULL, NULL),
('D03', 'Kilovatio hora por hora', 'Unidad de energía acumulada en mil vatios durante un período de una hora.', 'kW·h/h'),
('D04', 'Lot [unidad de peso]', 'Unidad de peso igual a aproximadamente media onza o 15 gramos.', NULL),
('D1', 'Segundo recíproco por estereorradián', NULL, 's⁻¹/sr'),
('D10', 'Siemens por metro', NULL, 'S/m'),
('D11', 'Mebibit', 'Una unidad de información igual a 2²⁰ (1048576) bits (dígitos binarios).', 'Mibit'),
('D12', 'Siemens metro cuadrado por Mol', NULL, 'S·m²/mol'),
('D13', 'Sievert', NULL, 'Sv'),
('D14', 'Yarda mil lineal', NULL, NULL),
('D15', 'Sone', 'Una unidad de volumen del sonido subjetivo. Un sone es la intensidad de un tono puro de la frecuencia y la fuerza de un kilohertz 40 decibelios.', NULL),
('D16', 'Centimetro cuadrado por erg', NULL, 'cm²/erg'),
('D17', 'Centimetro cuadrado por esteroradian erg', NULL, 'cm²/(sr·erg)'),
('D18', 'Metro kelvin', NULL, 'm·K'),
('D19', 'Metro cuadrado kelvin por watt.', NULL, 'm²·K/W'),
('D2', 'Segundo recíproco por estereorradián metro cuadrado', NULL, 's⁻¹/(sr·m²)'),
('D20', 'Metro cuadrado por joule', NULL, 'm²/J'),
('D21', 'Metro cuadrado por kilogramo', NULL, 'm²/kg'),
('D22', 'Metro cuadrado por Mol', NULL, 'm²/mol'),
('D23', 'Gramo pluma (proteína)', 'Unidad de recuento pata definir el número de gramos de aminoácidos  prescritos para la terapia parenteral y terapia enteral.', NULL),
('D24', 'Metro cuadrado por esteroradian', NULL, 'm²/sr'),
('D25', 'Metro cuadrado por esteroradian joule', NULL, 'm²/(sr·J)'),
('D26', 'Metro cuadrado por voltiosegundo', NULL, 'm²/(V·s)'),
('D27', 'Estereorradían', 'Es la unidad que mide angulos solidos', 'sr'),
('D28', 'sifón', NULL, NULL),
('D29', 'Terahertz', 'Se refiere a las ondas electromagnéticas que se propagan en las frecuencias en el rango de los terahercios.', 'THz'),
('D30', 'Terajoule', NULL, 'TJ'),
('D31', 'Terawatt', NULL, 'TW'),
('D32', 'Terawatt hora', NULL, 'TW·h'),
('D33', 'Tesla', 'Es la inducción magnética uniforme que, repartida normalmente sobre una superficie de 1 metro cuadrado, produce a través de esta superficie un flujo magnético total de 1 weber.', 'T'),
('D34', 'Tex', 'Enidad de medida utilizada para medir la densidad o la masa lineal de una fibra.', 'tex (g/km)'),
('D35', 'Calorías (termoquímicas)', NULL, 'º cal'),
('D36', 'Megabit', 'unidad que se usa para cuantificar un caudal de datos equivalente a 1000 kb/s.', 'Mbit'),
('D37', 'Calorías (termoquímicas) por gramo de kelvin', NULL, 'º cal / (g · K)'),
('D38', 'Calorías (termoquímicas) por segundo centímetro kelvin', NULL, 'º cal / (s · cm · K)'),
('D39', 'Calorías (termoquímicas) por segundo centímetro cuadrado kelvin', NULL, 'º cal / (s · cm² · K)'),
('D40', 'Mil litros', NULL, NULL),
('D41', 'Tonelada por metro cúbico', NULL, 't/m³'),
('D42', 'Año tropical', 'Unidad de tiempo equivalente a 365.242 19 días. Sinónimo: año solar.', 'y (tropical)'),
('D43', 'Unidad de masa atómica unificada', NULL, 'u'),
('D44', 'Var', 'El nombre de la unidad es un acrónimo de volt-amperio-reactive.', 'var'),
('D45', 'Voltio cuadrado por kelvin cuadrado', NULL, 'V²/K²'),
('D46', 'Voltioio-amperio', NULL, 'V·A'),
('D47', 'Voltio por centímetro', NULL, 'V/cm'),
('D48', 'Voltio por Kelvin', NULL, 'V/K'),
('D49', 'Millivoltio por Kelvin', NULL, 'mV/K'),
('D5', 'Kilogramo por centímetro cuadrado', NULL, 'kg/cm²'),
('D50', 'Voltio por metro', 'Es la intensidad de un campo eléctrico, que ejerce una fuerza de 1 newton sobre un cuerpo cargado con una cantidad de electricidad de 1 coulomb.', 'V/m'),
('D51', 'Voltio por milímetro', NULL, 'V/mm'),
('D52', 'Watt por kelvin', NULL, 'W/K'),
('D53', 'Watt por metro kelvin', 'Es la conductividad térmica de un cuerpo homogéneo isótropo, en la que una diferencia de temperatura de 1 kelvin entre dos planos paralelos, de área 1 metro cuadrado y distantes 1 metro, produce entre estos planos un flujo térmico de 1 watt.', 'W/(m·K)'),
('D54', 'Watt por metro cuadrado', NULL, 'W/m²'),
('D55', 'Watt por metro cuadrado kelvin', NULL, 'W/(m²·K)'),
('D56', 'Watt por metro cuadrado kelvin a la cuarta potencia', NULL, 'W/(m²·K⁴)'),
('D57', 'Watt por estereorradián', NULL, 'W/sr'),
('D58', 'Watt por estereorradián metro cuadrado', NULL, 'W/(sr·m²)'),
('D59', 'Weber por metro', NULL, 'Wb/m'),
('D6', 'Roentgen por segundo', NULL, 'R/s'),
('D60', 'Weber por milímetro', NULL, 'Wb/mm'),
('D61', 'Minuto [unidad de ángulo]', 'Es una sexagesima parte de un grado.', ''''),
('D62', 'Segundo [unidad de ángulo]', 'Es una unidad de medida angular. Su valor equivale a 1/60 del minuto de arco y a 1/3600 del grado sexagesimal.', '"'),
('D63', 'Libro', 'Unidad de recuento para definir el número de libros (libro: conjunto de elementos unidos entre sí o documento de un material escrito).', NULL),
('D64', 'bloquear', NULL, NULL),
('D65', 'Redondo', 'Unidad de recuento para definir el número de rondas (redondos: un objeto circular o cilíndrico).', NULL),
('D66', 'casete', NULL, NULL),
('D67', 'Dólar por hora', NULL, NULL),
('D68', 'Número de palabras', 'Unidad de recuento para definir el número de palabras.', NULL),
('D69', 'Pulgada a la cuarta potencia', NULL, 'in⁴'),
('D7', 'Sandwich', NULL, NULL),
('D70', 'Calorías (tabla internacional)', NULL, 'Cal TI'),
('D71', 'Calorías (tabla internacional) por segundo centímetro kelvin', NULL, 'cal TI / (s · cm · K)'),
('D72', 'Calorías (tabla internacional) por segundo centímetro cuadrado kelvin', NULL, 'Cal TI / (s · cm² · K)'),
('D73', 'Joule metro cuadrado', NULL, 'J·m²'),
('D74', 'Kilogramo por Mol', NULL, 'kg/mol'),
('D75', 'Calorías (tabla internacional) por gramo', NULL, 'cal IT / g'),
('D76', 'Calorías (tabla internacional) por gramo de kelvin', NULL, 'cal IT / (g · K)'),
('D77', 'MegaCulombio', NULL, 'MC'),
('D78', 'Megajoule por segundo', 'Unidad de energía acumulada igual a un millón de julios por segundo.', 'MJ/s'),
('D79', 'Viga', NULL, NULL),
('D8', 'Draize score', NULL, NULL),
('D80', 'Microwatt', NULL, 'µW'),
('D81', 'Microtesla', NULL, 'µT'),
('D82', 'Microvoltio', NULL, 'µV'),
('D83', 'Milinewton metro', NULL, 'mN·m'),
('D85', 'Microwatt por metro cuadrado', 'Es equivalente a una millonésima parte de un vatio.', 'µW/m²'),
('D86', 'MiliCulombio', NULL, 'mC'),
('D87', 'MiliMol por kilogramo', NULL, 'mmol/kg'),
('D88', 'MiliCulombio por metro cúbico', NULL, 'mC/m³'),
('D89', 'MiliCulombio por metro cuadrado', NULL, 'mC/m²'),
('D9', 'Dina por centímetro cuadrado', NULL, 'Dyn / cm²'),
('D90', 'Metro cúbico (neta)', NULL, NULL),
('D91', 'Rem', NULL, 'rem'),
('D92', 'banda', NULL, NULL),
('D93', 'Segundo por metro cúbico', NULL, 's/m³'),
('D94', 'Segundo por metro cúbico Radian', NULL, 's/(rad·m³)'),
('D95', 'Joule por gramo', NULL, 'J/g'),
('D96', 'Libra bruta', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();