INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('J89', 'Centímetro de mercurio', NULL, 'Cm Hg'),
('J90', 'Decímetro cúbico por día', NULL, 'dm³/d'),
('J91', 'Decímetro cúbico por metro cúbico', NULL, 'dm³/m³'),
('J92', 'Decímetro cúbico por minuto', NULL, 'dm³/min'),
('J93', 'Decímetro cúbico por segundo', NULL, 'dm³/s'),
('J94', 'Dina centímetro', NULL, 'Dyn · cm'),
('J95', 'Onza (fluido, UK) por día', NULL, 'fl oz (UK)/d'),
('J96', 'Onza (fluido, UK) por hora', NULL, 'fl oz (UK)/h'),
('J97', 'Onza (fluido, UK) por minuto', NULL, 'fl oz (UK)/min'),
('J98', 'Onza (fluido, UK) por segundo', NULL, 'fl oz (UK)/s'),
('J99', 'Onza (fluido, estados unidos) por día', NULL, 'fl oz (US)/d'),
('JB', 'Jumbo', NULL, NULL),
('JE', 'Joule por kelvin', 'Es el aumento de entropía de un sistema que recibe una cantidad de calor de 1 joule, a la temperatura termodinámica constante de 1 kelvin, siempre que en el sistema no tenga lugar ninguna transformación irreversible.', 'J/K'),
('JK', 'Megajoule por kilogramo', NULL, 'MJ/kg'),
('JM', 'Megajoule por metro cúbico', NULL, 'MJ/m³'),
('JNT', 'Junta de tubería', 'Un recuento del número de juntas de la tubería.', NULL),
('Jo', 'Articulación', NULL, NULL),
('JOU', 'Joule', 'Es el trabajo producido por una fuerza de 1 newton, cuyo punto de aplicación se desplaza 1 metro en la dirección de la fuerza.', 'J'),
('JPS', 'Cien metros', 'Unidad de conteo que define el número de longitudes de 100 metros.', NULL),
('JWL', 'Número de joyas', 'Unidad de cuenta que define el número de joyas (joya: piedra preciosa).', NULL),
('K1', 'Demanda de kilowatt', 'Unidad de medida que define la carga de potencia medida a intervalos predeterminados.', NULL),
('K10', 'Onza (fluido, estados unidos) por hora', NULL, 'fl oz (US)/h'),
('K11', 'Onza (fluido, estados unidos) por minuto', NULL, 'fl oz (US)/min'),
('K12', 'Onza (fluido, estados unidos) por segundo', NULL, 'fl oz (US)/s'),
('K13', 'Pie por grado fahrenheit', NULL, 'ft/°F'),
('K14', 'Pie por hora', NULL, 'ft/h'),
('K15', 'Pie libra-fuerza por hora', NULL, 'ft·lbf/h'),
('K16', 'Pie libra-fuerza por minuto', NULL, 'ft·lbf/min'),
('K17', 'Pie por psi (libra por pulgada cuadrada)', NULL, 'ft/psi'),
('K18', 'Pie por segundo grado fahrenheit', NULL, '(ft/s)/°F'),
('K19', 'Pie por segundo psi (libra por pulgada cuadrada)', NULL, '(ft/s)/psi'),
('K2', 'Kilovoltios amperios demanda reactiva', 'Unidad de medida que define la demanda de potencia reactiva igual a un kilovoltioio de potencia reactiva.', NULL),
('K20', 'Reciprocidad del pie cuadrado', NULL, '1/ft³'),
('K21', 'Pie cúbico por grado fahrenheit', NULL, 'ft³/°F'),
('K22', 'Pie cúbico por día', NULL, 'ft³/d'),
('K23', 'Pie cúbico por psi (libra por pulgada cuadrada)', NULL, 'ft³/psi'),
('K24', 'Pie de agua', NULL, 'Ft H $ ₂ $ O'),
('K25', 'Pie de mercurio', NULL, 'Ft Hg'),
('K26', 'Galón (UK) por día', NULL, 'gal (UK)/d'),
('K27', 'Galón (UK) por hora', NULL, 'gal (UK)/h'),
('K28', 'Galón (UK) por segundo', NULL, 'gal (UK)/s'),
('K3', 'Kilovoltio amperio hora reactivo', 'Unidad de medida que define la energía reactiva acumulada igual a un kilovoltioio de potencia reactiva por hora.', 'kvar·h'),
('K30', 'Galón (líquido, EUA) por segundo', NULL, 'gal (US liq.)/s'),
('K31', 'Gramo-fuerza por centímetro cuadrado', NULL, 'gf/cm²'),
('K32', 'Gill (UK) por día', 'Gill es una unidad de volumen inglesa en el sistema imperial y en los Estados Unidos. La versión imperial usada en el UK es de 5 onzas líquidas, y es equivalente a 142,0653125 ml; mientras que en los EUA es de 4 onzas líquidas, y es equivalente a 118,29411825 ml.', 'gi (UK)/d'),
('K33', 'Gill (UK) por hora', NULL, 'gi (UK)/h'),
('K34', 'Gill (UK) por minuto', NULL, 'gi (UK)/min'),
('K35', 'Gill (UK) por segundo', NULL, 'gi (UK)/s'),
('K36', 'Gill (estados unidos) por día', NULL, 'gi (US)/d'),
('K37', 'Gill (estados unidos) por hora', NULL, 'gi (US)/h'),
('K38', 'Gill (estados unidos) por minuto', NULL, 'gi (US)/min'),
('K39', 'Gill (estados unidos) por segundo', NULL, 'gi (US)/s'),
('K40', 'Aceleración estándar de la caída libre', 'Es la aceleración nominal de la gravedad de un objeto en un vacío cerca de la superficie de la Tierra.', 'gn'),
('K41', 'Grano por galón (EUA)', NULL, 'gr/gal (US)'),
('K42', 'Caballo de fuerza de caldera', 'Es la cantidad de energía requerida para producir 34,5 libras (15,65 kg) de vapor por hora a presión y temperatura 0 psig (0 bar) y 212 o F (100 o C) - con agua de alimentación a presión 0 psig y la temperatura 212 o F.', 'boiler hp'),
('K43', 'Caballo de fuerza (eléctrico)', 'Es una unidad de medida de potencia (la velocidad a la que el trabajo se realiza).', 'electric hp'),
('K45', 'Pulgada por grado fahrenheit', NULL, 'in/°F'),
('K46', 'Pulgada por psi (libra por pulgada cuadrada)', NULL, 'in/psi'),
('K47', 'Pulgada por segundo grado fahrenheit', NULL, '(in/s)/°F'),
('K48', 'Pulgada por segundo psi (libra por pulgada cuadrada)', NULL, '(in/s)/psi'),
('K49', 'Reciprocidad de la pulgada cuadrada', NULL, '1/in³'),
('K5', 'Kilovoltios amperios (reactivos)', 'Utilice kilovar (código común KVR)', 'Kvar'),
('K50', 'Kilobaud', 'Unidad de velocidad de transmisión de señal igual a 10³ (1000) eventos de señalización por segundo.', 'kBd'),
('K51', 'Kilocaloría (significado)', NULL, 'kcal'),
('K52', 'Kilocaloría (tabla internacional) por hora metro grado celsius', NULL, 'kcal/(m·h·°C)'),
('K53', 'Kilocaloría (termoquímico)', NULL, 'kcalth'),
('K54', 'Kilocaloría (termoquímica) por minuto', NULL, 'kcalth/min'),
('K55', 'Kilocaloría (termoquímica) por segundo', NULL, 'kcalth/s'),
('K58', 'KiloMol por hora', NULL, 'kmol/h'),
('K59', 'KiloMol por metro cúbico kelvin', NULL, '(kmol/m³)/K'),
('K6', 'Kilolitro', NULL, 'kl'),
('K60', 'KiloMol por metro cúbico bar', NULL, '(kmol/m³)/bar'),
('K61', 'KiloMol por minuto', NULL, 'kmol/min'),
('K62', 'Litro por litro', NULL, 'l/l'),
('K63', 'Reciprocidad del litro', NULL, '1/l'),
('K64', 'Libra (avoirdupois) por grado fahrenheit', NULL, 'lb/°F'),
('K65', 'Libra (avoirdupois) pie cuadrado', NULL, 'lb·ft²'),
('K66', 'Libra (avoirdupois) por día', NULL, 'lb/d'),
('K67', 'Libra por pie hora', NULL, 'lb/(ft·h)'),
('K68', 'Libra por pie segundo', NULL, 'lb/(ft·s)'),
('K69', 'Libra (avoirdupois) por pie cúbico grado fahrenheit', NULL, '(lb/ft³)/°F'),
('K70', 'Libra (avoirdupois) por pie cúbico psi', NULL, '(lb/ft³)/psi'),
('K71', 'Libra (avoirdupois) por galón (UK)', NULL, 'lb/gal (UK)'),
('K73', 'Libra (avoirdupois) por hora grados fahrenheit', NULL, '(lb/h)/°F'),
('K74', 'Libra (avoirdupois) por hora libra-fuerza por pulgada cuadrada', NULL, '(lb/h)/psi'),
('K75', 'Libra (avoirdupois) por pulgada cúbica grado fahrenheit', NULL, '(lb/in³)/°F'),
('K76', 'Libra (avoirdupois) por pulgada cúbica psi', NULL, '(lb/in³)/psi'),
('K77', 'Libra (avoirdupois) por psi', NULL, 'lb/psi'),
('K78', 'Libra (avoirdupois) por minuto', NULL, 'lb/min'),
('K79', 'Libra (avoirdupois) por minuto grados fahrenheit', NULL, 'lb/(min·°F)'),
('K80', 'Libra (avoirdupois) por minuto libra-fuerza por pulgada cuadrada', NULL, '(lb/min)/psi'),
('K81', 'Libra (avoirdupois) por segundo', NULL, 'lb/s'),
('K82', 'Libra (avoirdupois)por segundo grados fahrenheit', NULL, '(lb/s)/°F'),
('K83', 'Libra (avoirdupois) por segundo libra-fuerza por pulgada cuadrada', NULL, '(lb/s)/psi'),
('K84', 'Libra por yarda cúbica', NULL, 'lb/yd³'),
('K85', 'Libra-fuerza por pie cuadrado', NULL, 'lbf/ft²'),
('K86', 'Libra-fuerza por pulgada cuadrada grados fahrenheit', NULL, 'psi/°F'),
('K87', 'Libra-fuerza por pulgada cuadrada pulgada cúbica por segundo', NULL, 'psi·in³/s'),
('K88', 'Libra-fuerza por pulgada cuadrada litro por segundo', NULL, 'psi·l/s'),
('K89', 'Libra-fuerza por pulgada cuadrada metro cúbico por segundo', NULL, 'psi·m³/s')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();