INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('N95', 'Amperio minuto', 'Unidad de carga eléctrica que define la cantidad de carga acumulada por un flujo constante de un amperio por un minuto.', 'A·min'),
('N96', 'Biot', 'El número de Biot (Bi) es un número adimensional utilizado en cálculos de transmisión de calor. Su nombre hace honor al físico francés Jean Baptiste Biot (1774-1862) y relaciona la transferencia de calor por conducción dentro de un cuerpo y la transferencia de calor por convección en la superficie de dicho cuerpo. Biot en 1804, analizó la interacción entre la conducción en un sólido y la convección en sus superficies.', 'Bi'),
('N97', 'Gilbert', 'CGS (Centímetro-Gram-Segundo sistema) unidad de la fuerza magnetomotriz, que se define por el trabajo para aumentar el potencial magnético de un polo común positivo con 1 erg.', 'Gi'),
('N98', 'Voltio por pascal', 'Unidad derivada del sistema internacional, voltio, dividido entre la unidad derivada del sistema internacional, pascal.', 'V/Pa'),
('N99', 'Picovoltio', '0.000 000 000 001 veces de la unidad derivada del sistema internacional, voltio.', 'pV'),
('NA', 'Miligramo por kilogramo', NULL, 'mg/kg'),
('NAR', 'Número de artículos', 'Unidad de conteo que define el número de artículos', NULL),
('NB', 'barcaza', NULL, NULL),
('NBB', 'Número de bobinas', NULL, NULL),
('NC', 'Carro', NULL, NULL),
('NCL', 'Número de celulas', 'Unidad de conteo que define el número de células (célula: un espacio cerrado o circunscrito, cavidad o volumen)', NULL),
('ND', 'Barril neto', NULL, NULL),
('NE', 'Litro neto', NULL, NULL),
('NEW', 'Newton', NULL, 'N'),
('NF', 'Mensaje', 'Unidad de conteo que define el número de mensajes', NULL),
('NG', 'Galón neto (us)', NULL, NULL),
('NH', 'Hora del mensaje', NULL, NULL),
('NI', 'Galón imperial neto', NULL, NULL),
('NIL', 'Nil', 'Unidad de conteo que define el número de instancias de nada', '()'),
('NIU', 'Número de unidades internacionales', 'Unidad de conteo que define el número de unidades internacionales', NULL),
('NJ', 'Número de pantallas', NULL, NULL),
('NL', 'Carga', 'Unidad de volumen que define el número de cargas(carga: cantidad de artículos transportados o procesados al mismo tiempo)', NULL),
('NM3', 'Metro cúbico normalizado', 'Metros cúbicos normalizados (temperatura 0 ° C y presión 101325 milibares)', NULL),
('NMI', 'Milla náutica', 'Es una unidad de longitud empleada en navegación marítima y aérea.', 'n mile'),
('NMP', 'Número de paquetes', 'Unidad que define el número de paquetes (paquetes: colección de objetos empaquetados)', NULL),
('NN', 'tren', NULL, NULL),
('NPR', 'Número de parejas', 'Una unidad de cuenta que define el número de pares (par: elemento descrito por dos).', NULL),
('NPT', 'Número de partes', 'Unidad de conteo que define el número de partes (partes: componente de larga entidad)', NULL),
('NQ', 'Mho', NULL, NULL),
('NR', 'Micromho', NULL, NULL),
('NT', 'Tonelada neta', 'Unidad de masa equivalente a 2000 libras, ver (US). Convencion Internacional referencia sobre el arqueo de los busques', NULL),
('NTT', 'Tonelada de registro neto', 'Una unidad de masa igual al total de las imágenes cúbicas después de las deducciones, donde 1 registro t es igual a 100 pies cúbicos. Véase el Convenio internacional sobre el arqueo de los buques.', NULL),
('NV', 'vehículo', NULL, NULL),
('NY', 'Libra por tonelada métrica al aire seco', NULL, NULL),
('NX', 'Parte por mil', 'Unidad de proporcion igual a 10 Sínonimo: por milla', '‰'),
('OA', 'Panel', 'Unidade de conteo que define el n[umero de paneles', NULL),
('ODE', 'Equvalente de agotamiento del ozona', 'Unidad de masa que define el potencial de agotamiento del ozono en kilogramos de un producto en relación con el agotamiento calculado para la sustancia de referencia Triclorofluorometano (CFC-11).', NULL),
('Ohm', 'Ohm', 'es la resistencia eléctrica que existe entre dos puntos de un conductor cuando una diferencia de potencial constante de 1 volt aplicada entre estos dos puntos produce, en dicho conductor, una corriente de intensidad 1 amperio, cuando no haya fuerza electromotriz en el conductor.', 'Ω'),
('ON', 'Onza por yarda cuadrada', NULL, 'oz/yd²'),
('ONZ', 'Onza (avoirdupois)', 'Es una unidad de masa usada desde la Antigua Roma para pesar con mayor precisión las mercancías y otros artículos, especialmente si su peso era menor que una libra romana', 'oz'),
('OP', 'Dos paquetes', NULL, NULL),
('OPM', 'Oscilaciones por minuto', 'número de variaciones, perturbaciones o fluctuación en el tiempo de un medio o sistema', 'o/min'),
('OT', 'Hora extra', 'Unidad de tiempo que define el n[umero de horas extras', NULL),
('OZ', 'Onza AV', 'Una unidad de medida igual a 1/16 de una libra o aproximadamente 28.3495 gramos (av = avoirdupois). Use onza (código común ONZ).', NULL),
('OZA', 'Onza líquida (estados unidos)', NULL, 'fl oz (US)'),
('OZI', 'Onza líquida (UK)', NULL, 'fl oz (UK)'),
('P0', 'Página electrónica', NULL, NULL),
('P1', 'Tanto por ciento', 'Unidad de proporcion equivalente a 0.01', '% or pct'),
('P10', 'Culombio por metro', 'Unidad derivada, coulomb dividida por la unidad base, metro.', 'C/m'),
('P11', 'Kiloweber', '1000 veces la unidad derivada weber, del sistema internacional de unidades.', 'kWb'),
('P12', 'Gamma', 'Unidad de densidad de flujo magnético.', 'γ'),
('P13', 'Kilotesla', '1000 veces la unidad derivada tesla.', 'kT'),
('P14', 'Joule por segundo', 'Cociente de la unidad derivada joule dividido entre la unidad base, segundo, ambas del sistema internacional.', 'J/s'),
('P15', 'Joule por minuto', 'Cociente de la unidad derivada, joule, dividido entre la unidad minuto.', 'J/min'),
('P16', 'Joule por hora', 'Cociente de la unidad derivada, joule, dividido entre la unidad hora.', 'J/h'),
('P17', 'Joule por día', 'Cociente de la unidad derivada, joule, dividido entre la unidad día.', 'J/d'),
('P18', 'Kilojoule por segundo', 'Cociente entre 1000 veces de la unida derivada, joule, dividido por la unidad base segundo.', 'kJ/s'),
('P19', 'Kilojoule por minuto', 'Cociente entre 1000 veces de la unida derivada, joule, dividido por la unidad minuto.', 'kJ/min'),
('P2', 'Libra por pie', NULL, 'lb/ft'),
('P20', 'Kilojoule por hora', 'Cociente entre 1000 veces de la unida derivada, joule, dividido por la unidad hora.', 'kJ/h'),
('P21', 'Kilojoule por dia', 'Cociente entre 1000 veces de la unida derivada, joule, dividido por la unidad día', 'kJ/d'),
('P22', 'NanoOhm', '0.000 000 001 veces de la unidad derivada Ohm.', 'nΩ'),
('P23', 'Ohm circular-mil por pie', 'Unidad de resistividad.', 'Ω·cmil/ft'),
('P24', 'Kilohenry', '1000 veces la unidad derivada, henry del sistema internacional.', 'kH'),
('P25', 'Lumen por pie cuadrado', 'Unidad derivada, lumen dividido por la potencia de la unidad pie, al exponente 2, de acuerdo con el sistema anglo-americano y el sistema imperial.', 'lm/ft²'),
('P26', 'Foto', 'es una unidad de iluminancia  o flujo luminoso a través de un área. No es una unidad del sistema internacional, sino que se asocia con el antiguo segundo sistema centímetro gramo de unidades .', 'ph'),
('P27', 'Vela (medida)', 'Es una unidad de medida de iluminancia que no pertenece al Sistema Internacional de Unidades, pero es ampliamente usada en Estados Unidos para fotografía, cine, televisión, conservación luminosa, ingeniería de la construcción, etc. Una vela significa "el reparto de iluminación sobre una superficie equivalente a una candela, y a un pie de distancia".', 'ftc'),
('P28', 'Candela por pulgada cuadrada', 'Unidad base, candela dividido por la potencia de la unidad de pulgada al exponente 2 de acuerdo con el sistema de unidades Anglo-Americanas e Imperial.', 'cd/in²'),
('P29', 'Footlambert', 'Unidad de luminancia de acuerdo con el sistema Anglo-Americano de unidades, y se define como la luminancia emitida o reflejada de un lumen por pie cuadrado.', 'ftL'),
('P3', 'Tres paquetes', NULL, NULL),
('P30', 'Lambert', 'Unidad de luminancia CGS (Centímetro-Gram-Segundo sistema), definida como la luminancia emitida o reflejada de un lumen por centímetro cuadrado.', 'Lb'),
('P31', 'Stilb', 'Unidad de luminancia CGS (Centímetro-Gram-Segundo sistema), definida como la luminancia emitida o reflejada de un lumen por centímetro cuadrado.', 'sb'),
('P32', 'Candela por pie cuadrado', 'Unidad base, candela dividido por la potencia de la unidad pie al exponente 2 , de acuerdo con el sistema anglo-americano y el sistema imperial de unidades', 'cd/ft²'),
('P33', 'Kilocandela', '1000 veces la unidad base, candela, del sistema internacional.', 'kcd'),
('P34', 'Milicandela', '0.001 veces la unidad base , candela, del sistema internacional.', 'mcd'),
('P35', 'Hefner-kerze', 'Obsoleto, unidad de potencia en Alemania relacionado con DIN 1301-3:1979: 1 HK = 0,903 candela.', 'HK'),
('P36', 'Candela internacional', 'Unidad obsoleta de la potencia en Alemania relativa a DIN 1301-3: 1979: 1 HK = 1.019 candela.', 'IK'),
('P37', 'Unidad térmica británica (tabla internacional) por pie cuadrado', 'Unidad de la transmisión de energía relacionado de muestreo de áreas de acuerdo con el sistema imperial de unidades.', 'BtuIT/ft²'),
('P38', 'Unidad térmica británica (termoquímica) por pie cuadrado', 'Unidad de la transmisión de energía relacionado de muestreo de áreas de acuerdo con el sistema imperial de unidades.', 'Btuth/ft²'),
('P39', 'Caloría (termoquímica) por centímetro cuadrado', 'Unidad de la transmisión de energía relacionado de muestreo de áreas de acuerdo con el sistema imperial de unidades.', 'calth/cm²'),
('P4', 'paquete de cuatro', NULL, NULL),
('P40', 'Langley', 'CGS (Centímetro-Gramo-Segundo sistema) unidad de la transmisión de energía relacionada con el área (como una medida de la cantidad incidente de calor de la radiación solar en la superficie de la tierra).', 'Ly'),
('P41', 'Década (logaritmica)', 'Una escala logarítmica es una escala de medida que utiliza el logaritmo de una cantidad física en lugar de la propia cantidad.', 'dec'),
('P42', 'Pascal por segundo cuadrado', 'Unidad del conjunto como un producto de la potencia de derivado unidad pascal SI con exponente 2 y la unidad base segunda SI.', 'Pa²·s'),
('P43', 'Bel por metro', 'Una unidad Bel dividida por la unidad básica del sistema internacional (metros).', 'B/m'),
('P44', 'Libra Mol', 'Unidad que no forma parte del sistema internacional, cantidad de una sustancia relacionada que un mol libra de una composición química corresponde a la misma cantidad de libras como el peso molcular de una molécula de esta composición en unidades de masa atómica.', 'lbmol'),
('P45', 'Libra de Mol por segundo', 'No forma parte del sistema internacional de unidades.
Unidad de flujo del flujo molar que se refiere a que una libra mol de una composición química el mismo número de libras corresponde con el peso molcular de una molécula de esta composición en la masa atómica de unidades.', 'lbmol/s'),
('P46', 'Libra Mol por minuto', 'No forma parte del sistema internacional de unidades.
Unidad de flujo del flujo molar que se refiere a que una libra mol de una composición química el mismo número de libras corresponde como el peso molcular de una molécula de esta composición en la masa atómica de unidades.', 'lbmol/h'),
('P47', 'KiloMol por kilogramo', '1000 veces la división de la unidad base mol por la base de la unidad kilogramo.', 'kmol/kg'),
('P48', 'Libra de Mol por libra', 'Unidad del flujo molar material dividido por la libra avoirdupois para la masa de acuerdo con el sistema de unidades avoirdupois no SI-conforme.', 'lbmol/lb'),
('P49', 'Newton metro cuadrado por amperio', 'Producto de la division de la unidad Newton y la unidad base metro 
Producto de la unidad derivada newton y la potencia del medidor de la unidad base con el exponente 2 dividido por el amperio de la unidad base.', 'N·m²/A'),
('P5', 'Paquete de cinco', 'Unidad de conteo que define el número de paquetes-cinco (paquete-cinco: set de cinco artículos empaquetados siempre)', NULL),
('P50', 'Metro weber', 'Producto de la división entre  la unidad Weber y la unidad Metro.', 'Wb·m'),
('P51', 'Mol por kilogramo pascal', 'Unidad base mol dividido por el producto de la unidad base SI kilogramo y la unidad derivada pascal SI.', '(mol/kg)/Pa'),
('P52', 'Mol por metro cúbico pascal', 'unidad base mol dividido por el producto de la potencia de la unidad base SI metros con exponente 3 y la unidad derivada pascal SI.', '(mol/m³)/Pa'),
('P53', 'Unit por segundo', 'Sistema CGS (Centímetro-Gram-Segundo sistema) para el flujo magnético de un polo magnético (según la interacción de polos idénticos de 1 din a una distancia de un cm).', 'unit pole'),
('P54', 'MiliGray por segundo', '0.0001 veces de la unidad derivada Gray dividido por la unidad de base segundos.', 'mGy/s'),
('P55', 'MicroGray por segundo', '0.000 001 veces de la unidad derivada Gray dividido por la unidad de base segundos.', 'µGy/s'),
('P56', 'NanoGray por segundo', '0.000 000 001 veces de la unidad derivada Gray dividido por la unidad de base segundos.', 'nGy/s'),
('P57', 'Gray por minuto', 'Derivada del la unidad Gray dividida por la unidad minutos.', 'Gy/min')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();