INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('XBW', 'Caja para líquidos', NULL, NULL),
('XBX', 'Caja', NULL, NULL),
('XBY', 'Tablero, con fleje/ agrupados/ armados', NULL, NULL),
('XBZ', 'Barras, con fleje/ agrupados/ armados', NULL, NULL),
('XCA', 'Lata rectangular', NULL, NULL),
('XCB', 'Cajón para cerveza', NULL, NULL),
('XCC', 'Mantequera', NULL, NULL),
('XCD', 'Lata con mango y boquilla', NULL, NULL),
('XCE', 'Cesto tejido', NULL, NULL),
('XCF', 'Cofre', NULL, NULL),
('XCG', 'Contenedor tipo Jaula', NULL, NULL),
('XCH', 'Cajonera', NULL, NULL),
('XCI', 'Frasco', NULL, NULL),
('XCJ', 'Ataúd', NULL, NULL),
('XCK', 'Barrica', NULL, NULL),
('XCL', 'Espiral', NULL, NULL),
('XCM', 'Paquete de tarjetas', 'Paquete plano normalmente hecho de cartón desde / hacia el cual el producto es a menudo colgado o unido.', NULL),
('XCN', 'Contenedor, no especificado como equipo de transporte', NULL, NULL),
('XCO', 'Garrafón no protegido', NULL, NULL),
('XCP', 'Garrafón protegido', NULL, NULL),
('XCQ', 'Cartucho', 'Paquete que contiene una carga tal como un explosivo propulsor para armas de fuego o tóner de tinta para una impresora.', NULL),
('XCR', 'Cajón', NULL, NULL),
('XCS', 'Estuche', NULL, NULL),
('XCT', 'Cartón', NULL, NULL),
('XCU', 'Vaso', NULL, NULL),
('XCV', 'Cubierta', NULL, NULL),
('XCW', 'Jaula estilo rodillo', NULL, NULL),
('XCX', 'Lata cilíndrica', NULL, NULL),
('XCY', 'Cilindro', NULL, NULL),
('XCZ', 'Lona', NULL, NULL),
('XDA', 'Cajón multicapa de plástico', NULL, NULL),
('XDB', 'Cajón de varias capas de madera', NULL, NULL),
('XDC', 'Cajón multicapa de cartón', NULL, NULL),
('XDG', 'Jaula, Según la clasificación de la compañía (Commonwealth Handling Equipment Pool (CHEP))', NULL, NULL),
('XDH', 'Caja, Según la clasificación de la compañía (CHEP), Eurobox', 'Caja montada sobre una base de pallet Según la clasificación de la compañía (CHEP).', NULL),
('XDI', 'Tambor de hierro', NULL, NULL),
('XDJ', 'damajuana o garrafa, no protegido', NULL, NULL),
('XDK', 'Cajón a granel, cartón', NULL, NULL),
('XDL', 'Cajas de plástico', NULL, NULL),
('XDM', 'Cajones a granel de madera', NULL, NULL),
('XDN', 'Dispensador', NULL, NULL),
('XDP', 'damajuana o garrafa, protegido', NULL, NULL),
('XDR', 'Tambor', NULL, NULL),
('XDS', 'Bandeja de una capa sin cubierta y de plástico', NULL, NULL),
('XDT', 'Bandeja de una capa sin cubierta y de madera', NULL, NULL),
('XDU', 'Bandeja de una capa sin cubierta y  poliestireno', NULL, NULL),
('XDV', 'Bandeja de una capa sin cubierta y de cartón', NULL, NULL),
('XDW', 'Bandeja de dos capas sin tapa y con bandeja de plástico', NULL, NULL),
('XDX', 'Bandeja de dos capas sin cubierta y de madera', NULL, NULL),
('XDY', 'Bandeja de dos capas sin cubierta y de cartón', NULL, NULL),
('XEC', 'Bolsa de plástico', NULL, NULL),
('XED', 'Estuche, con pallet de base', NULL, NULL),
('XEE', 'Estuche, con pallet base de madera', NULL, NULL),
('XEF', 'Estuche, con pallet base de cartón', NULL, NULL),
('XEG', 'Estuche, con pallet base de plástico', NULL, NULL),
('XEH', 'Estuche, con pallet base de metal', NULL, NULL),
('XEI', 'Estuche isotérmico', NULL, NULL),
('XEN', 'Sobre', NULL, NULL),
('XFB', 'Bolsa flexible', 'Bolsa de contención flexible hecha de plástico, usado típicamente para el transporte de mercancías no peligrosas a granel, que usan contenedores de transporte de tamaño estándar.', NULL),
('XFC', 'Cajón para fruta', NULL, NULL),
('XFD', 'Cajón enmarcado', NULL, NULL),
('XFE', 'Tanque flexible', 'Contenedor flexible de plástico, usado típicamente para el transporte de cargas no peligrosas a granel usando contenedores de transporte de tamaño estándar.', NULL),
('XFI', 'Firkin', 'Barril de 41 litros', NULL),
('XFL', 'Matraz', NULL, NULL),
('XFO', 'Cajón para zapatos', NULL, NULL),
('XFP', 'Caja auxiliar para película fotográfica', NULL, NULL),
('XFR', 'Marco', NULL, NULL),
('XFT', 'Contenedor para alimentos', NULL, NULL),
('XFW', 'Carro de cama plana', 'Módulo con ruedas en el que las bandejas u otros artículos de forma regular se empacan para fines de transporte.', NULL),
('XFX', 'Bolsa flexible tipo contenedor', NULL, NULL),
('XGB', 'Botella para gas', 'Cilindro metálico de cuello estrecho para la retención de gas licuado o comprimido.', NULL),
('XGI', 'Viga', NULL, NULL),
('XGL', 'Contenedor tipo galón', 'Contenedor con una capacidad de un galón.', NULL),
('XGR', 'Recipiente de vidrio', 'Recipiente de contención de vidrio para retener sustancias o artículos.', NULL),
('XGU', 'Bandeja contenedor para apilar horizontalmente objetos planos', 'Bandeja para contiene objetos planos apilados uno encima del otro.', NULL),
('XGY', 'Costal de Yute', 'Hecho de yute, usado para transportar mercancías gruesas, tales como granos, patatas, y otros productos agrícolas.', NULL),
('XGZ', 'Vigas con correas o agrupadas', NULL, NULL),
('XHA', 'Cesta con mango y de plástico', NULL, NULL),
('XHB', 'Cesta con mango y de madera', NULL, NULL),
('XHC', 'Cesta  con asa y de  cartón', NULL, NULL),
('XHG', 'Hogshead', 'Barril de 1/4 de tonel', NULL),
('XHN', 'Gancho', 'Artefacto, cuya forma con un gancho en la parte superior, tiene el propósito de colgar artículos de un carril.', NULL),
('XHR', 'Cesto', NULL, NULL),
('XIA', 'Paquete con pantalla y de madera', NULL, NULL),
('XIB', 'Paquete  con pantalla y de cartón', NULL, NULL),
('XIC', 'Paquete con pantalla y de plástico', NULL, NULL),
('XID', 'Paquete con pantalla y de metal', NULL, NULL),
('XIE', 'Paquete de mostrador.', NULL, NULL),
('XIF', 'Envase para alimentos', 'Envase flexible tubular o de piel, posiblemente transparente, a menudo utilizado para contener alimentos (por ejemplo salami).', NULL),
('XIG', 'Paquete envuelto en papel', NULL, NULL),
('XIH', 'Tambor de plástico', NULL, NULL),
('XIK', 'Paquete de cartón con los agujeros para botellas', 'Material de empaque realizado en cartón que facilita la separación de botellas individuales de vidrio o plástico.', NULL),
('XIL', 'Bandeja rígida con tapa y apilable (CEN TS 14482: 2002)', 'Bandeja rígida apilable empotrada compatible con CEN TS 14482: 2002.', NULL),
('XIN', 'Lingote', NULL, NULL),
('XIZ', 'Lingotes  con correas/ agrupados', NULL, NULL),
('XJB', 'Bolsa jumbo', 'Bolsa de contención flexible, ampliamente utilizada para almacenamiento, transporte y manipulación de materiales en polvo, escamas o granulares. Típicamente construido a partir de tejido de polipropileno (PP) tejido en forma de bolsas cúbicas.', NULL),
('XJC', 'Bidón rectangular', NULL, NULL),
('XJG', 'Jarra', NULL, NULL),
('XJR', 'Tarro', NULL, NULL),
('XJT', 'Bolsa de yute', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();