INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('P58', 'MiliGray por minuto', '0.001 veces de la unidad derivada de Gray dividida por la unidad de minutos.', 'mGy/min'),
('P59', 'Microgray por minuto', '0.000 001 veces de la unidad derivada gris SI dividido por la unidad de minutos.', 'µGy/min'),
('P6', 'paquete de seis', NULL, NULL),
('P60', 'Nanogray por minuto', '0.000 000 001 veces de la unidad derivada gris SI dividido por la unidad de minutos.', 'nGy/min'),
('P61', 'Gray por hora', 'Derivada de la unidad Gray por la derivada de la unidad hora.', 'Gy/h'),
('P62', 'MiliGray por hora', '0.001 veces de la unidad derivada Gray por la unidad hora', 'mGy/h'),
('P63', 'Micro gray por hora', '0.000 001 veces de la unidad derivada gris SI dividida por la hora unidad.', 'µGy/h'),
('P64', 'Nanogray por hora', '0.000 000 001 veces de la unidad derivada gris SI dividida por la hora unidad.', 'nGy/h'),
('P65', 'Sievert por segundo', 'Derivada de la unidad Sievert dividida por la unidad de base segundos.', 'Sv/s'),
('P66', 'MilliSievert por segundo', '0.001 veces de la unidad derivada Sievert dividida por la unidad de base segundos.', 'mSv/s'),
('P67', 'MicroSievert por segundo', '0.000 001 veces de la unidad derivada Sievert dividido por la unidad de base segundos.', 'µSv/s'),
('P68', 'NanoSievert por segundo', '0.000 000 001 veces de la unidad derivada Sievert dividido por la unidad de base segundos.', 'nSv/s'),
('P69', 'Rem por segundo', 'Unidad para la tasa de estaño equivalente y relativa a DIN 1301-3: 1979: 1 rem / s = 0,01 J / (kg · s) = 1 Sv / s.', 'rem/s'),
('P7', 'Paquete de siete', NULL, NULL),
('P70', 'Sievert por hora', 'Derivado unidad Sievert dividida por la hora unidad.', 'Sv/h'),
('P71', 'MilliSievert por hora', '0.001 veces de la unidad derivada Sievert SI dividida por la unidad hora.', 'mSv/h'),
('P72', 'Micro Sievert por hora', '0.000 001 veces de la unidad derivada Sievert dividida por la unidad hora.', 'µSv/h'),
('P73', 'NanoSievert por hora', '0.000 000 001 veces de la unidad derivada Sievert dividida por la unidad hora.', 'nSv/h'),
('P74', 'Sievert por minuto', 'Derivado unidad Sievert dividido por la unidad minuto.', 'Sv/min'),
('P75', 'MilliSievert por minuto', '0.001 veces de la unidad derivada Sievert dividido por la unidad de minutos.', 'mSv/min'),
('P76', 'MicroSievert por minuto', '0.000 001 veces de la unidad derivada Sievert dividido por la unidad de minutos.', 'µSv/min'),
('P77', 'NanoSievert pominut', '0.000 000 001 veces de la unidad derivada Sievert dividido por la unidad de minutos.', 'nSv/min'),
('P78', 'Reciprocidad por segundo', 'Complemento de la potencia de la unidad pulgada según el sistema Anglo-Americano e Imperial de unidades por exponente 2.', '1/in²'),
('P79', 'Pascal metro cuadrado por kilogramo', 'Unidad del índice de estallido como unidad derivada para pascal presión relacionada con la sustancia, representado como cociente de la unidad base SI kilogramo dividida por la potencia de la unidad base SI metros por exponente 2.', 'Pa/(kg/m²)'),
('P8', 'Paquete de ocho', NULL, NULL),
('P80', 'Milipascal por metro.', '0.001 veces de la unidad derivada pascal dividido por la unidad de base metros.', 'mPa/m'),
('P81', 'Kilopascal por metro.', '1000 veces de la unidad derivada pascal dividido por la unidad de base metros.', 'kPa/m'),
('P82', 'Hectopascal por metro.', '100 veces de la unidad derivada pascal SI dividido por la unidad de base metros.', 'hPa/m'),
('P83', 'Admosfera estandar por metro.', 'Unidad anticuadas de la presión dividida por la unidad de base metros.', 'Atm/m'),
('P84', 'Admosfera tecnica por metro.', 'unidad obsoleta y no legal de la presión que se genera por una columna de agua de 10 metros dividida por la unidad de base metros.', 'at/m'),
('P85', 'Torr por metro.', 'Unidad de la presión dividida por la unidad de base metros.', 'Torr/m'),
('P86', 'Psi por pulgada', 'Unidad de compuesto para la presión (libra de fuerza de acuerdo con el sistema de la unidad angloamericana dividida por la potencia de la unidad de pulgada de acuerdo con el sistema angloamericano e Imperial de unidades con el exponente 2) dividido por la unidad de pulgada de acuerdo con la sistema angloamericano e Imperial de unidades.', 'psi/in'),
('P87', 'Metro cúbico por segundo de metro cuadrado', 'Unidad de volumen de flujo metros cúbicos por segundo relacionado con la superficie de transmisión en metros cuadrados.', '(m³/s)/m²'),
('P88', 'Rhe', 'Unidad no conforme a SI de fluidez de viscosidad dinámica', 'rhe'),
('P89', 'Libra por metro cúbico de pulgada', 'Unidad para el momento de rotación relacionado con la longitud según el sistema de unidades Anglo-Americanas e Imperial.', 'lbf·ft/in'),
('P9', 'Nueve paquetes', NULL, NULL),
('P90', 'Libra-fuerza por pulgada cuadrada', 'Unidad para el momento de rotación relacionado con la longitud según el sistema de unidades Anglo-Americanas e Imperial.', 'lbf·in/in'),
('P91', 'Permanente (0°c)', 'Unidad tradicional para la capacidad de un material para permitir la transición del vapor, definida a una temperatura de 0°C como transmitancia del vapor en la cual la masa de un grano de vapor penetra en un área de un pie cuadrado a una presión de mercurio de una pulgada por hora.', 'perm (0 ºC)'),
('P92', 'Permanente (23°c)', 'Unidad tradicional para la capacidad de un material para permitir la transición del vapor, definida a una temperatura de 23°C como transmitancia del vapor en la cual la masa de un grano de vapor penetra en un área de un pie cuadrado a una presión de mercurio de una pulgada por hora.', 'perm (23 ºC)'),
('P93', 'Byte por segundo', 'Son utilizados para expresar la velocidad de transmisión de datos o bit rate. Con frecuencia se usa en forma ambigua como bps, que para el SI significaría "bits por segundos"', 'byte/s'),
('P94', 'Kilobyte por segundo', '1000-veces la unidad de byte dividida por la unidad de base SI en segundo lugar.', 'kbyte/s'),
('P95', 'Megabite por segundo', '1 000 000 veces de la unidad de byte dividida por la unidad base SI segunda', 'Mbyte/s'),
('P96', 'Recíproco de la unidad si deriva voltio', 'Recíproco de la unidad SI deriva voltio', '1/V'),
('P97', 'Reciprocidad de Radian', 'Recíproco de la unidad radian', '1/rad'),
('P98', 'Pascal a la suma de potencia de los números estequimetricos', 'Unidad de la constante de equilibrio sobre la base de la presión (ISO 80000-9: 2009, 9-35.a).', 'PaΣνB'),
('P99', 'Mols por metro cúbico a la suma de potencia de los números estequimetricos', 'Unidad de la constante de equilibrio sobre la base de la concentración (ISO 80000-9: 2009, 9-36.a).', '(mol/m³)∑νB'),
('PAL', 'Pascal', 'Es la presión uniforme que, actuando sobre una superficie plana de 1 metro cuadrado, ejerce perpendicularmente a esta superficie una fuerza total de 1 newton.', 'Pa'),
('PB', 'Par de la pulgada', NULL, NULL),
('PD', 'Almohadilla', 'Unidad de conteo que define el número de almohadillas (almohadilla: bloquea de hojas de papel sujetas juntas en un extremo).', NULL),
('PE', 'Libra equivalente', NULL, NULL),
('PFL', 'Litro de prueba', 'Unidad de volumen igual a un litro de alcoholes de prueba, o su equivalente alcohólico. Se utiliza para medir la concentración de licores alcohólicos destilados, expresada como porcentaje del contenido en alcohol de una mezcla patrón a una tempreatura específica.', NULL),
('PGL', 'Galón de prueba', 'Unidad de volumen igual a un galón de alcoholes de prueba, o su equivalente alcohólico. Se utiliza para medir la concentración de licores alcohólicos destilados, expresada como porcentaje del contenido en alcohol de una mezcla patrón a una temperatura específica.', NULL),
('PI', 'Tono', 'Unidade de conteo que define el número de caracteres que se ajustan en una pulgada horizontal', NULL),
('PLA', 'Grado de platón', 'Unidad de proporción que define el contenido de azúcar de un producto, especialmente en relación con la cerveza', '°P'),
('PM', 'Porcentaje de libra', NULL, NULL),
('PO', 'Libra por pulgada', NULL, 'lb/in'),
('PQ', 'Página por pulgada', 'Unidad de cantidad que define el grado de espesor de una publicación enlazada, expresada como el número de páginas por pulgada de espesor.', 'ppi'),
('PR', 'Par', 'Unidad de conteo que define el número de pares (par: descripción por 2)', NULL),
('PS', 'Libra fuerza por pulgada cuadrada', NULL, 'lbf/in²'),
('PT', 'Pinta (US)', 'Utilice pinta líquida (código común PTL)', 'Pt (US)'),
('PTD', 'Pinta seca (estados unidos)', NULL, 'dry pt (US)'),
('PTI', 'Pint (uk)', 'Es una unidad de volumen inglesa en el sistema imperial y los Estados Unidos. La versión imperial usada en el UK es de 20 onzas líquidas y es equivalente a 568,26125 ml, mientras que en los EUA es de 16 onzas líquidas y es equivalente a 473,17647 ml.', 'pt (UK)'),
('PTL', 'Pinta líquida (estados unidos)', NULL, 'liq pt (US)'),
('PTN', 'Parte', 'Cantidad de alimentos asignados o suficientes para una persona', 'PTN'),
('PV', 'Media pinta (US)', NULL, NULL),
('PW', 'Libra por pulgada de ancho', NULL, NULL),
('PY', 'Pico seco (EUA)', NULL, NULL),
('PZ', 'Peck dry (UK)', NULL, NULL),
('Q10', 'Joule por tesla', 'Unidad del momento dipolar magnético de la molécula como derivado de la unidad SI joule dividido por la unidad SI derivada Tesla', 'J/T'),
('Q11', 'Erlang', 'Unidad del valor del mercado de acuerdo con la caracteristica de una sola característica como una medición estadística de la utilización existente', 'E'),
('Q12', 'Octeto', 'Sinónimo por byte: 1octet =8bit = 1byte', 'o'),
('Q13', 'Octeto por segundo', 'Unidad octeto dividido por la unidad base SI segundo', 'o/s'),
('Q14', 'Shannon', 'Unidad logarítmica para la información igual al contenido de la decisión de una oración de dos sucesos mutuamente excluyentes, expresada como un logaritmo a la base 2.', 'Sh'),
('Q15', 'Hartley', 'Unidad logarítmica para la información igual al contenido de la decisión de una oración de diez sucesos mutuamente excluyentes, expresada como un logaritmo base 10.', 'Hart'),
('Q16', 'Unidad natural de información', 'Unidad logarítmica para información igual al contenido de la decisión de una oración de 718 281 828 459 sucesos mutuamente excluyentes, expresada como un logaritmo para basar el valor de Euler e.', 'nat'),
('Q17', 'Shannon por segundo', 'Unidad logarítmica relacionada con el tiempo para información igual al contenido de la decisión de una oración de dos sucesos mutuamente excluyentes, expresada como logarítmo base 2.', 'Sh/s'),
('Q18', 'Hartley por segundo', 'Unidad logaritmica relacionada con el tiempo para información igual al contenido de la decisión de una oración de diez sucesos mutuamente excluyentes, expresada como un logartimo a la base 10.', 'Hart/s'),
('Q19', 'Unidad natural de información por segundo', 'Unidad logarítmica relacionada con el tiempo para información igual al contenido de la decisión de una oración 2.718281828459 mutuamente excluyentes, expresado como un logarítmo a la base del valor de Euler', 'nat/s'),
('Q20', 'Segundo por kilogramo', 'Unidad de la probabilidad de transición de Einsten para emisiones espontáneas o inductoras y absorción según ISO 80000-7, expresada como unidad base SI segundo dividida por la unidad base kilogramo.', 's/kg'),
('Q21', 'Watt metro cuadrado', 'Unidad de las primeras constantes de radiación c1=2.p.c0, cuyo valor es 3.74177118.10 6 veces la del valor comparativo del producto de la unidad SI deriva watts multiplicada con la potencia de la SI medidor de la unidad base con el exponente 2.', 'W·m²'),
('Q22', 'Segundo por metro cúbicos de radianes', 'Unidad de la densidad de estados como una expresión de la frecuencia angular como complemento del producto de hertzio y radiante y la potencia del medidor de la unidad base SI por exponente 3.', '1/(Hz·rad·m³)'),
('Q23', 'Weber a la potencia menos uno', 'Complemento de la unidad SI deriva weber como unidad de la constante de Joshepson, cuyo valor es igual al 384,597,891 veces del valor de referencia gigahertz dividido  por volt. 4', '1/Wb'),
('Q24', 'Reciprocidad de Pulgada', 'Complemento de la unidad pulgada según el sistema de unidades Anglo-Americanas e Imperial', '1/in'),
('Q25', 'Dioptría', 'Unidad utilizada en la declaración de índices de refracción relativos de sistemas ópticos como complemento de la longitud focal con correspondencia con: 1dpt=1/m.', 'dpt'),
('Q26', 'Uno por uno', 'Valor del cociente de dos unidades físicas del mismo tipo que un numerador y denominador mientras que las unidades se acortan mutuamente', '1/1'),
('Q27', 'Newtons metros por metro', 'Unidad para el momento de rotación relacionado con la longitud como producto de la unidad SI derivada por el medidor de la unidad SI', 'N·m/m²'),
('Q28', 'Kilograma por metro cuadrado pascal segundo', 'Unidad para la capacidad de un material para permitir la transición del vapor', 'kg/(m²·Pa·s)'),
('Q29', 'Microgramo por hectogramo', 'Microgramo por hectogramo', 'µg/hg'),
('Q3', 'Comida', 'Unidad de conteo que define el número de comida', NULL),
('Q30', 'Ph (potencial de hidrogeno)', 'Es una escala numérica utilizada para especificar la acidez o basicidad de una solución acuosa .', 'pH'),
('Q31', 'Kilojoule por gramo', NULL, 'kJ/g'),
('Q32', 'Femtolitro', NULL, 'fl'),
('Q33', 'Picolitro', NULL, 'pl'),
('Q34', 'Nanolitro', NULL, 'nl'),
('Q35', 'Megawatts por minuto', 'Unidad de potencia que define la cantidad total de energía mayor transferida o consumida en un minuto.', 'MW/min'),
('Q36', 'Metro cuadrado por metro cúbico', 'Unidad de la cantidad de superficie por unidad de volumen de un objeto o colección de objetos', 'm2/m3'),
('Q37', 'Metro cúbico estándar por día', 'Metro cúbico estándar (temperatura 15 ° C y presión 101325 milibares) por día', NULL),
('Q38', 'Metro cúbico estándar por hora', 'Metro cúbico estándar (temperatura 15 ° C y presión 101325 milibares) por día', NULL),
('Q39', 'Metro cúbico normalizado por día', 'Metro cúbico estándar (temperatura 0° C y presión 101325 milibares) por día', NULL),
('Q40', 'Metro cúbico normalizado por hora', 'Metro cúbico estándar (temperatura 0° C y presión 101325 milibares) por día', NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();