INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('G50', 'Galón por hora', NULL, 'gal/h'),
('G51', 'Litro por segundo', NULL, 'l/s'),
('G52', 'Metro cúbico por día', NULL, 'm³/d'),
('G53', 'Metro cúbico por minuto', NULL, 'm³/min'),
('G54', 'Mililitro por día', NULL, 'ml/d'),
('G55', 'Mililitro por hora', NULL, 'ml/h'),
('G56', 'Pulgada cúbica por hora', NULL, 'in³/h'),
('G57', 'Pulgada cúbica por minuto', NULL, 'in³/min'),
('G58', 'Pulgada cúbica por segundo', NULL, 'in³/s'),
('G59', 'Miliamperio por litro minuto', NULL, 'mA/(l·min)'),
('G60', 'Voltio por bar', NULL, 'V/bar'),
('G61', 'Centímetro cúbico por día kelvin', NULL, 'cm³/(d·K)'),
('G62', 'Centímetro cúbico por hora kelvin', NULL, 'cm³/(h·K)'),
('G63', 'Centímetro cúbico por minuto kelvin', NULL, 'cm³/(min·K)'),
('G64', 'Centímetro cúbico por segundo kelvin', NULL, 'cm³/(s·K)'),
('G65', 'Litro por día kelvin', NULL, 'l/(d·K)'),
('G66', 'Litro por hora kelvin', NULL, 'l/(h·K)'),
('G67', 'Litro por minuto kelvin', NULL, 'l/(min·K)'),
('G68', 'Litro por segundo kelvin', NULL, 'l/(s·K)'),
('G69', 'Metro cúbico por día kelvin', NULL, 'm³/(d·K)'),
('G7', 'Hoja de microficha', NULL, NULL),
('G70', 'Metro cúbico por hora kelvin', NULL, 'm³/(h·K)'),
('G71', 'Metro cúbico por minuto kelvin', NULL, 'm³/(min·K)'),
('G72', 'Metro cúbico por segundo kelvin', NULL, 'm³/(s·K)'),
('G73', 'Mililitro por día kelvin', NULL, 'ml/(d·K)'),
('G74', 'Mililitro por hora kelvin', NULL, 'ml/(h·K)'),
('G75', 'Mililitro por minuto kelvin', NULL, 'ml/(min·K)'),
('G76', 'Mililitro por segundo kelvin', NULL, 'ml/(s·K)'),
('G77', 'Milímetro a la cuarta potencia', NULL, 'mm⁴'),
('G78', 'Centímetro cúbico por día bar', NULL, 'cm³/(d·bar)'),
('G79', 'Centímetro cúbico por hora bar', NULL, 'cm³/(h·bar)'),
('G80', 'Centímetro cúbico por minuto bar', NULL, 'cm³/(min·bar)'),
('G81', 'Centímetro cúbico por segundo bar', NULL, 'cm³/(s·bar)'),
('G82', 'Litro por día bar', NULL, 'l/(d·bar)'),
('G83', 'Litro por hora bar', NULL, 'l/(h·bar)'),
('G84', 'Litro por minuto bar', NULL, 'l/(min·bar)'),
('G85', 'Litro por segundo bar', NULL, 'l/(s·bar)'),
('G86', 'Metro cúbico por día bar', NULL, 'm³/(d·bar)'),
('G87', 'Metro cúbico por hora bar', NULL, 'm³/(h·bar)'),
('G88', 'Metro cúbico por minuto bar', NULL, 'm³/(min·bar)'),
('G89', 'Metro cúbico por segundo bar', NULL, 'm³/(s·bar)'),
('G90', 'Mililitro por día bar', NULL, 'ml/(d·bar)'),
('G91', 'Mililitro por hora bar', NULL, 'ml/(h·bar)'),
('G92', 'Mililitro por minuto bar', NULL, 'ml/(min·bar)'),
('G93', 'Mililitro por segundo bar', NULL, 'ml/(s·bar)'),
('G94', 'Centímetro cúbico por bar', NULL, 'cm³/bar'),
('G95', 'Litro por bar', NULL, 'l/bar'),
('G96', 'Metro cúbico por bar', NULL, 'm³/bar'),
('G97', 'Mililitro por bar', NULL, 'ml/bar'),
('G98', 'Micro henry por kiloOhm', NULL, 'µH/kΩ'),
('G99', 'Micro henry por Ohm', NULL, 'µH/Ω'),
('GB', 'Galón (EUA) por día', NULL, 'gal (US)/d'),
('GBQ', 'Gigabecquerel', NULL, 'GBq'),
('GC', 'Gramo por 100 gramos', NULL, NULL),
('Gd', 'Barril bruto', NULL, NULL),
('GDW', 'Gramo, peso seco', 'Unidad de masa que define el número de gramos de un producto, sin tener en cuenta el contenido de agua del producto.', NULL),
('GE', 'Libra por galón (EUA)', NULL, 'lb/gal (US)'),
('GF', 'Gramo por metro (gramo por 100 centímetros)', NULL, 'g/m'),
('GFI', 'Gramo de isótopo fisible', 'Unidad de masa que define el número de gramos de un isótopo fisible (isótopo fisible: un isótopo cuyo núcleo es capaz de ser dividido cuando se irradia con neutrones de baja energía).', 'gi F/S'),
('GGR', 'Grandioso', 'Unidad de cuenta que define el número de unidades en múltiplos de 1728 (12 x 12 x 12).', NULL),
('GH', 'Medio galón (US)', NULL, NULL),
('GIA', 'Gill (us)', 'Es Unidad de volumen inglesa en el sistema imperial y en los Estados Unidos. La versión imperial usada en el UK es de 5 onzas líquidas, y es equivalente a 142,0653125 ml; mientras que en los EUA es de 4 onzas líquidas, y es equivalente a 118,29411825 ml.', 'gi (US)'),
('GIC', 'Gramo, incluido el contenedor', 'Unidad de masa que define el número de gramos de un producto, incluyendo su recipiente.', NULL),
('GII', 'Gill (uk)', 'Es Unidad de volumen inglesa en el sistema imperial y en los Estados Unidos. La versión imperial usada en el UK es de 5 onzas líquidas, y es equivalente a 142.0653125 ml; mientras que en los EUA es de 4 onzas líquidas, y es equivalente a 118.29411825 ml.', 'gi (UK)'),
('GIP', 'Grama, incluido el embalaje interior', 'Unidad de masa que define el número de gramos de un producto, incluyendo sus materiales de envasado interior.', NULL),
('GJ', 'Gramo por mililitro', NULL, 'g/ml'),
('GK', 'Gramo por kilogramo', NULL, NULL),
('GL', 'Gramo por litro', NULL, 'g/l'),
('GLD', 'Galón seco (EUA)', NULL, 'dry gal (US)'),
('GLI', 'Galón (UK)', 'Es una unidad de volumen que se emplea en los países anglófonos (especialmente Estados Unidos) o con influencia de estos (como Liberia, Guatemala, Panamá, Honduras, Nicaragua, El Salvador, Colombia y parcialmente en México), para medir volúmenes de líquidos, principalmente la gasolina y su precio. Antiguamente, el volumen de un galón dependía de lo que se midiera, y dónde. Sin embargo, en el siglo XIX existían dos definiciones de uso común: "galón de vino" (wine gallon) y "galón de cerveza británico" (ale gallon).
Es equivalente a 3.7854 litros.', 'gal (UK)'),
('GLL', 'Galón (EUA)', 'Es una unidad de volumen que se emplea en los países anglófonos (especialmente Estados Unidos) o con influencia de estos (como Liberia, Guatemala, Panamá, Honduras, Nicaragua, El Salvador, Colombia y parcialmente en México), para medir volúmenes de líquidos, principalmente la gasolina y su precio. Antiguamente, el volumen de un galón dependía de lo que se midiera, y dónde. Sin embargo, en el siglo XIX existían dos definiciones de uso común: "galón de vino" (wine gallon) y "galón de cerveza británico" (ale gallon).', 'gal (US)'),
('GM', 'Gramo por metro cuadrado', NULL, 'g/m²'),
('GN', 'Galón bruto', NULL, NULL),
('GO', 'Miligramo por metro cuadrado', NULL, 'mg/m²'),
('GP', 'Miligramo por metro cúbico', NULL, 'mg/m³'),
('GQ', 'Microgramo por metro cúbico', NULL, 'µg/m³'),
('GRM', 'Gramo', 'Medida de masa, de símbolo g, que es igual a la milésima parte de un kilogramo.', 'g'),
('GRN', 'Grano', 'Es la mínima unidad de masa en el sistema inglés de medidas. Se considera con el mismo valor en cualquier país anglosajón. Se utiliza para estimar con más sensibilidad y precisión la poca masa de pequeños objetos (medicamentos, drogas, pólvora, proyectiles, piezas de joyería, etc.).', 'gr'),
('GRO', 'Gross', 'Unidad de conteo que define el número de unidades en múltiplos de 144 (12 x 12).', 'gr'),
('GT', 'Tonelada bruta', 'Una unidad de masa igual a 2240 libras. Véase el Convenio internacional sobre arqueo de buques.

Sinónimo: ton (UK) o tonelada larga (US) (código común LTN)', NULL),
('GV', 'Gigajoule', NULL, 'GJ'),
('GW', 'Galón por mil pies cúbicos', NULL, NULL),
('GWH', 'Gigawatt hora', NULL, 'GW·h'),
('GY', 'Patio grueso', NULL, NULL),
('GZ', 'Sistema de calibración', NULL, NULL),
('H03', 'Henry por kiloOhm', NULL, 'H/kΩ'),
('H04', 'Henry por Ohm', NULL, 'H/Ω'),
('H05', 'Milihenry por kiloOhm', NULL, 'mH/kΩ'),
('H06', 'Milihenry por Ohm', NULL, 'mH/Ω'),
('H07', 'Pascal segundo por bar', NULL, 'Pa·s/bar'),
('H08', 'Microbequerel', NULL, 'µBq'),
('H09', 'Año recíproco', NULL, '1/y'),
('H1', 'Media página - electrónica', NULL, NULL),
('H10', 'Hora recíproca', NULL, '1/h'),
('H11', 'Mes recíproco', NULL, '1/mo'),
('H12', 'Grado celsius por hora', NULL, '°C/h'),
('H13', 'Grado celsius por minuto', NULL, '°C/min'),
('H14', 'Grado celsius por segundo', NULL, '°C/s'),
('H15', 'Centímetro cudrado por gramo', NULL, 'cm²/g'),
('H16', 'Decámetro cuadrado', NULL, 'dam²')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();