INSERT INTO public.cat_cfdi_unidades (code, name, description, symbol)
VALUES ('XTC', 'Caja para té', NULL, NULL),
('XTD', 'Tubo plegable', NULL, NULL),
('XTG', 'Contenedor de tanque genérico', 'Recipiente especialmente construido para el transporte de líquidos y gases a granel.', NULL),
('XTI', 'Tierce', 'Barril de 1/6 parte de tonel', NULL),
('XTK', 'Tanque rectangular', NULL, NULL),
('XTL', 'Tina con tapa', NULL, NULL),
('XTN', 'Hojalata', NULL, NULL),
('XTO', 'Tonel', 'Barril con capacidad para 982 litros', NULL),
('XTR', 'Maletero', NULL, NULL),
('XTS', 'Estructura', NULL, NULL),
('XTT', 'Bolsa de mano', 'Una gran bolsa o cesto.', NULL),
('XTU', 'Tubo', NULL, NULL),
('XTV', 'Tubo con boquilla', 'Tubo de plástico, metal o cartón, provisto de una boquilla, que contiene un producto líquido o semilíquido, por ejemplo silicio.', NULL),
('XTW', 'Pallet tricapa', 'Una paleta ligera hecha de cartón ondulado resistente.', NULL),
('XTY', 'Tanque cilíndrico', NULL, NULL),
('XTZ', 'Tubos  con fleje/ agrupados/ armados', NULL, NULL),
('XUC', 'Sin empaque', NULL, NULL),
('XUN', 'Unidad', 'Tipo de paquete compuesto de un solo artículo u objeto, no especificado de otro modo como una unidad de equipo de transporte.', NULL),
('XVA', 'Tanque', NULL, NULL),
('XVG', 'Tanque de gas (a 1,031 mbar y 15° C)', NULL, NULL),
('XVI', 'Frasco pequeño', NULL, NULL),
('XVK', 'Paquete transportable', 'Tipo de cajón de madera.', NULL),
('XVL', 'Contenedor para líquidos a granel', NULL, NULL),
('XVN', 'Vehículo', 'Medio de transporte autopropulsado.', NULL),
('XVO', 'Contenedor para sólido de partículas grandes a granel ("nódulos")', NULL, NULL),
('XVP', 'Envasado al vacío', NULL, NULL),
('XVQ', 'Tanque para Gas licuado (a temperatura / presión anormal)', NULL, NULL),
('XVR', 'Contenedor para sólidos de partículas granulares a granel (Granos)', NULL, NULL),
('XVS', 'Contenedor de chatarra a granel', 'Chatarra suelta o sin empaquetar transportada a granel.', NULL),
('XVY', 'Contenedor para sólido de partículas finas a granel ("polvos")', NULL, NULL),
('XWA', 'Contenedor de granel intermedio', 'Recipiente reutilizable hecho de metal, plástico, textiles, madera o materiales compuestos utilizados para facilitar el transporte de sólidos y líquidos a granel en volúmenes manejables.', NULL),
('XWB', 'Botella de mimbre', NULL, NULL),
('XWC', 'Contenedor intermedio para gráneles y de acero', NULL, NULL),
('XWD', 'Contenedor intermedio para gráneles y de aluminio', NULL, NULL),
('XWF', 'Contenedor intermedio para gráneles y de metal', NULL, NULL),
('XWG', 'Contenedor intermedio para gráneles y de acero presurizado menor a 10 kpa', NULL, NULL),
('XWH', 'Contenedor intermedio para gráneles y de aluminio, presurizado menor a 10 kpa', NULL, NULL),
('XWJ', 'Contenedor intermedio para gráneles y de metal con una presión de 10 kpa', NULL, NULL),
('XWK', 'Contenedor intermedio para gráneles y de acero para líquido', NULL, NULL),
('XWL', 'Contenedor intermedio para gráneles y de aluminio para líquido', NULL, NULL),
('XWM', 'Contenedor intermedio para gráneles y de metal para líquido', NULL, NULL),
('XWN', 'Contenedor intermedio para gráneles con tejido plástico sin capa con revestimiento', NULL, NULL),
('XWP', 'Contenedor intermedio para gráneles con tejido plástico y recubierto', NULL, NULL),
('XWQ', 'Contenedor intermedio para gráneles con tejido plástico con revestimiento', NULL, NULL),
('XWR', 'Contenedor intermedio para gráneles con tejido plástico, revestido y con forro', NULL, NULL),
('XWS', 'Contenedor intermedio para gráneles con película de plástico', NULL, NULL),
('XWT', 'Contenedor intermedio para gráneles textil sin capa / forro', NULL, NULL),
('XWU', 'Contenedor intermedio para gráneles de madera natural con forro interior', NULL, NULL),
('XWV', 'Contenedor intermedio para gráneles textil recubierto', NULL, NULL),
('XWW', 'Contenedor intermedio para gráneles textil con revestimiento', NULL, NULL),
('XWX', 'Contenedor intermedio para gráneles textil recubierto y con forro', NULL, NULL),
('XWY', 'Contenedor intermedio para gráneles contrachapado con revestimiento interior', NULL, NULL),
('XWZ', 'Contenedor intermedio para gráneles de madera reconstituida con revestimiento interior', NULL, NULL),
('XXA', 'Bolsa de tejido plástico, sin abrigo interior ni forro', NULL, NULL),
('XXB', 'Bolsa de tejido plástico a prueba de filtraciones', NULL, NULL),
('XXC', 'Bolsa de tejido plástico resistente al agua', NULL, NULL),
('XXD', 'Bolsa con película de plástico', NULL, NULL),
('XXF', 'Bolsa textil sin capa ni forro interior', NULL, NULL),
('XXG', 'Bolsa textil a prueba de filtraciones', NULL, NULL),
('XXH', 'Bolsa textil resistente al agua', NULL, NULL),
('XXJ', 'Bolsa de papel multi-pared', NULL, NULL),
('XXK', 'Bolsa de papel multi-pared, resistente al agua', NULL, NULL),
('XYA', 'Empaque compuesto, recipiente de plástico en tambor de acero', NULL, NULL),
('XYB', 'Empaque compuesto, recipiente de plástico en cajas de acero', NULL, NULL),
('XYC', 'Empaque compuesto, recipiente de plástico en tambor de aluminio', NULL, NULL),
('XYD', 'Empaque compuesto, recipiente de plástico en cajón de aluminio', NULL, NULL),
('XYF', 'Empaque compuesto, recipiente de plástico en caja de madera', NULL, NULL),
('XYG', 'Empaque compuesto, recipiente de plástico en tambor de madera contrachapada', NULL, NULL),
('XYH', 'Empaque compuesto, recipiente de plástico en caja de madera contrachapada', NULL, NULL),
('XYJ', 'Empaque compuesto, recipiente de plástico en tambor de fibra', NULL, NULL),
('XYK', 'Empaque compuesto, recipiente de plástico en caja de cartón', NULL, NULL),
('XYL', 'Empaque compuesto, recipiente de plástico en el tambor de plástico', NULL, NULL),
('XYM', 'Empaque compuesto, recipiente de plástico en caja de plástico sólido', NULL, NULL),
('XYN', 'Empaque compuesto, receptáculo de vidrio en tambor de acero', NULL, NULL),
('XYP', 'Empaque compuesto, receptáculo de vidrio en caja de cajas de acero', NULL, NULL),
('XYQ', 'Empaque compuesto, recipiente de vidrio en tambor de aluminio', NULL, NULL),
('XYR', 'Empaque compuesto, receptáculo de vidrio en caja de aluminio', NULL, NULL),
('XYS', 'Empaque compuesto, recipiente de vidrio en caja de madera', NULL, NULL),
('XYT', 'Empaque compuesto, recipiente de vidrio en tambor de madera contrachapada', NULL, NULL),
('Xyv', 'Empaque compuesto, recipiente de vidrio en el cesto de mimbre', NULL, NULL),
('XYW', 'Empaque compuesto, recipiente de vidrio en tambor de fibra', NULL, NULL),
('XYX', 'Empaque compuesto, recipiente de vidrio en caja de cartón', NULL, NULL),
('XYY', 'Empaque compuesto, recipiente de vidrio en paquete de plástico expandible', NULL, NULL),
('XYZ', 'Empaque compuesto, recipiente de vidrio en paquete de plástico sólido', NULL, NULL),
('XZA', 'Contenedor de granel intermedio, papel, multi-pared', NULL, NULL),
('XZB', 'Bolsa grande', NULL, NULL),
('XZC', 'Contenedor intermedio para gráneles de papel, multi-pared y resistente al agua', NULL, NULL),
('XZD', 'Contenedor intermedio para gráneles de plástico rígido, con equipo estructural para sólidos', NULL, NULL),
('XZF', 'Contenedor intermedio para gráneles de plástico rígido, autoportante para sólidos', NULL, NULL),
('XZG', 'Contenedor intermedio para gráneles de plástico rígido, con equipo estructural, presurizado', NULL, NULL),
('XZH', 'Contenedor intermedio para gráneles de plástico rígido, autoportante y presurizado', NULL, NULL),
('XZJ', 'Contenedor intermedio para gráneles de plástico rígido, con equipo estructural para líquidos', NULL, NULL),
('XZK', 'Contenedor intermedio para gráneles de plástico rígido, autoportante, líquidos', NULL, NULL),
('XZL', 'Contenedor intermedio para gráneles, compuesto y de plástico rígido, sólidos', NULL, NULL),
('XZM', 'Contenedor intermedio para gráneles, compuesto y de plástico flexible, sólidos', NULL, NULL),
('XZN', 'Contenedor intermedio para gráneles, compuesto y de plástico rígido, presurizado', NULL, NULL),
('XZP', 'Contenedor intermedio para gráneles, compuesto y de plástico flexible, presurizado', NULL, NULL),
('XZQ', 'Contenedor intermedio para gráneles, compuesto y de plástico rígido, líquidos', NULL, NULL),
('XZR', 'Contenedor intermedio para gráneles, compuesto y de plástico flexible para líquidos', NULL, NULL),
('XZS', 'Contenedor intermedio para gráneles, compuesto', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    symbol = EXCLUDED.symbol,
    updated_at = NOW();