INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('236222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('237111', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;