INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468212', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468213', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('468311', '50', 1.0, 'Vínculo sectorial: Comercio al por menor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;