INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811312', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811313', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811314', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;