INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541610', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541620', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541690', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541941', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('541943', '80', 1.0, 'Vínculo sectorial: Servicios profesionales, científicos y técnicos') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;