INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811121', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811122', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811122', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811122', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811122', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811122', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811129', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811191', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811192', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811199', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811211', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811219', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811311', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;