INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812110', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812120', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812130', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812130', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812130', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812130', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('812210', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('113211', '10', 1.0, 'Vínculo sectorial: Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;