INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811410', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811420', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811430', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811491', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811492', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811492', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811492', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811492', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811492', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811493', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811493', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811493', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811493', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('811499', '72', 1.0, 'Vínculo sectorial: Otros servicios excepto actividades gubernamentales') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;