INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238390', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238910', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238990', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('431110', '24', 1.0, 'Vínculo sectorial: Comercio al por mayor') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;