INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238130', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238221', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238222', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;INSERT INTO public.rel_activity_cps_congruence (activity_code, cps_family_code, score, reason) 
VALUES ('238311', '72', 1.0, 'Vínculo sectorial: Construcción') 
ON CONFLICT (activity_code, cps_family_code) DO NOTHING;